/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/home/renzhen/Nim12.0/lib -o src/nimcache/client.o src/nimcache/client.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#include <setjmp.h>
#include <sys/types.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct FutureHEX3Aobjecttype195302 FutureHEX3Aobjecttype195302;
typedef struct Asyncsocketdesc209202 Asyncsocketdesc209202;
typedef struct TY250210 TY250210;
typedef struct FuturebaseHEX3Aobjecttype195018 FuturebaseHEX3Aobjecttype195018;
typedef struct FutureHEX3Aobjecttype202887 FutureHEX3Aobjecttype202887;
typedef struct Message249005 Message249005;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell55949 Cell55949;
typedef struct Cellseq55965 Cellseq55965;
typedef struct Gcheap58018 Gcheap58018;
typedef struct Gcstack58016 Gcstack58016;
typedef struct Cellset55961 Cellset55961;
typedef struct Pagedesc55957 Pagedesc55957;
typedef struct Memregion37891 Memregion37891;
typedef struct Smallchunk37843 Smallchunk37843;
typedef struct Llchunk37885 Llchunk37885;
typedef struct Bigchunk37845 Bigchunk37845;
typedef struct Intset37817 Intset37817;
typedef struct Trunk37813 Trunk37813;
typedef struct Avlnode37889 Avlnode37889;
typedef struct Gcstat58014 Gcstat58014;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct Flowvarobj250295 Flowvarobj250295;
typedef struct TY250343 TY250343;
typedef struct Flowvarbaseobj154247 Flowvarbaseobj154247;
typedef struct Semaphore154008 Semaphore154008;
typedef struct Awaitinfo154243 Awaitinfo154243;
typedef struct TY250434 TY250434;
typedef struct Basechunk37841 Basechunk37841;
typedef struct Freecell37833 Freecell37833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef struct {
N_NIMCALL_PTR(FuturebaseHEX3Aobjecttype195018*, ClPrc) (void* ClEnv);
void* ClEnv;
} TY208102;
struct  Message249005  {
NimStringDesc* username;
NimStringDesc* message;
};
struct  TY250210  {
NI HEX3Astate;
NimStringDesc* serveraddr250021;
Asyncsocketdesc209202* socket250020;
FutureHEX3Aobjecttype195302* retfuture250014;
TY208102 nameitervar250065;
FutureHEX3Aobjecttype195302* future250016;
FutureHEX3Aobjecttype202887* future250017;
NimStringDesc* line250059;
Message249005 parsed250060;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell55949  {
NI refcount;
TNimType* typ;
};
struct  Cellseq55965  {
NI len;
NI cap;
Cell55949** d;
};
struct  Cellset55961  {
NI counter;
NI max;
Pagedesc55957* head;
Pagedesc55957** data;
};
typedef Smallchunk37843* TY37906[512];
typedef Trunk37813* Trunkbuckets37815[256];
struct  Intset37817  {
Trunkbuckets37815 data;
};
struct  Memregion37891  {
NI minlargeobj;
NI maxlargeobj;
TY37906 freesmallchunks;
Llchunk37885* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk37845* freechunkslist;
Intset37817 chunkstarts;
Avlnode37889* root;
Avlnode37889* deleted;
Avlnode37889* last;
Avlnode37889* freeavlnodes;
};
struct  Gcstat58014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap58018  {
Gcstack58016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq55965 zct;
Cellseq55965 decstack;
Cellset55961 cycleroots;
Cellseq55965 tempstack;
NI recgclock;
Memregion37891 region;
Gcstat58014 stat;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19611;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19611 raiseAction;
};
typedef N_CLOSURE_PTR(FuturebaseHEX3Aobjecttype195018*, TMP1205) (void);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY195019;
struct  FuturebaseHEX3Aobjecttype195018  {
  TNimObject Sup;
TY195019 cb;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorstacktrace;
NimStringDesc* stacktrace;
NI id;
NimStringDesc* fromproc;
};
struct  FutureHEX3Aobjecttype195302  {
  FuturebaseHEX3Aobjecttype195018 Sup;
};
typedef N_CLOSURE_PTR(void, TMP1207) (void);
struct  TY250343  {
Flowvarobj250295* fv250346;
};
typedef N_NIMCALL_PTR(void, Workerproc154255) (void* thread, void* args);
struct  Semaphore154008  {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
struct  Flowvarbaseobj154247  {
  TNimObject Sup;
NIM_BOOL ready;
NIM_BOOL usessemaphore;
NIM_BOOL awaited;
Semaphore154008 cv;
Awaitinfo154243* ai;
NI idx;
void* data;
void* owner;
};
struct  Flowvarobj250295  {
  Flowvarbaseobj154247 Sup;
NimStringDesc* blob;
};
struct  TY250434  {
Flowvarobj250295* fv250437;
};
typedef NIM_CHAR TY209209[4001];
struct  Asyncsocketdesc209202  {
int fd;
NIM_BOOL closed;
NIM_BOOL isbuffered;
union{
struct {TY209209 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NIM_BOOL isssl;
NU8 domain;
NU8 socktype;
NU8 protocol;
};
struct  FutureHEX3Aobjecttype202887  {
  FuturebaseHEX3Aobjecttype195018 Sup;
NimStringDesc* value;
};
struct  Gcstack58016  {
Gcstack58016* prev;
Gcstack58016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY37822[8];
struct  Pagedesc55957  {
Pagedesc55957* next;
NI key;
TY37822 bits;
};
struct  Basechunk37841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk37843  {
  Basechunk37841 Sup;
Smallchunk37843* next;
Smallchunk37843* prev;
Freecell37833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk37885  {
NI size;
NI acc;
Llchunk37885* next;
};
struct  Bigchunk37845  {
  Basechunk37841 Sup;
Bigchunk37845* next;
Bigchunk37845* prev;
NI align;
NF data;
};
struct  Trunk37813  {
Trunk37813* next;
NI key;
TY37822 bits;
};
typedef Avlnode37889* TY37896[2];
struct  Avlnode37889  {
TY37896 link;
NI key;
NI upperbound;
NI level;
};
struct  Awaitinfo154243  {
Semaphore154008 cv;
NI idx;
};
struct  Freecell37833  {
Freecell37833* next;
NI zerofield;
};
N_NIMCALL(NimStringDesc*, readinput_250004)(void);
N_NIMCALL(NimStringDesc*, readline_16916)(FILE* f);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_30201)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(FutureHEX3Aobjecttype195302*, connect_250018)(Asyncsocketdesc209202* socket, NimStringDesc* serveraddr);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP1199)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell55949*, usrtocell_59673)(void* usr);
static N_INLINE(void, rtladdzct_61204)(Cell55949* c);
N_NOINLINE(void, addzct_59644)(Cellseq55965* s, Cell55949* c);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(FutureHEX3Aobjecttype195302*, newfuture_202573)(NimStringDesc* fromproc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_62022)(Cell55949* c);
static N_INLINE(NIM_BOOL, canbecycleroot_59694)(Cell55949* c);
static N_INLINE(void, rtladdcycleroot_60423)(Cell55949* c);
N_NOINLINE(void, incl_56665)(Cellset55961* s, Cell55949* cell);
static N_INLINE(void, decref_61604)(Cell55949* c);
N_CLOSURE(FuturebaseHEX3Aobjecttype195018*, connectiter_250015)(void* ClEnv);
N_NIMCALL(FutureHEX3Aobjecttype195302*, connect_209604)(Asyncsocketdesc209202* socket, NimStringDesc* address, NU16 port);
N_NIMCALL(void, read_209625)(FutureHEX3Aobjecttype195302* future);
N_NIMCALL(FutureHEX3Aobjecttype202887*, recvline_216048)(Asyncsocketdesc209202* socket, NU8 flags);
N_NIMCALL(NimStringDesc*, read_208112)(FutureHEX3Aobjecttype202887* future);
N_NIMCALL(void, parsemessage_249013)(NimStringDesc* data, Message249005* Result);
N_NIMCALL(void, complete_195295)(FutureHEX3Aobjecttype195302* future);
N_CLOSURE(void, cb_250068)(void* ClEnv);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished_208637)(TY208102 x);
N_NIMCALL(void, failedassertimpl_99603)(NimStringDesc* msg);
N_NIMCALL(void, callbackHEX3D_195853)(FuturebaseHEX3Aobjecttype195018* future, TY195019 cb);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, fail_202633)(FutureHEX3Aobjecttype195302* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(NI, paramcount_144635)(void);
N_NIMCALL(void, quit_98791)(NimStringDesc* errormsg, NI errorcode) __attribute__((noreturn));
N_NIMCALL(NimStringDesc*, paramstr_144613)(NI i);
N_NIMCALL(Asyncsocketdesc209202*, newasyncsocket_209424)(NU8 domain, NU8 socktype, NU8 protocol, NIM_BOOL buffered);
N_NIMCALL(void, asynccheck_250257)(FutureHEX3Aobjecttype195302* future);
N_NIMCALL(Flowvarobj250295*, nimcreateflowvar_250299)(void);
N_NIMCALL(void, fvfinalizer_250306)(Flowvarobj250295* fv);
N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj154247* fv);
N_NIMCALL(void, nimSpawn3)(Workerproc154255 fn, void* data);
N_NIMCALL(void, readinputwrapper_250351)(void* thread, void* args);
N_NIMCALL(void, nimArgsPassingDone)(void* p);
static N_INLINE(void, nimGCref)(void* p);
N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj154247* fv);
N_NIMCALL(NimStringDesc*, HEX5E_250356)(Flowvarobj250295* fv);
N_NIMCALL(NIM_BOOL, isready_154738)(Flowvarbaseobj154247* fv);
N_NIMCALL(FutureHEX3Aobjecttype195302*, send_211652)(Asyncsocketdesc209202* socket, NimStringDesc* data, NU8 flags);
N_NIMCALL(NimStringDesc*, createmessage_249113)(NimStringDesc* username, NimStringDesc* message);
N_NIMCALL(void, readinputwrapper_250442)(void* thread, void* args);
N_NIMCALL(void, poll_201920)(NI timeout);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuloadDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_lexbaseDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unicodeDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_jsonDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_protocolInit000)(void);
NIM_EXTERNC N_NOINLINE(void, HEX00_protocolDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, clientInit000)(void);
NIM_EXTERNC N_NOINLINE(void, clientDatInit000)(void);
STRING_LITERAL(TMP1200, "connect", 7);
STRING_LITERAL(TMP1201, "Connecting to ", 14);
STRING_LITERAL(TMP1202, "Connected!", 10);
STRING_LITERAL(TMP1203, " said ", 6);
STRING_LITERAL(TMP1206, "retFuture.finished Async procedure\'s (connect) return Future wa"
"s not finished.", 78);
STRING_LITERAL(TMP1208, "Chat application started", 24);
STRING_LITERAL(TMP1210, "Please specify the server address, e.g. ./client localhost user"
"name", 67);
extern NIM_THREADVAR TFrame* frameptr_27442;
TNimType NTI250210; /* object */
extern TNimType NTI208812; /* range -1..2(int) */
extern TNimType NTI149; /* string */
extern TNimType NTI209204; /* AsyncSocket */
extern TNimType NTI195301; /* Future */
extern TNimType NTI208102; /* iterator (): FutureBase{.closure, gcsafe, locks: <unknown>.} */
extern TNimType NTI202886; /* Future */
extern TNimType NTI249005; /* Message */
TNimType NTI250217; /* ref object */
extern NIM_THREADVAR Gcheap58018 gch_58059;
extern NIM_THREADVAR TSafePoint* exchandler_27443;
extern NIM_THREADVAR Exception* currexception_27445;
NimStringDesc* serveraddr_250244;
NimStringDesc* username_250248;
Asyncsocketdesc209202* socket_250252;
Flowvarobj250295* messageflowvar_250334;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_27442 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_27442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_27442;
	frameptr_27442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_30201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_27442 = (*frameptr_27442).prev;
}

N_NIMCALL(NimStringDesc*, readinput_250004)(void) {
	NimStringDesc* result;
	NimStringDesc* message;
	nimfr("readInput", "client.nim")
{	result = 0;
	nimln(9, "client.nim");
	message = readline_16916(stdin);
	nimln(10, "client.nim");
	result = copyString(message);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP1199)(void* p, NI op) {
	TY250210* a;
	a = (TY250210*)p;
	nimGCvisit((void*)(*a).serveraddr250021, op);
	nimGCvisit((void*)(*a).socket250020, op);
	nimGCvisit((void*)(*a).retfuture250014, op);
	nimGCvisit((void*)(*a).nameitervar250065.ClEnv, op);
	nimGCvisit((void*)(*a).future250016, op);
	nimGCvisit((void*)(*a).future250017, op);
	nimGCvisit((void*)(*a).line250059, op);
	nimGCvisit((void*)(*a).parsed250060.username, op);
	nimGCvisit((void*)(*a).parsed250060.message, op);
}

static N_INLINE(Cell55949*, usrtocell_59673)(void* usr) {
	Cell55949* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell55949*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell55949))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_61204)(Cell55949* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_59644((&gch_58059.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell55949* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_59673(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_61204(c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell55949* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_59673(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell55949* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_59673((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_61204(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_59694)(Cell55949* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_60423)(Cell55949* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_56665((&gch_58059.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_62022)(Cell55949* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_59694(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_60423(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_61604)(Cell55949* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_61204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_59694(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_60423(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell55949* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_59673(src);
		incref_62022(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell55949* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_59673((*dest));
		decref_61604(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_CLOSURE(FuturebaseHEX3Aobjecttype195018*, connectiter_250015)(void* ClEnv) {
	FuturebaseHEX3Aobjecttype195018* result;
	TY250210* HEX3Aenvp_250216;
	nimfr("connectIter", "asyncdispatch.nim")
{	result = 0;
	HEX3Aenvp_250216 = (TY250210*) ClEnv;
	switch ((*HEX3Aenvp_250216).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	case 2: goto STATE2;
	}
	STATE0: ;
	nimln(15, "client.nim");
	printf("%s%s\012", ((NimStringDesc*) &TMP1201)? (((NimStringDesc*) &TMP1201))->data:"nil", (*HEX3Aenvp_250216).serveraddr250021? ((*HEX3Aenvp_250216).serveraddr250021)->data:"nil");
	nimln(18, "client.nim");
	asgnRef((void**) (&(*HEX3Aenvp_250216).future250016), connect_209604((*HEX3Aenvp_250216).socket250020, (*HEX3Aenvp_250216).serveraddr250021, ((NU16) 7687)));
	(*HEX3Aenvp_250216).HEX3Astate = ((NI) 1);
	nimln(1324, "asyncdispatch.nim");
	result = &(*HEX3Aenvp_250216).future250016->Sup;
	goto BeforeRet;
	STATE1: ;
	nimln(18, "client.nim");
	read_209625((*HEX3Aenvp_250216).future250016);
	nimln(19, "client.nim");
	printf("%s\012", ((NimStringDesc*) &TMP1202)? (((NimStringDesc*) &TMP1202))->data:"nil");
	{
		nimln(20, "client.nim");
		while (1) {
			nimln(23, "client.nim");
			asgnRef((void**) (&(*HEX3Aenvp_250216).future250017), recvline_216048((*HEX3Aenvp_250216).socket250020, 2));
			(*HEX3Aenvp_250216).HEX3Astate = ((NI) 2);
			nimln(1324, "asyncdispatch.nim");
			result = &(*HEX3Aenvp_250216).future250017->Sup;
			goto BeforeRet;
			STATE2: ;
			nimln(23, "client.nim");
			asgnRefNoCycle((void**) (&(*HEX3Aenvp_250216).line250059), read_208112((*HEX3Aenvp_250216).future250017));
			nimln(26, "client.nim");
			parsemessage_249013((*HEX3Aenvp_250216).line250059, (&(*HEX3Aenvp_250216).parsed250060));
			nimln(28, "client.nim");
			printf("%s%s%s\012", (*HEX3Aenvp_250216).parsed250060.username? ((*HEX3Aenvp_250216).parsed250060.username)->data:"nil", ((NimStringDesc*) &TMP1203)? (((NimStringDesc*) &TMP1203))->data:"nil", (*HEX3Aenvp_250216).parsed250060.message? ((*HEX3Aenvp_250216).parsed250060.message)->data:"nil");
		}
	}
	complete_195295((*HEX3Aenvp_250216).retfuture250014);
	nimln(1512, "asyncdispatch.nim");
	(*HEX3Aenvp_250216).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_27443;
	exchandler_27443 = s;
}

static N_INLINE(NIM_BOOL, finished_208637)(TY208102 x) {
	NIM_BOOL result;
	nimfr("finished", "system.nim")
	result = 0;
	nimln(3071, "system.nim");
	      result = *((NI*) x.ClEnv) < 0;
      
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_27443 = (*exchandler_27443).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_27442 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2994, "system.nim");
	result = currexception_27445;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_27445), NIM_NIL);
}

N_CLOSURE(void, cb_250068)(void* ClEnv) {
	TY250210* HEX3Aenvp_250224;
	TSafePoint TMP1204;
	nimfr("cb", "asyncdispatch.nim")
	HEX3Aenvp_250224 = (TY250210*) ClEnv;
	nimln(1255, "asyncdispatch.nim");
	pushSafePoint(&TMP1204);
	TMP1204.status = setjmp(TMP1204.context);
	if (TMP1204.status == 0) {
		nimln(1256, "asyncdispatch.nim");
		{
			NIM_BOOL LOC4;
			FuturebaseHEX3Aobjecttype195018* next_250067;
			LOC4 = 0;
			LOC4 = finished_208637((*HEX3Aenvp_250224).nameitervar250065);
			if (!!(LOC4)) goto LA5;
			nimln(1257, "asyncdispatch.nim");
			next_250067 = (*HEX3Aenvp_250224).nameitervar250065.ClPrc((*HEX3Aenvp_250224).nameitervar250065.ClEnv);
			nimln(1258, "asyncdispatch.nim");
			{
				if (!(next_250067 == NIM_NIL)) goto LA9;
				nimln(1259, "asyncdispatch.nim");
				{
					if (!!((*(*HEX3Aenvp_250224).retfuture250014).Sup.finished)) goto LA13;
					failedassertimpl_99603(((NimStringDesc*) &TMP1206));
				}
				LA13: ;
			}
			goto LA7;
			LA9: ;
			{
				TY195019 LOC16;
				nimln(1262, "asyncdispatch.nim");
				memset((void*)(&LOC16), 0, sizeof(LOC16));
				LOC16.ClPrc = cb_250068; LOC16.ClEnv = HEX3Aenvp_250224;
				callbackHEX3D_195853(next_250067, LOC16);
			}
			LA7: ;
		}
		LA5: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TMP1204.status = 0;
			nimln(1264, "asyncdispatch.nim");
			{
				if (!(*(*HEX3Aenvp_250224).retfuture250014).Sup.finished) goto LA21;
				nimln(1267, "asyncdispatch.nim");
				reraiseException();
			}
			goto LA19;
			LA21: ;
			{
				Exception* LOC24;
				nimln(1269, "asyncdispatch.nim");
				LOC24 = 0;
				LOC24 = getCurrentException();
				fail_202633((*HEX3Aenvp_250224).retfuture250014, LOC24);
			}
			LA19: ;
			popCurrentException();
		}
	}
	if (TMP1204.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(FutureHEX3Aobjecttype195302*, connect_250018)(Asyncsocketdesc209202* socket, NimStringDesc* serveraddr) {
	FutureHEX3Aobjecttype195302* result;
	TY250210* HEX3Aenv_250227;
	NimStringDesc* LOC1;
	TY208102 LOC2;
	TY195019 LOC3;
	nimfr("connect", "client.nim")
{	result = 0;
	HEX3Aenv_250227 = 0;
	nimln(198, "system.nim");
	HEX3Aenv_250227 = (TY250210*) newObj((&NTI250217), sizeof(TY250210));
	nimln(13, "client.nim");
	LOC1 = 0;
	LOC1 = (*HEX3Aenv_250227).serveraddr250021; (*HEX3Aenv_250227).serveraddr250021 = copyStringRC1(serveraddr);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	asgnRefNoCycle((void**) (&(*HEX3Aenv_250227).socket250020), socket);
	nimln(12, "client.nim");
	asgnRef((void**) (&(*HEX3Aenv_250227).retfuture250014), newfuture_202573(((NimStringDesc*) &TMP1200)));
	nimln(1252, "asyncdispatch.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = connectiter_250015; LOC2.ClEnv = HEX3Aenv_250227;
	asgnRef((void**) (&(*HEX3Aenv_250227).nameitervar250065.ClEnv), LOC2.ClEnv);
	(*HEX3Aenv_250227).nameitervar250065.ClPrc = LOC2.ClPrc;
	nimln(1270, "asyncdispatch.nim");
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	LOC3.ClPrc = cb_250068; LOC3.ClEnv = HEX3Aenv_250227;
	LOC3.ClEnv? LOC3.ClPrc(LOC3.ClEnv):((TMP1207)(LOC3.ClPrc))();
	nimln(28, "client.nim");
	nimln(1494, "asyncdispatch.nim");
	result = (*HEX3Aenv_250227).retfuture250014;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, nimGCref)(void* p) {
	Cell55949* LOC1;
	nimfr("nimGCref", "gc.nim")
	nimln(235, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_59673(p);
	incref_62022(LOC1);
	popFrame();
}

N_NIMCALL(void, readinputwrapper_250351)(void* thread, void* args) {
	Flowvarobj250295* HEX3Atmp_250348;
	nimfr("readInputWrapper", "client.nim")
	nimln(47, "client.nim");
	HEX3Atmp_250348 = (*((TY250343*) (args))).fv250346;
	(*HEX3Atmp_250348).Sup.owner = thread;
	nimArgsPassingDone(thread);
	(*HEX3Atmp_250348).Sup.data = readinput_250004();
	nimGCref((*HEX3Atmp_250348).Sup.data);
	nimFlowVarSignal(HEX3Atmp_250348);
	popFrame();
}

N_NIMCALL(void, readinputwrapper_250442)(void* thread, void* args) {
	Flowvarobj250295* HEX3Atmp_250439;
	nimfr("readInputWrapper", "client.nim")
	nimln(58, "client.nim");
	HEX3Atmp_250439 = (*((TY250434*) (args))).fv250437;
	(*HEX3Atmp_250439).Sup.owner = thread;
	nimArgsPassingDone(thread);
	(*HEX3Atmp_250439).Sup.data = readinput_250004();
	nimGCref((*HEX3Atmp_250439).Sup.data);
	nimFlowVarSignal(HEX3Atmp_250439);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_linuxDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_cpuloadDatInit000();
	stdlib_locksDatInit000();
	stdlib_threadpoolDatInit000();
	stdlib_endiansDatInit000();
	stdlib_oidsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_netDatInit000();
	stdlib_epollDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	stdlib_streamsDatInit000();
	stdlib_lexbaseDatInit000();
	stdlib_unicodeDatInit000();
	stdlib_jsonDatInit000();
	HEX00_protocolDatInit000();
	clientDatInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_linuxInit000();
	stdlib_cpuinfoInit000();
	stdlib_cpuloadInit000();
	stdlib_locksInit000();
	stdlib_threadpoolInit000();
	stdlib_endiansInit000();
	stdlib_oidsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_nativesocketsInit000();
	stdlib_netInit000();
	stdlib_epollInit000();
	stdlib_selectorsInit000();
	stdlib_asyncdispatchInit000();
	stdlib_asyncnetInit000();
	stdlib_streamsInit000();
	stdlib_lexbaseInit000();
	stdlib_unicodeInit000();
	stdlib_jsonInit000();
	HEX00_protocolInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	clientInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, clientInit000)(void) {
	FutureHEX3Aobjecttype195302* LOC6;
	TY250343 scratch_250345;
	nimfr("client", "client.nim")
	nimln(30, "client.nim");
	printf("%s\012", ((NimStringDesc*) &TMP1208)? (((NimStringDesc*) &TMP1208))->data:"nil");
	nimln(32, "client.nim");
	{
		NI LOC3;
		LOC3 = 0;
		LOC3 = paramcount_144635();
		if (!(LOC3 < ((NI) 2))) goto LA4;
		nimln(35, "client.nim");
		quit_98791(((NimStringDesc*) &TMP1210), ((NI) 1));
	}
	LA4: ;
	nimln(38, "client.nim");
	asgnRefNoCycle((void**) (&serveraddr_250244), paramstr_144613(((NI) 1)));
	nimln(40, "client.nim");
	asgnRefNoCycle((void**) (&username_250248), paramstr_144613(((NI) 2)));
	nimln(42, "client.nim");
	asgnRefNoCycle((void**) (&socket_250252), newasyncsocket_209424(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE));
	nimln(45, "client.nim");
	LOC6 = 0;
	LOC6 = connect_250018(socket_250252, serveraddr_250244);
	asynccheck_250257(LOC6);
	nimln(47, "client.nim");
	memset((void*)(&scratch_250345), 0, sizeof(scratch_250345));
	scratch_250345.fv250346 = nimcreateflowvar_250299();
	nimFlowVarCreateSemaphore(scratch_250345.fv250346);
	nimSpawn3(readinputwrapper_250351, (&scratch_250345));
	asgnRef((void**) (&messageflowvar_250334), scratch_250345.fv250346);
	{
		nimln(48, "client.nim");
		while (1) {
			nimln(50, "client.nim");
			{
				Flowvarbaseobj154247* LOC11;
				NIM_BOOL LOC12;
				NimStringDesc* LOC15;
				NimStringDesc* LOC16;
				FutureHEX3Aobjecttype195302* LOC17;
				TY250434 scratch_250436;
				LOC11 = 0;
				LOC11 = &messageflowvar_250334->Sup;
				LOC12 = 0;
				LOC12 = isready_154738(LOC11);
				if (!LOC12) goto LA13;
				nimln(55, "client.nim");
				LOC15 = 0;
				LOC15 = HEX5E_250356(messageflowvar_250334);
				LOC16 = 0;
				LOC16 = createmessage_249113(username_250248, LOC15);
				LOC17 = 0;
				LOC17 = send_211652(socket_250252, LOC16, 2);
				asynccheck_250257(LOC17);
				nimln(58, "client.nim");
				memset((void*)(&scratch_250436), 0, sizeof(scratch_250436));
				scratch_250436.fv250437 = nimcreateflowvar_250299();
				nimFlowVarCreateSemaphore(scratch_250436.fv250437);
				nimSpawn3(readinputwrapper_250442, (&scratch_250436));
				asgnRef((void**) (&messageflowvar_250334), scratch_250436.fv250437);
			}
			LA13: ;
			nimln(62, "client.nim");
			poll_201920(((NI) 500));
		}
	}
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, clientDatInit000)(void) {
static TNimNode* TMP1197[9];
static TNimNode TMP141[10];
NTI250210.size = sizeof(TY250210);
NTI250210.kind = 18;
NTI250210.base = 0;
TMP1197[0] = &TMP141[1];
TMP141[1].kind = 1;
TMP141[1].offset = offsetof(TY250210, HEX3Astate);
TMP141[1].typ = (&NTI208812);
TMP141[1].name = ":state";
TMP1197[1] = &TMP141[2];
TMP141[2].kind = 1;
TMP141[2].offset = offsetof(TY250210, serveraddr250021);
TMP141[2].typ = (&NTI149);
TMP141[2].name = "serverAddr250021";
TMP1197[2] = &TMP141[3];
TMP141[3].kind = 1;
TMP141[3].offset = offsetof(TY250210, socket250020);
TMP141[3].typ = (&NTI209204);
TMP141[3].name = "socket250020";
TMP1197[3] = &TMP141[4];
TMP141[4].kind = 1;
TMP141[4].offset = offsetof(TY250210, retfuture250014);
TMP141[4].typ = (&NTI195301);
TMP141[4].name = "retFuture250014";
TMP1197[4] = &TMP141[5];
TMP141[5].kind = 1;
TMP141[5].offset = offsetof(TY250210, nameitervar250065);
TMP141[5].typ = (&NTI208102);
TMP141[5].name = "nameIterVar250065";
TMP1197[5] = &TMP141[6];
TMP141[6].kind = 1;
TMP141[6].offset = offsetof(TY250210, future250016);
TMP141[6].typ = (&NTI195301);
TMP141[6].name = "future250016";
TMP1197[6] = &TMP141[7];
TMP141[7].kind = 1;
TMP141[7].offset = offsetof(TY250210, future250017);
TMP141[7].typ = (&NTI202886);
TMP141[7].name = "future250017";
TMP1197[7] = &TMP141[8];
TMP141[8].kind = 1;
TMP141[8].offset = offsetof(TY250210, line250059);
TMP141[8].typ = (&NTI149);
TMP141[8].name = "line250059";
TMP1197[8] = &TMP141[9];
TMP141[9].kind = 1;
TMP141[9].offset = offsetof(TY250210, parsed250060);
TMP141[9].typ = (&NTI249005);
TMP141[9].name = "parsed250060";
TMP141[0].len = 9; TMP141[0].kind = 2; TMP141[0].sons = &TMP1197[0];
NTI250210.node = &TMP141[0];
NTI250217.size = sizeof(TY250210*);
NTI250217.kind = 22;
NTI250217.base = (&NTI250210);
NTI250217.marker = TMP1199;
}

