/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/renzhen/Nim12.0/lib -o src/nimcache/server.o src/nimcache/server.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#include <setjmp.h>
#include <sys/socket.h>
typedef struct ServerHEX3Aobjecttype199014 ServerHEX3Aobjecttype199014;
typedef struct Asyncsocketdesc190202 Asyncsocketdesc190202;
typedef struct TY199016 TY199016;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct ClientHEX3Aobjecttype199008 ClientHEX3Aobjecttype199008;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Cell49347 Cell49347;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellset49359 Cellset49359;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct FutureHEX3Aobjecttype176302 FutureHEX3Aobjecttype176302;
typedef struct TY199410 TY199410;
typedef struct FuturebaseHEX3Aobjecttype176018 FuturebaseHEX3Aobjecttype176018;
typedef struct FutureHEX3Aobjecttype183887 FutureHEX3Aobjecttype183887;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TSafePoint TSafePoint;
typedef struct TY199610 TY199610;
typedef struct FutureHEX3Aobjecttype193248 FutureHEX3Aobjecttype193248;
typedef struct TY193241 TY193241;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  ServerHEX3Aobjecttype199014  {
Asyncsocketdesc190202* socket;
TY199016* clients;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  ClientHEX3Aobjecttype199008  {
Asyncsocketdesc190202* socket;
NimStringDesc* netaddr;
NI id;
NIM_BOOL connected;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
typedef struct {
N_NIMCALL_PTR(FuturebaseHEX3Aobjecttype176018*, ClPrc) (void* ClEnv);
void* ClEnv;
} TY189102;
struct  TY199410  {
NI HEX3Astate;
ClientHEX3Aobjecttype199008* client199065;
FutureHEX3Aobjecttype176302* retfuture199058;
ServerHEX3Aobjecttype199014* server199064;
TY189102 nameitervar199230;
FutureHEX3Aobjecttype183887* future199060;
NimStringDesc* line199089;
ClientHEX3Aobjecttype199008* c199211;
TY199016* HEX3Atmp199223;
NI i199226;
NI L199228;
FutureHEX3Aobjecttype176302* future199061;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19211;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19211 raiseAction;
};
typedef N_CLOSURE_PTR(FuturebaseHEX3Aobjecttype176018*, TMP892) (void);
typedef struct {
N_NIMCALL_PTR(void, ClPrc) (void* ClEnv);
void* ClEnv;
} TY176019;
struct  FuturebaseHEX3Aobjecttype176018  {
  TNimObject Sup;
TY176019 cb;
NIM_BOOL finished;
Exception* error;
NimStringDesc* errorstacktrace;
NimStringDesc* stacktrace;
NI id;
NimStringDesc* fromproc;
};
struct  FutureHEX3Aobjecttype176302  {
  FuturebaseHEX3Aobjecttype176018 Sup;
};
typedef N_CLOSURE_PTR(void, TMP894) (void);
struct  TY199610  {
NI HEX3Astate;
ServerHEX3Aobjecttype199014* server199444;
NI port199446;
FutureHEX3Aobjecttype176302* retfuture199439;
TY189102 nameitervar199529;
NimStringDesc* netaddr199476;
Asyncsocketdesc190202* clientsocket199477;
FutureHEX3Aobjecttype193248* future199441;
ClientHEX3Aobjecttype199008* client199488;
};
struct TY193241 {
NimStringDesc* Field0;
Asyncsocketdesc190202* Field1;
};
typedef N_CLOSURE_PTR(FuturebaseHEX3Aobjecttype176018*, TMP904) (void);
typedef N_CLOSURE_PTR(void, TMP906) (void);
typedef NIM_CHAR TY190209[4001];
struct  Asyncsocketdesc190202  {
int fd;
NIM_BOOL closed;
NIM_BOOL isbuffered;
union{
struct {TY190209 buffer;
NI currpos;
NI buflen;
} S1;
} isbufferedU;
NIM_BOOL isssl;
NU8 domain;
NU8 socktype;
NU8 protocol;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  FutureHEX3Aobjecttype183887  {
  FuturebaseHEX3Aobjecttype176018 Sup;
NimStringDesc* value;
};
struct  FutureHEX3Aobjecttype193248  {
  FuturebaseHEX3Aobjecttype176018 Sup;
TY193241 value;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct TY199016 {
  TGenericSeq Sup;
  ClientHEX3Aobjecttype199008* data[SEQ_DECL_SIZE];
};
N_NIMCALL(ServerHEX3Aobjecttype199014*, newserver_199022)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP878)(void* p, NI op);
N_NIMCALL(void, TMP879)(void* p, NI op);
N_NIMCALL(void, TMP880)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(Asyncsocketdesc190202*, newasyncsocket_190424)(NU8 domain, NU8 socktype, NU8 protocol, NIM_BOOL buffered);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void*, newSeqRC1)(TNimType* typ, NI len);
N_NIMCALL(NimStringDesc*, HEX24_199048)(ClientHEX3Aobjecttype199008* client);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(FutureHEX3Aobjecttype176302*, processmessages_199062)(ServerHEX3Aobjecttype199014* server, ClientHEX3Aobjecttype199008* client);
N_NIMCALL(void, TMP884)(void* p, NI op);
N_NIMCALL(FutureHEX3Aobjecttype176302*, newfuture_183573)(NimStringDesc* fromproc);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49347* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c);
N_NOINLINE(void, incl_50065)(Cellset49359* s, Cell49347* cell);
static N_INLINE(void, decref_55004)(Cell49347* c);
N_CLOSURE(FuturebaseHEX3Aobjecttype176018*, processmessagesiter_199059)(void* ClEnv);
N_NIMCALL(FutureHEX3Aobjecttype183887*, recvline_197048)(Asyncsocketdesc190202* socket, NU8 flags);
N_NIMCALL(NimStringDesc*, read_189112)(FutureHEX3Aobjecttype183887* future);
N_NIMCALL(void, close_197463)(Asyncsocketdesc190202* socket);
N_NIMCALL(void, complete_176295)(FutureHEX3Aobjecttype176302* future);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(FutureHEX3Aobjecttype176302*, send_192652)(Asyncsocketdesc190202* socket, NimStringDesc* data, NU8 flags);
N_NIMCALL(void, read_190625)(FutureHEX3Aobjecttype176302* future);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_CLOSURE(void, cb_199233)(void* ClEnv);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(NIM_BOOL, finished_189637)(TY189102 x);
N_NIMCALL(void, callbackHEX3D_176853)(FuturebaseHEX3Aobjecttype176018* future, TY176019 cb);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(void, fail_183633)(FutureHEX3Aobjecttype176302* future, Exception* error);
static N_INLINE(Exception*, getCurrentException)(void);
static N_INLINE(void, popCurrentException)(void);
N_NIMCALL(void, asynccheck_199500)(FutureHEX3Aobjecttype176302* future);
N_NIMCALL(FutureHEX3Aobjecttype176302*, loop_199442)(ServerHEX3Aobjecttype199014* server, NI port);
N_NIMCALL(void, TMP898)(void* p, NI op);
N_CLOSURE(FuturebaseHEX3Aobjecttype176018*, loopiter_199440)(void* ClEnv);
N_NIMCALL(void, bindaddr_197445)(Asyncsocketdesc190202* socket, NU16 port, NimStringDesc* address);
N_NIMCALL(void, listen_197435)(Asyncsocketdesc190202* socket, int backlog);
N_NIMCALL(FutureHEX3Aobjecttype193248*, acceptaddr_193234)(Asyncsocketdesc190202* socket, NU8 flags);
N_NIMCALL(void, read_195031)(FutureHEX3Aobjecttype193248* future, TY193241* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
N_CLOSURE(void, cb_199532)(void* ClEnv);
N_NIMCALL(void, waitfor_199641)(FutureHEX3Aobjecttype176302* fut);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* thestackbottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_etcprivDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_unsignedDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_netDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncdispatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_asyncnetDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, serverInit000)(void);
NIM_EXTERNC N_NOINLINE(void, serverDatInit000)(void);
STRING_LITERAL(TMP881, "(", 1);
STRING_LITERAL(TMP882, ")", 1);
STRING_LITERAL(TMP885, "processMessages", 15);
STRING_LITERAL(TMP886, " disconnected!", 14);
STRING_LITERAL(TMP887, " sent: ", 7);
STRING_LITERAL(TMP888, "\015\012", 2);
STRING_LITERAL(TMP890, "len(a) == L seq modified while iterating over it", 48);
STRING_LITERAL(TMP893, "retFuture.finished Async procedure\'s (processMessages) return F"
"uture was not finished.", 86);
STRING_LITERAL(TMP899, "loop", 4);
STRING_LITERAL(TMP900, "", 0);
STRING_LITERAL(TMP901, "Listening on localhost:", 23);
STRING_LITERAL(TMP902, "Accepted connection from ", 25);
STRING_LITERAL(TMP905, "retFuture.finished Async procedure\'s (loop) return Future was n"
"ot finished.", 75);
STRING_LITERAL(TMP907, "Server initialised!", 19);
TNimType NTI199014; /* Server:ObjectType */
extern TNimType NTI190204; /* AsyncSocket */
TNimType NTI199008; /* Client:ObjectType */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
extern TNimType NTI138; /* bool */
TNimType NTI199005; /* Client */
TNimType NTI199016; /* seq[Client] */
TNimType NTI199007; /* Server */
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
TNimType NTI199410; /* object */
extern TNimType NTI189812; /* range -1..2(int) */
extern TNimType NTI176301; /* Future */
extern TNimType NTI189102; /* iterator (): FutureBase{.closure, gcsafe, locks: <unknown>.} */
extern TNimType NTI183886; /* Future */
TNimType NTI199417; /* ref object */
extern TSafePoint* exchandler_20843;
extern Exception* currexception_20845;
TNimType NTI199610; /* object */
extern TNimType NTI191412; /* range -1..1(int) */
extern TNimType NTI193247; /* Future */
TNimType NTI199617; /* ref object */
ServerHEX3Aobjecttype199014* server_199637;
N_NIMCALL(void, TMP878)(void* p, NI op) {
	ClientHEX3Aobjecttype199008* a;
	a = (ClientHEX3Aobjecttype199008*)p;
	nimGCvisit((void*)(*a).socket, op);
	nimGCvisit((void*)(*a).netaddr, op);
}
N_NIMCALL(void, TMP879)(void* p, NI op) {
	TY199016* a;
	NI LOC1;
	a = (TY199016*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1], op);
	}
}
N_NIMCALL(void, TMP880)(void* p, NI op) {
	ServerHEX3Aobjecttype199014* a;
	a = (ServerHEX3Aobjecttype199014*)p;
	nimGCvisit((void*)(*a).socket, op);
	nimGCvisit((void*)(*a).clients, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell49347* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_53046(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_54604(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(ServerHEX3Aobjecttype199014*, newserver_199022)(void) {
	ServerHEX3Aobjecttype199014* result;
	ServerHEX3Aobjecttype199014* LOC1;
	nimfr("newServer", "server.nim")
	result = 0;
	nimln(15, "server.nim");
	LOC1 = 0;
	LOC1 = (ServerHEX3Aobjecttype199014*) newObj((&NTI199007), sizeof(ServerHEX3Aobjecttype199014));
	nimln(16, "server.nim");
	asgnRefNoCycle((void**) (&(*LOC1).socket), newasyncsocket_190424(((NU8) 2), ((NU8) 1), ((NU8) 6), NIM_TRUE));
	if ((*LOC1).clients) nimGCunrefNoCycle((*LOC1).clients);
	(*LOC1).clients = (TY199016*) newSeqRC1((&NTI199016), 0);
	result = LOC1;
	popFrame();
	return result;
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

N_NIMCALL(NimStringDesc*, HEX24_199048)(ClientHEX3Aobjecttype199008* client) {
	NimStringDesc* result;
	NimStringDesc* LOC1;
	NimStringDesc* LOC2;
	nimfr("$", "server.nim")
	result = 0;
	nimln(19, "server.nim");
	nimln(20, "server.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = nimIntToStr((*client).id);
	LOC1 = rawNewString(LOC2->Sup.len + (*client).netaddr->Sup.len + 2);
appendString(LOC1, LOC2);
appendString(LOC1, ((NimStringDesc*) &TMP881));
appendString(LOC1, (*client).netaddr);
appendString(LOC1, ((NimStringDesc*) &TMP882));
	result = LOC1;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP884)(void* p, NI op) {
	TY199410* a;
	a = (TY199410*)p;
	nimGCvisit((void*)(*a).client199065, op);
	nimGCvisit((void*)(*a).retfuture199058, op);
	nimGCvisit((void*)(*a).server199064, op);
	nimGCvisit((void*)(*a).nameitervar199230.ClEnv, op);
	nimGCvisit((void*)(*a).future199060, op);
	nimGCvisit((void*)(*a).line199089, op);
	nimGCvisit((void*)(*a).c199211, op);
	nimGCvisit((void*)(*a).HEX3Atmp199223, op);
	nimGCvisit((void*)(*a).future199061, op);
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49347* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49347* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49347* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49347* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_CLOSURE(FuturebaseHEX3Aobjecttype176018*, processmessagesiter_199059)(void* ClEnv) {
	FuturebaseHEX3Aobjecttype176018* result;
	TY199410* HEX3Aenvp_199416;
	nimfr("processMessagesIter", "asyncdispatch.nim")
{	result = 0;
	HEX3Aenvp_199416 = (TY199410*) ClEnv;
	switch ((*HEX3Aenvp_199416).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	case 2: goto STATE2;
	}
	STATE0: ;
	{
		nimln(25, "server.nim");
		while (1) {
			NimStringDesc* LOC8;
			nimln(28, "server.nim");
			asgnRef((void**) (&(*HEX3Aenvp_199416).future199060), recvline_197048((*(*HEX3Aenvp_199416).client199065).socket, 2));
			(*HEX3Aenvp_199416).HEX3Astate = ((NI) 1);
			nimln(1324, "asyncdispatch.nim");
			result = &(*HEX3Aenvp_199416).future199060->Sup;
			goto BeforeRet;
			STATE1: ;
			nimln(28, "server.nim");
			asgnRefNoCycle((void**) (&(*HEX3Aenvp_199416).line199089), read_189112((*HEX3Aenvp_199416).future199060));
			nimln(32, "server.nim");
			{
				NimStringDesc* LOC7;
				if (!(((*HEX3Aenvp_199416).line199089 ? (*HEX3Aenvp_199416).line199089->Sup.len : 0) == ((NI) 0))) goto LA5;
				nimln(33, "server.nim");
				LOC7 = 0;
				LOC7 = HEX24_199048((*HEX3Aenvp_199416).client199065);
				printf("%s%s\012", LOC7? (LOC7)->data:"nil", ((NimStringDesc*) &TMP886)? (((NimStringDesc*) &TMP886))->data:"nil");
				nimln(34, "server.nim");
				(*(*HEX3Aenvp_199416).client199065).connected = NIM_FALSE;
				nimln(36, "server.nim");
				close_197463((*(*HEX3Aenvp_199416).client199065).socket);
				nimln(1167, "os.nim");
				complete_176295((*HEX3Aenvp_199416).retfuture199058);
				nimln(37, "server.nim");
				(*HEX3Aenvp_199416).HEX3Astate = ((NI) -1);
				nimln(1167, "os.nim");
				result = NIM_NIL;
				goto BeforeRet;
			}
			LA5: ;
			nimln(40, "server.nim");
			LOC8 = 0;
			LOC8 = HEX24_199048((*HEX3Aenvp_199416).client199065);
			printf("%s%s%s\012", LOC8? (LOC8)->data:"nil", ((NimStringDesc*) &TMP887)? (((NimStringDesc*) &TMP887))->data:"nil", (*HEX3Aenvp_199416).line199089? ((*HEX3Aenvp_199416).line199089)->data:"nil");
			{
				nimln(43, "server.nim");
				asgnRefNoCycle((void**) (&(*HEX3Aenvp_199416).HEX3Atmp199223), (*(*HEX3Aenvp_199416).server199064).clients);
				nimln(3365, "system.nim");
				(*HEX3Aenvp_199416).i199226 = ((NI) 0);
				nimln(3366, "system.nim");
				(*HEX3Aenvp_199416).L199228 = ((*HEX3Aenvp_199416).HEX3Atmp199223 ? (*HEX3Aenvp_199416).HEX3Atmp199223->Sup.len : 0);
				{
					nimln(3367, "system.nim");
					while (1) {
						NI TMP889;
						if (!((*HEX3Aenvp_199416).i199226 < (*HEX3Aenvp_199416).L199228)) goto LA11;
						nimln(3368, "system.nim");
						if ((NU)((*HEX3Aenvp_199416).i199226) >= (NU)((*HEX3Aenvp_199416).HEX3Atmp199223->Sup.len)) raiseIndexError();
						asgnRefNoCycle((void**) (&(*HEX3Aenvp_199416).c199211), (*HEX3Aenvp_199416).HEX3Atmp199223->data[(*HEX3Aenvp_199416).i199226]);
						nimln(46, "server.nim");
						{
							NIM_BOOL LOC14;
							NimStringDesc* LOC18;
							LOC14 = 0;
							nimln(349, "system.nim");
							LOC14 = !(((*(*HEX3Aenvp_199416).c199211).id == (*(*HEX3Aenvp_199416).client199065).id));
							if (!(LOC14)) goto LA15;
							LOC14 = (*(*HEX3Aenvp_199416).c199211).connected;
							LA15: ;
							if (!LOC14) goto LA16;
							nimln(47, "server.nim");
							LOC18 = 0;
							LOC18 = rawNewString((*HEX3Aenvp_199416).line199089->Sup.len + 2);
appendString(LOC18, (*HEX3Aenvp_199416).line199089);
appendString(LOC18, ((NimStringDesc*) &TMP888));
							asgnRef((void**) (&(*HEX3Aenvp_199416).future199061), send_192652((*(*HEX3Aenvp_199416).c199211).socket, LOC18, 2));
							(*HEX3Aenvp_199416).HEX3Astate = ((NI) 2);
							nimln(1324, "asyncdispatch.nim");
							result = &(*HEX3Aenvp_199416).future199061->Sup;
							goto BeforeRet;
							STATE2: ;
							nimln(47, "server.nim");
							read_190625((*HEX3Aenvp_199416).future199061);
						}
						LA16: ;
						nimln(3369, "system.nim");
						TMP889 = addInt((*HEX3Aenvp_199416).i199226, ((NI) 1));
						(*HEX3Aenvp_199416).i199226 = (NI)(TMP889);
						nimln(3370, "system.nim");
						{
							if (!!((((*HEX3Aenvp_199416).HEX3Atmp199223 ? (*HEX3Aenvp_199416).HEX3Atmp199223->Sup.len : 0) == (*HEX3Aenvp_199416).L199228))) goto LA21;
							failedassertimpl_91603(((NimStringDesc*) &TMP890));
						}
						LA21: ;
					} LA11: ;
				}
			}
		}
	}
	nimln(47, "server.nim");
	complete_176295((*HEX3Aenvp_199416).retfuture199058);
	nimln(1512, "asyncdispatch.nim");
	(*HEX3Aenvp_199416).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_20843;
	exchandler_20843 = s;
}

static N_INLINE(NIM_BOOL, finished_189637)(TY189102 x) {
	NIM_BOOL result;
	nimfr("finished", "system.nim")
	result = 0;
	nimln(3071, "system.nim");
	      result = *((NI*) x.ClEnv) < 0;
      
	popFrame();
	return result;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_20843 = (*exchandler_20843).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_20842 = s;
}

static N_INLINE(Exception*, getCurrentException)(void) {
	Exception* result;
	nimfr("getCurrentException", "system.nim")
	result = 0;
	nimln(2994, "system.nim");
	result = currexception_20845;
	popFrame();
	return result;
}

static N_INLINE(void, popCurrentException)(void) {
	asgnRef((void**) (&currexception_20845), NIM_NIL);
}

N_CLOSURE(void, cb_199233)(void* ClEnv) {
	TY199410* HEX3Aenvp_199424;
	TSafePoint TMP891;
	nimfr("cb", "asyncdispatch.nim")
	HEX3Aenvp_199424 = (TY199410*) ClEnv;
	nimln(1255, "asyncdispatch.nim");
	pushSafePoint(&TMP891);
	TMP891.status = setjmp(TMP891.context);
	if (TMP891.status == 0) {
		nimln(1256, "asyncdispatch.nim");
		{
			NIM_BOOL LOC4;
			FuturebaseHEX3Aobjecttype176018* next_199232;
			LOC4 = 0;
			LOC4 = finished_189637((*HEX3Aenvp_199424).nameitervar199230);
			if (!!(LOC4)) goto LA5;
			nimln(1257, "asyncdispatch.nim");
			next_199232 = (*HEX3Aenvp_199424).nameitervar199230.ClPrc((*HEX3Aenvp_199424).nameitervar199230.ClEnv);
			nimln(1258, "asyncdispatch.nim");
			{
				if (!(next_199232 == NIM_NIL)) goto LA9;
				nimln(1259, "asyncdispatch.nim");
				{
					if (!!((*(*HEX3Aenvp_199424).retfuture199058).Sup.finished)) goto LA13;
					failedassertimpl_91603(((NimStringDesc*) &TMP893));
				}
				LA13: ;
			}
			goto LA7;
			LA9: ;
			{
				TY176019 LOC16;
				nimln(1262, "asyncdispatch.nim");
				memset((void*)(&LOC16), 0, sizeof(LOC16));
				LOC16.ClPrc = cb_199233; LOC16.ClEnv = HEX3Aenvp_199424;
				callbackHEX3D_176853(next_199232, LOC16);
			}
			LA7: ;
		}
		LA5: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TMP891.status = 0;
			nimln(1264, "asyncdispatch.nim");
			{
				if (!(*(*HEX3Aenvp_199424).retfuture199058).Sup.finished) goto LA21;
				nimln(1267, "asyncdispatch.nim");
				reraiseException();
			}
			goto LA19;
			LA21: ;
			{
				Exception* LOC24;
				nimln(1269, "asyncdispatch.nim");
				LOC24 = 0;
				LOC24 = getCurrentException();
				fail_183633((*HEX3Aenvp_199424).retfuture199058, LOC24);
			}
			LA19: ;
			popCurrentException();
		}
	}
	if (TMP891.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(FutureHEX3Aobjecttype176302*, processmessages_199062)(ServerHEX3Aobjecttype199014* server, ClientHEX3Aobjecttype199008* client) {
	FutureHEX3Aobjecttype176302* result;
	TY199410* HEX3Aenv_199427;
	TY189102 LOC1;
	TY176019 LOC2;
	nimfr("processMessages", "server.nim")
{	result = 0;
	HEX3Aenv_199427 = 0;
	nimln(198, "system.nim");
	HEX3Aenv_199427 = (TY199410*) newObj((&NTI199417), sizeof(TY199410));
	nimln(23, "server.nim");
	asgnRefNoCycle((void**) (&(*HEX3Aenv_199427).client199065), client);
	asgnRefNoCycle((void**) (&(*HEX3Aenv_199427).server199064), server);
	nimln(22, "server.nim");
	asgnRef((void**) (&(*HEX3Aenv_199427).retfuture199058), newfuture_183573(((NimStringDesc*) &TMP885)));
	nimln(1252, "asyncdispatch.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = processmessagesiter_199059; LOC1.ClEnv = HEX3Aenv_199427;
	asgnRef((void**) (&(*HEX3Aenv_199427).nameitervar199230.ClEnv), LOC1.ClEnv);
	(*HEX3Aenv_199427).nameitervar199230.ClPrc = LOC1.ClPrc;
	nimln(1270, "asyncdispatch.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = cb_199233; LOC2.ClEnv = HEX3Aenv_199427;
	LOC2.ClEnv? LOC2.ClPrc(LOC2.ClEnv):((TMP894)(LOC2.ClPrc))();
	nimln(47, "server.nim");
	nimln(1494, "asyncdispatch.nim");
	result = (*HEX3Aenv_199427).retfuture199058;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP898)(void* p, NI op) {
	TY199610* a;
	a = (TY199610*)p;
	nimGCvisit((void*)(*a).server199444, op);
	nimGCvisit((void*)(*a).retfuture199439, op);
	nimGCvisit((void*)(*a).nameitervar199529.ClEnv, op);
	nimGCvisit((void*)(*a).netaddr199476, op);
	nimGCvisit((void*)(*a).clientsocket199477, op);
	nimGCvisit((void*)(*a).future199441, op);
	nimGCvisit((void*)(*a).client199488, op);
}

N_CLOSURE(FuturebaseHEX3Aobjecttype176018*, loopiter_199440)(void* ClEnv) {
	FuturebaseHEX3Aobjecttype176018* result;
	TY199610* HEX3Aenvp_199616;
	NimStringDesc* LOC1;
	nimfr("loopIter", "asyncdispatch.nim")
{	result = 0;
	HEX3Aenvp_199616 = (TY199610*) ClEnv;
	switch ((*HEX3Aenvp_199616).HEX3Astate) {
	case -1: goto BeforeRet;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	nimln(53, "server.nim");
	bindaddr_197445((*(*HEX3Aenvp_199616).server199444).socket, ((NU16) ((*HEX3Aenvp_199616).port199446)), ((NimStringDesc*) &TMP900));
	nimln(55, "server.nim");
	listen_197435((*(*HEX3Aenvp_199616).server199444).socket, SOMAXCONN);
	nimln(56, "server.nim");
	LOC1 = 0;
	LOC1 = nimIntToStr((*HEX3Aenvp_199616).port199446);
	printf("%s%s\012", ((NimStringDesc*) &TMP901)? (((NimStringDesc*) &TMP901))->data:"nil", LOC1? (LOC1)->data:"nil");
	{
		nimln(58, "server.nim");
		while (1) {
			TY193241 HEX3Atmp_199636;
			NimStringDesc* LOC4;
			ClientHEX3Aobjecttype199008* LOC5;
			NimStringDesc* LOC6;
			FutureHEX3Aobjecttype176302* LOC7;
			memset((void*)(&HEX3Atmp_199636), 0, sizeof(HEX3Atmp_199636));
			nimln(60, "server.nim");
			asgnRef((void**) (&(*HEX3Aenvp_199616).future199441), acceptaddr_193234((*(*HEX3Aenvp_199616).server199444).socket, 2));
			(*HEX3Aenvp_199616).HEX3Astate = ((NI) 1);
			nimln(1324, "asyncdispatch.nim");
			result = &(*HEX3Aenvp_199616).future199441->Sup;
			goto BeforeRet;
			STATE1: ;
			nimln(60, "server.nim");
			chckNil((void*)(&HEX3Atmp_199636));
			memset((void*)(&HEX3Atmp_199636), 0, sizeof(HEX3Atmp_199636));
			read_195031((*HEX3Aenvp_199616).future199441, (&HEX3Atmp_199636));
			LOC4 = 0;
			LOC4 = (*HEX3Aenvp_199616).netaddr199476; (*HEX3Aenvp_199616).netaddr199476 = copyStringRC1(HEX3Atmp_199636.Field0);
			if (LOC4) nimGCunrefNoCycle(LOC4);
			asgnRefNoCycle((void**) (&(*HEX3Aenvp_199616).clientsocket199477), HEX3Atmp_199636.Field1);
			nimln(61, "server.nim");
			printf("%s%s\012", ((NimStringDesc*) &TMP902)? (((NimStringDesc*) &TMP902))->data:"nil", (*HEX3Aenvp_199616).netaddr199476? ((*HEX3Aenvp_199616).netaddr199476)->data:"nil");
			nimln(64, "server.nim");
			LOC5 = 0;
			LOC5 = (ClientHEX3Aobjecttype199008*) newObj((&NTI199005), sizeof(ClientHEX3Aobjecttype199008));
			asgnRefNoCycle((void**) (&(*LOC5).socket), (*HEX3Aenvp_199616).clientsocket199477);
			LOC6 = 0;
			LOC6 = (*LOC5).netaddr; (*LOC5).netaddr = copyStringRC1((*HEX3Aenvp_199616).netaddr199476);
			if (LOC6) nimGCunrefNoCycle(LOC6);
			nimln(67, "server.nim");
			(*LOC5).id = ((*(*HEX3Aenvp_199616).server199444).clients ? (*(*HEX3Aenvp_199616).server199444).clients->Sup.len : 0);
			(*LOC5).connected = NIM_TRUE;
			asgnRefNoCycle((void**) (&(*HEX3Aenvp_199616).client199488), LOC5);
			nimln(71, "server.nim");
			(*(*HEX3Aenvp_199616).server199444).clients = (TY199016*) incrSeqV2(&((*(*HEX3Aenvp_199616).server199444).clients)->Sup, sizeof(ClientHEX3Aobjecttype199008*));
			asgnRefNoCycle((void**) (&(*(*HEX3Aenvp_199616).server199444).clients->data[(*(*HEX3Aenvp_199616).server199444).clients->Sup.len]), (*HEX3Aenvp_199616).client199488);
			++(*(*HEX3Aenvp_199616).server199444).clients->Sup.len;
			nimln(74, "server.nim");
			LOC7 = 0;
			LOC7 = processmessages_199062((*HEX3Aenvp_199616).server199444, (*HEX3Aenvp_199616).client199488);
			asynccheck_199500(LOC7);
		}
	}
	complete_176295((*HEX3Aenvp_199616).retfuture199439);
	nimln(1512, "asyncdispatch.nim");
	(*HEX3Aenvp_199616).HEX3Astate = ((NI) -1);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_CLOSURE(void, cb_199532)(void* ClEnv) {
	TY199610* HEX3Aenvp_199624;
	TSafePoint TMP903;
	nimfr("cb", "asyncdispatch.nim")
	HEX3Aenvp_199624 = (TY199610*) ClEnv;
	nimln(1255, "asyncdispatch.nim");
	pushSafePoint(&TMP903);
	TMP903.status = setjmp(TMP903.context);
	if (TMP903.status == 0) {
		nimln(1256, "asyncdispatch.nim");
		{
			NIM_BOOL LOC4;
			FuturebaseHEX3Aobjecttype176018* next_199531;
			LOC4 = 0;
			LOC4 = finished_189637((*HEX3Aenvp_199624).nameitervar199529);
			if (!!(LOC4)) goto LA5;
			nimln(1257, "asyncdispatch.nim");
			next_199531 = (*HEX3Aenvp_199624).nameitervar199529.ClPrc((*HEX3Aenvp_199624).nameitervar199529.ClEnv);
			nimln(1258, "asyncdispatch.nim");
			{
				if (!(next_199531 == NIM_NIL)) goto LA9;
				nimln(1259, "asyncdispatch.nim");
				{
					if (!!((*(*HEX3Aenvp_199624).retfuture199439).Sup.finished)) goto LA13;
					failedassertimpl_91603(((NimStringDesc*) &TMP905));
				}
				LA13: ;
			}
			goto LA7;
			LA9: ;
			{
				TY176019 LOC16;
				nimln(1262, "asyncdispatch.nim");
				memset((void*)(&LOC16), 0, sizeof(LOC16));
				LOC16.ClPrc = cb_199532; LOC16.ClEnv = HEX3Aenvp_199624;
				callbackHEX3D_176853(next_199531, LOC16);
			}
			LA7: ;
		}
		LA5: ;
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
		{
			TMP903.status = 0;
			nimln(1264, "asyncdispatch.nim");
			{
				if (!(*(*HEX3Aenvp_199624).retfuture199439).Sup.finished) goto LA21;
				nimln(1267, "asyncdispatch.nim");
				reraiseException();
			}
			goto LA19;
			LA21: ;
			{
				Exception* LOC24;
				nimln(1269, "asyncdispatch.nim");
				LOC24 = 0;
				LOC24 = getCurrentException();
				fail_183633((*HEX3Aenvp_199624).retfuture199439, LOC24);
			}
			LA19: ;
			popCurrentException();
		}
	}
	if (TMP903.status != 0) reraiseException();
	popFrame();
}

N_NIMCALL(FutureHEX3Aobjecttype176302*, loop_199442)(ServerHEX3Aobjecttype199014* server, NI port) {
	FutureHEX3Aobjecttype176302* result;
	TY199610* HEX3Aenv_199627;
	TY189102 LOC1;
	TY176019 LOC2;
	nimfr("loop", "server.nim")
{	result = 0;
	HEX3Aenv_199627 = 0;
	nimln(198, "system.nim");
	HEX3Aenv_199627 = (TY199610*) newObj((&NTI199617), sizeof(TY199610));
	nimln(50, "server.nim");
	asgnRefNoCycle((void**) (&(*HEX3Aenv_199627).server199444), server);
	(*HEX3Aenv_199627).port199446 = port;
	nimln(49, "server.nim");
	asgnRef((void**) (&(*HEX3Aenv_199627).retfuture199439), newfuture_183573(((NimStringDesc*) &TMP899)));
	nimln(1252, "asyncdispatch.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	LOC1.ClPrc = loopiter_199440; LOC1.ClEnv = HEX3Aenv_199627;
	asgnRef((void**) (&(*HEX3Aenv_199627).nameitervar199529.ClEnv), LOC1.ClEnv);
	(*HEX3Aenv_199627).nameitervar199529.ClPrc = LOC1.ClPrc;
	nimln(1270, "asyncdispatch.nim");
	memset((void*)(&LOC2), 0, sizeof(LOC2));
	LOC2.ClPrc = cb_199532; LOC2.ClEnv = HEX3Aenv_199627;
	LOC2.ClEnv? LOC2.ClPrc(LOC2.ClEnv):((TMP906)(LOC2.ClPrc))();
	nimln(74, "server.nim");
	nimln(1494, "asyncdispatch.nim");
	result = (*HEX3Aenv_199627).retfuture199439;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner() {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_osDatInit000();
	stdlib_endiansDatInit000();
	stdlib_oidsDatInit000();
	stdlib_etcprivDatInit000();
	stdlib_hashesDatInit000();
	stdlib_mathDatInit000();
	stdlib_tablesDatInit000();
	stdlib_macrosDatInit000();
	stdlib_unsignedDatInit000();
	stdlib_nativesocketsDatInit000();
	stdlib_netDatInit000();
	stdlib_epollDatInit000();
	stdlib_selectorsDatInit000();
	stdlib_asyncdispatchDatInit000();
	stdlib_asyncnetDatInit000();
	serverDatInit000();
	stdlib_parseutilsInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_osInit000();
	stdlib_endiansInit000();
	stdlib_oidsInit000();
	stdlib_etcprivInit000();
	stdlib_hashesInit000();
	stdlib_mathInit000();
	stdlib_tablesInit000();
	stdlib_macrosInit000();
	stdlib_unsignedInit000();
	stdlib_nativesocketsInit000();
	stdlib_netInit000();
	stdlib_epollInit000();
	stdlib_selectorsInit000();
	stdlib_asyncdispatchInit000();
	stdlib_asyncnetInit000();
}

void PreMain() {
	void (*volatile inner)();
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	serverInit000();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)();
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, serverInit000)(void) {
	FutureHEX3Aobjecttype176302* LOC1;
	nimfr("server", "server.nim")
	nimln(80, "server.nim");
	asgnRefNoCycle((void**) (&server_199637), newserver_199022());
	nimln(81, "server.nim");
	printf("%s\012", ((NimStringDesc*) &TMP907)? (((NimStringDesc*) &TMP907))->data:"nil");
	nimln(84, "server.nim");
	LOC1 = 0;
	LOC1 = loop_199442(server_199637, ((NI) 7687));
	waitfor_199641(LOC1);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, serverDatInit000)(void) {
static TNimNode* TMP876[2];
static TNimNode* TMP877[4];
static TNimNode* TMP883[12];
static TNimNode* TMP897[9];
static TNimNode TMP138[31];
NTI199014.size = sizeof(ServerHEX3Aobjecttype199014);
NTI199014.kind = 18;
NTI199014.base = 0;
NTI199014.flags = 2;
TMP876[0] = &TMP138[1];
TMP138[1].kind = 1;
TMP138[1].offset = offsetof(ServerHEX3Aobjecttype199014, socket);
TMP138[1].typ = (&NTI190204);
TMP138[1].name = "socket";
TMP876[1] = &TMP138[2];
NTI199008.size = sizeof(ClientHEX3Aobjecttype199008);
NTI199008.kind = 18;
NTI199008.base = 0;
NTI199008.flags = 2;
TMP877[0] = &TMP138[4];
TMP138[4].kind = 1;
TMP138[4].offset = offsetof(ClientHEX3Aobjecttype199008, socket);
TMP138[4].typ = (&NTI190204);
TMP138[4].name = "socket";
TMP877[1] = &TMP138[5];
TMP138[5].kind = 1;
TMP138[5].offset = offsetof(ClientHEX3Aobjecttype199008, netaddr);
TMP138[5].typ = (&NTI149);
TMP138[5].name = "netAddr";
TMP877[2] = &TMP138[6];
TMP138[6].kind = 1;
TMP138[6].offset = offsetof(ClientHEX3Aobjecttype199008, id);
TMP138[6].typ = (&NTI108);
TMP138[6].name = "id";
TMP877[3] = &TMP138[7];
TMP138[7].kind = 1;
TMP138[7].offset = offsetof(ClientHEX3Aobjecttype199008, connected);
TMP138[7].typ = (&NTI138);
TMP138[7].name = "connected";
TMP138[3].len = 4; TMP138[3].kind = 2; TMP138[3].sons = &TMP877[0];
NTI199008.node = &TMP138[3];
NTI199005.size = sizeof(ClientHEX3Aobjecttype199008*);
NTI199005.kind = 22;
NTI199005.base = (&NTI199008);
NTI199005.flags = 2;
NTI199005.marker = TMP878;
NTI199016.size = sizeof(TY199016*);
NTI199016.kind = 24;
NTI199016.base = (&NTI199005);
NTI199016.flags = 2;
NTI199016.marker = TMP879;
TMP138[2].kind = 1;
TMP138[2].offset = offsetof(ServerHEX3Aobjecttype199014, clients);
TMP138[2].typ = (&NTI199016);
TMP138[2].name = "clients";
TMP138[0].len = 2; TMP138[0].kind = 2; TMP138[0].sons = &TMP876[0];
NTI199014.node = &TMP138[0];
NTI199007.size = sizeof(ServerHEX3Aobjecttype199014*);
NTI199007.kind = 22;
NTI199007.base = (&NTI199014);
NTI199007.flags = 2;
NTI199007.marker = TMP880;
NTI199410.size = sizeof(TY199410);
NTI199410.kind = 18;
NTI199410.base = 0;
TMP883[0] = &TMP138[9];
TMP138[9].kind = 1;
TMP138[9].offset = offsetof(TY199410, HEX3Astate);
TMP138[9].typ = (&NTI189812);
TMP138[9].name = ":state";
TMP883[1] = &TMP138[10];
TMP138[10].kind = 1;
TMP138[10].offset = offsetof(TY199410, client199065);
TMP138[10].typ = (&NTI199005);
TMP138[10].name = "client199065";
TMP883[2] = &TMP138[11];
TMP138[11].kind = 1;
TMP138[11].offset = offsetof(TY199410, retfuture199058);
TMP138[11].typ = (&NTI176301);
TMP138[11].name = "retFuture199058";
TMP883[3] = &TMP138[12];
TMP138[12].kind = 1;
TMP138[12].offset = offsetof(TY199410, server199064);
TMP138[12].typ = (&NTI199007);
TMP138[12].name = "server199064";
TMP883[4] = &TMP138[13];
TMP138[13].kind = 1;
TMP138[13].offset = offsetof(TY199410, nameitervar199230);
TMP138[13].typ = (&NTI189102);
TMP138[13].name = "nameIterVar199230";
TMP883[5] = &TMP138[14];
TMP138[14].kind = 1;
TMP138[14].offset = offsetof(TY199410, future199060);
TMP138[14].typ = (&NTI183886);
TMP138[14].name = "future199060";
TMP883[6] = &TMP138[15];
TMP138[15].kind = 1;
TMP138[15].offset = offsetof(TY199410, line199089);
TMP138[15].typ = (&NTI149);
TMP138[15].name = "line199089";
TMP883[7] = &TMP138[16];
TMP138[16].kind = 1;
TMP138[16].offset = offsetof(TY199410, c199211);
TMP138[16].typ = (&NTI199005);
TMP138[16].name = "c199211";
TMP883[8] = &TMP138[17];
TMP138[17].kind = 1;
TMP138[17].offset = offsetof(TY199410, HEX3Atmp199223);
TMP138[17].typ = (&NTI199016);
TMP138[17].name = ":tmp199223";
TMP883[9] = &TMP138[18];
TMP138[18].kind = 1;
TMP138[18].offset = offsetof(TY199410, i199226);
TMP138[18].typ = (&NTI108);
TMP138[18].name = "i199226";
TMP883[10] = &TMP138[19];
TMP138[19].kind = 1;
TMP138[19].offset = offsetof(TY199410, L199228);
TMP138[19].typ = (&NTI108);
TMP138[19].name = "L199228";
TMP883[11] = &TMP138[20];
TMP138[20].kind = 1;
TMP138[20].offset = offsetof(TY199410, future199061);
TMP138[20].typ = (&NTI176301);
TMP138[20].name = "future199061";
TMP138[8].len = 12; TMP138[8].kind = 2; TMP138[8].sons = &TMP883[0];
NTI199410.node = &TMP138[8];
NTI199417.size = sizeof(TY199410*);
NTI199417.kind = 22;
NTI199417.base = (&NTI199410);
NTI199417.marker = TMP884;
NTI199610.size = sizeof(TY199610);
NTI199610.kind = 18;
NTI199610.base = 0;
TMP897[0] = &TMP138[22];
TMP138[22].kind = 1;
TMP138[22].offset = offsetof(TY199610, HEX3Astate);
TMP138[22].typ = (&NTI191412);
TMP138[22].name = ":state";
TMP897[1] = &TMP138[23];
TMP138[23].kind = 1;
TMP138[23].offset = offsetof(TY199610, server199444);
TMP138[23].typ = (&NTI199007);
TMP138[23].name = "server199444";
TMP897[2] = &TMP138[24];
TMP138[24].kind = 1;
TMP138[24].offset = offsetof(TY199610, port199446);
TMP138[24].typ = (&NTI108);
TMP138[24].name = "port199446";
TMP897[3] = &TMP138[25];
TMP138[25].kind = 1;
TMP138[25].offset = offsetof(TY199610, retfuture199439);
TMP138[25].typ = (&NTI176301);
TMP138[25].name = "retFuture199439";
TMP897[4] = &TMP138[26];
TMP138[26].kind = 1;
TMP138[26].offset = offsetof(TY199610, nameitervar199529);
TMP138[26].typ = (&NTI189102);
TMP138[26].name = "nameIterVar199529";
TMP897[5] = &TMP138[27];
TMP138[27].kind = 1;
TMP138[27].offset = offsetof(TY199610, netaddr199476);
TMP138[27].typ = (&NTI149);
TMP138[27].name = "netAddr199476";
TMP897[6] = &TMP138[28];
TMP138[28].kind = 1;
TMP138[28].offset = offsetof(TY199610, clientsocket199477);
TMP138[28].typ = (&NTI190204);
TMP138[28].name = "clientSocket199477";
TMP897[7] = &TMP138[29];
TMP138[29].kind = 1;
TMP138[29].offset = offsetof(TY199610, future199441);
TMP138[29].typ = (&NTI193247);
TMP138[29].name = "future199441";
TMP897[8] = &TMP138[30];
TMP138[30].kind = 1;
TMP138[30].offset = offsetof(TY199610, client199488);
TMP138[30].typ = (&NTI199005);
TMP138[30].name = "client199488";
TMP138[21].len = 9; TMP138[21].kind = 2; TMP138[21].sons = &TMP897[0];
NTI199610.node = &TMP138[21];
NTI199617.size = sizeof(TY199610*);
NTI199617.kind = 22;
NTI199617.base = (&NTI199610);
NTI199617.marker = TMP898;
}

