/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_selectors.o src/nimcache/stdlib_selectors.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/epoll.h>
#include <string.h>
#include <errno.h>
#include <unistd.h>
typedef struct Table178466 Table178466;
typedef struct Selectorkey178439 Selectorkey178439;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Keyvaluepairseq178469 Keyvaluepairseq178469;
typedef struct Keyvaluepair178472 Keyvaluepair178472;
typedef struct Selector178456 Selector178456;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TY179655 TY179655;
typedef struct Readyinfo178441 Readyinfo178441;
typedef struct Cell49347 Cell49347;
typedef struct Cellset49359 Cellset49359;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  Selectorkey178439  {
int fd;
NU8 events;
TNimObject* data;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Table178466  {
Keyvaluepairseq178469* data;
NI counter;
};
struct Keyvaluepair178472 {
NI Field0;
int Field1;
Selectorkey178439 Field2;
};
typedef struct epoll_event TY178459[64];
struct  Selector178456  {
int epollfd;
TY178459 events;
Table178466 fds;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Readyinfo178441 {
Selectorkey178439 Field0;
NU8 Field1;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct TY179655 {
  TGenericSeq Sup;
  Readyinfo178441 data[SEQ_DECL_SIZE];
};
struct Keyvaluepairseq178469 {
  TGenericSeq Sup;
  Keyvaluepair178472 data[SEQ_DECL_SIZE];
};
static N_INLINE(NI, hash_178409)(int x);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(void, HEX5BHEX5DHEX3D_178571)(Table178466* t, int key, Selectorkey178439 val);
static N_INLINE(NI, rawget_178585)(Table178466 t, int key, NI* hc);
static N_INLINE(NIM_BOOL, isfilled_151281)(NI hcode);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, nexttry_151404)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, enlarge_178620)(Table178466* t);
static N_INLINE(NI, rawgetknownhc_178674)(Table178466 t, int key, NI hc);
N_NIMCALL(void, rawinsert_178699)(Table178466* t, Keyvaluepairseq178469** data, int key, Selectorkey178439 val, NI hc, NI h);
N_NIMCALL(Selectorkey178439*, HEX5BHEX5D_178804)(Table178466* t, int key);
N_NIMCALL(Selectorkey178439*, mget_179058)(Table178466* t, int key);
N_NIMCALL(void, del_179325)(Table178466* t, int key);
N_NIMCALL(void, HEX5BHEX5D_179417)(Table178466 t, int key, Selectorkey178439* Result);
N_NIMCALL(void, inittable_180202)(NI initialsize, Table178466* Result);
N_NIMCALL(NIM_BOOL, haskey_180423)(Table178466 t, int key);
N_NIMCALL(struct epoll_event, createeventstruct_178485)(NU8 events, int fd);
N_NIMCALL(void, register_178533)(Selector178456* s, int fd, NU8 events, TNimObject* data);
N_NOINLINE(void, raiseoserror_127009)(NI32 errorcode, NimStringDesc* additionalinfo);
N_NIMCALL(NI32, oslasterror_127034)(void);
N_NIMCALL(void, update_178796)(Selector178456* s, int fd, NU8 events);
N_NIMCALL(void, unregister_179293)(Selector178456* s, int fd);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, close_179389)(Selector178456* s);
N_NIMCALL(NIM_BOOL, epollhasfd_179411)(Selector178456* s, int fd);
N_NIMCALL(TY179655*, select_179650)(Selector178456* s, NI timeout);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP689)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemsize);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49347* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c);
N_NOINLINE(void, incl_50065)(Cellset49359* s, Cell49347* cell);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, decref_55004)(Cell49347* c);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, newselector_180034)(Selector178456* Result);
N_NIMCALL(NIM_BOOL, contains_180417)(Selector178456* s, int fd);
N_NIMCALL(void, HEX5BHEX5D_180479)(Selector178456* s, int fd, Selectorkey178439* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_180813)(Selectorkey178439 x, Selectorkey178439 y);
N_NIMCALL(NIM_BOOL, contains_180604)(Selector178456* s, Selectorkey178439 key);
STRING_LITERAL(TMP687, "", 0);
STRING_LITERAL(TMP690, "\012  not (selectorKey.fd == SocketHandle(0)) ", 43);
extern TFrame* frameptr_20842;
TNimType NTI178439; /* SelectorKey */
extern TNimType NTI8211; /* cint */
TNimType NTI178437; /* Event */
TNimType NTI178446; /* set[Event] */
extern TNimType NTI4013; /* SelectorData */
TNimType NTI178441; /* ReadyInfo */
TNimType NTI179655; /* seq[ReadyInfo] */
extern Gcheap51418 gch_51459;
TNimType NTI178456; /* Selector */
extern TNimType NTI177290; /* epoll_event */
TNimType NTI178459; /* array[0..63, epoll_event] */
extern TNimType NTI178466; /* Table */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(NI, hash_178409)(int x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(121, "hashes.nim");
	result = ((NI) (x));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_151281)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "tableimpl.nim")
	result = 0;
	nimln(18, "tableimpl.nim");
	nimln(349, "system.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_151404)(NI h, NI maxhash) {
	NI result;
	NI TMP679;
	nimfr("nextTry", "tableimpl.nim")
	result = 0;
	nimln(28, "tableimpl.nim");
	TMP679 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP679) & maxhash);
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rawget_178585)(Table178466 t, int key, NI* hc) {
	NI result;
	NI h;
	NI TMP680;
	nimfr("rawGet", "tableimpl.nim")
{	result = 0;
	nimln(43, "tableimpl.nim");
	(*hc) = hash_178409(key);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_151281(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field1 == key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_151404(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP680 = subInt(((NI) -1), h);
	result = (NI)(TMP680);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawgetknownhc_178674)(Table178466 t, int key, NI hc) {
	NI result;
	NI h;
	NI TMP681;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result = 0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_151281(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field1 == key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_151404(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP681 = subInt(((NI) -1), h);
	result = (NI)(TMP681);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(struct epoll_event, createeventstruct_178485)(NU8 events, int fd) {
	struct epoll_event result;
	nimfr("createEventStruct", "selectors.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(95, "selectors.nim");
	{
		nimln(1098, "system.nim");
		if (!((events &(1<<((((NU8) 0))&7)))!=0)) goto LA3;
		nimln(96, "selectors.nim");
		result.events = ((NU32) 1);
	}
	LA3: ;
	nimln(97, "selectors.nim");
	{
		nimln(1098, "system.nim");
		if (!((events &(1<<((((NU8) 1))&7)))!=0)) goto LA7;
		nimln(98, "selectors.nim");
		result.events = (NU32)(result.events | ((NI) 4));
	}
	LA7: ;
	nimln(99, "selectors.nim");
	result.events = (NU32)(result.events | ((NI) 8192));
	nimln(100, "selectors.nim");
	result.data.fd = fd;
	popFrame();
	return result;
}

N_NIMCALL(void, register_178533)(Selector178456* s, int fd, NU8 events, TNimObject* data) {
	struct epoll_event event;
	Selectorkey178439 LOC11;
	nimfr("register", "selectors.nim")
	nimln(104, "selectors.nim");
	event = createeventstruct_178485(events, fd);
	nimln(105, "selectors.nim");
	{
		nimln(349, "system.nim");
		if (!!((events == 0))) goto LA3;
		nimln(106, "selectors.nim");
		{
			int LOC7;
			NI32 LOC10;
			nimln(349, "system.nim");
			nimln(106, "selectors.nim");
			LOC7 = 0;
			LOC7 = epoll_ctl((*s).epollfd, ((int) 1), fd, (&event));
			if (!!((LOC7 == ((NI32) 0)))) goto LA8;
			nimln(107, "selectors.nim");
			LOC10 = 0;
			LOC10 = oslasterror_127034();
			raiseoserror_127009(LOC10, ((NimStringDesc*) &TMP687));
		}
		LA8: ;
	}
	LA3: ;
	nimln(109, "selectors.nim");
	memset((void*)(&LOC11), 0, sizeof(LOC11));
	memset((void*)(&LOC11), 0, sizeof(LOC11));
	LOC11.fd = fd;
	LOC11.events = events;
	LOC11.data = data;
	HEX5BHEX5DHEX3D_178571((&(*s).fds), fd, LOC11);
	popFrame();
}

N_NIMCALL(void, update_178796)(Selector178456* s, int fd, NU8 events) {
	nimfr("update", "selectors.nim")
	nimln(112, "selectors.nim");
	{
		Selectorkey178439* LOC3;
		nimln(349, "system.nim");
		nimln(112, "selectors.nim");
		LOC3 = 0;
		LOC3 = HEX5BHEX5D_178804((&(*s).fds), fd);
		if (!!(((*LOC3).events == events))) goto LA4;
		nimln(113, "selectors.nim");
		{
			Selectorkey178439* LOC16;
			if (!(events == 0)) goto LA8;
			nimln(119, "selectors.nim");
			{
				int LOC12;
				NI32 LOC15;
				nimln(349, "system.nim");
				nimln(119, "selectors.nim");
				LOC12 = 0;
				LOC12 = epoll_ctl((*s).epollfd, ((int) 2), fd, NIM_NIL);
				if (!!((LOC12 == ((NI32) 0)))) goto LA13;
				nimln(120, "selectors.nim");
				LOC15 = 0;
				LOC15 = oslasterror_127034();
				raiseoserror_127009(LOC15, ((NimStringDesc*) &TMP687));
			}
			LA13: ;
			nimln(121, "selectors.nim");
			LOC16 = 0;
			LOC16 = mget_179058((&(*s).fds), fd);
			(*LOC16).events = events;
		}
		goto LA6;
		LA8: ;
		{
			struct epoll_event event;
			Selectorkey178439* LOC36;
			nimln(123, "selectors.nim");
			event = createeventstruct_178485(events, fd);
			nimln(124, "selectors.nim");
			{
				Selectorkey178439* LOC20;
				LOC20 = 0;
				LOC20 = HEX5BHEX5D_178804((&(*s).fds), fd);
				if (!((*LOC20).events == 0)) goto LA21;
				nimln(127, "selectors.nim");
				{
					int LOC25;
					NI32 LOC28;
					nimln(349, "system.nim");
					nimln(127, "selectors.nim");
					LOC25 = 0;
					LOC25 = epoll_ctl((*s).epollfd, ((int) 1), fd, (&event));
					if (!!((LOC25 == ((NI32) 0)))) goto LA26;
					nimln(128, "selectors.nim");
					LOC28 = 0;
					LOC28 = oslasterror_127034();
					raiseoserror_127009(LOC28, ((NimStringDesc*) &TMP687));
				}
				LA26: ;
			}
			goto LA18;
			LA21: ;
			{
				nimln(130, "selectors.nim");
				{
					int LOC32;
					NI32 LOC35;
					nimln(349, "system.nim");
					nimln(130, "selectors.nim");
					LOC32 = 0;
					LOC32 = epoll_ctl((*s).epollfd, ((int) 3), fd, (&event));
					if (!!((LOC32 == ((NI32) 0)))) goto LA33;
					nimln(131, "selectors.nim");
					LOC35 = 0;
					LOC35 = oslasterror_127034();
					raiseoserror_127009(LOC35, ((NimStringDesc*) &TMP687));
				}
				LA33: ;
			}
			LA18: ;
			nimln(132, "selectors.nim");
			LOC36 = 0;
			LOC36 = mget_179058((&(*s).fds), fd);
			(*LOC36).events = events;
		}
		LA6: ;
	}
	LA4: ;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, unregister_179293)(Selector178456* s, int fd) {
	nimfr("unregister", "selectors.nim")
	nimln(135, "selectors.nim");
	{
		int LOC3;
		NI32 err;
		nimln(349, "system.nim");
		nimln(135, "selectors.nim");
		LOC3 = 0;
		LOC3 = epoll_ctl((*s).epollfd, ((int) 2), fd, NIM_NIL);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		nimln(136, "selectors.nim");
		err = oslasterror_127034();
		nimln(137, "selectors.nim");
		{
			nimln(1104, "system.nim");
			if (!!((err == ((NI)chckRange(ENOENT, ((NI) 0), ((NI) 65535))) || err == ((NI)chckRange(EBADF, ((NI) 0), ((NI) 65535)))))) goto LA8;
			nimln(139, "selectors.nim");
			raiseoserror_127009(err, ((NimStringDesc*) &TMP687));
		}
		LA8: ;
	}
	LA4: ;
	nimln(140, "selectors.nim");
	del_179325((&(*s).fds), fd);
	popFrame();
}

N_NIMCALL(void, close_179389)(Selector178456* s) {
	nimfr("close", "selectors.nim")
	nimln(144, "selectors.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(349, "system.nim");
		nimln(144, "selectors.nim");
		LOC3 = 0;
		LOC3 = close((*s).epollfd);
		if (!!((LOC3 == ((NI32) 0)))) goto LA4;
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP687));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, epollhasfd_179411)(Selector178456* s, int fd) {
	NIM_BOOL result;
	struct epoll_event event;
	Selectorkey178439 LOC1;
	nimfr("epollHasFd", "selectors.nim")
{	result = 0;
	nimln(147, "selectors.nim");
	result = NIM_TRUE;
	nimln(148, "selectors.nim");
	memset((void*)(&LOC1), 0, sizeof(LOC1));
	HEX5BHEX5D_179417((*s).fds, fd, (&LOC1));
	event = createeventstruct_178485(LOC1.events, fd);
	nimln(149, "selectors.nim");
	{
		int LOC4;
		NI32 err;
		nimln(349, "system.nim");
		nimln(149, "selectors.nim");
		LOC4 = 0;
		LOC4 = epoll_ctl((*s).epollfd, ((int) 3), fd, (&event));
		if (!!((LOC4 == ((NI32) 0)))) goto LA5;
		nimln(150, "selectors.nim");
		err = oslasterror_127034();
		nimln(151, "selectors.nim");
		{
			nimln(1098, "system.nim");
			if (!(err == ((NI)chckRange(ENOENT, ((NI) 0), ((NI) 65535))) || err == ((NI)chckRange(EBADF, ((NI) 0), ((NI) 65535))))) goto LA9;
			nimln(152, "selectors.nim");
			result = NIM_FALSE;
			goto BeforeRet;
		}
		LA9: ;
		nimln(153, "selectors.nim");
		raiseoserror_127009(err, ((NimStringDesc*) &TMP687));
	}
	LA5: ;
	}BeforeRet: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP689)(void* p, NI op) {
	TY179655* a;
	NI LOC1;
	a = (TY179655*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field0.data, op);
	}
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49347* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49347* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49347* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49347* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(TY179655*, select_179650)(Selector178456* s, NI timeout) {
	TY179655* result;
	int evnum;
	nimfr("select", "selectors.nim")
{	result = 0;
	nimln(156, "selectors.nim");
	result = (TY179655*) newSeq((&NTI179655), 0);
	nimln(157, "selectors.nim");
	evnum = epoll_wait((*s).epollfd, (&(*s).events[(((NI) 0))- 0]), ((int) 64), ((int)chckRange(timeout, ((int) (-2147483647 -1)), ((int) 2147483647))));
	nimln(158, "selectors.nim");
	{
		NI32 err;
		if (!(evnum < ((NI32) 0))) goto LA3;
		nimln(159, "selectors.nim");
		err = oslasterror_127034();
		nimln(160, "selectors.nim");
		{
			if (!(err == EINTR)) goto LA7;
			nimln(161, "selectors.nim");
			result = (TY179655*) newSeq((&NTI179655), 0);
			goto BeforeRet;
		}
		LA7: ;
		nimln(162, "selectors.nim");
		raiseoserror_127009(err, ((NimStringDesc*) &TMP687));
	}
	LA3: ;
	nimln(163, "selectors.nim");
	{
		if (!(evnum == ((NI32) 0))) goto LA11;
		result = (TY179655*) newSeq((&NTI179655), 0);
		goto BeforeRet;
	}
	LA11: ;
	{
		int i_179823;
		int HEX3Atmp_180016;
		NI res_180019;
		i_179823 = 0;
		HEX3Atmp_180016 = 0;
		nimln(164, "selectors.nim");
		HEX3Atmp_180016 = subInt(evnum, 1);
		nimln(1874, "system.nim");
		res_180019 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				int fd;
				NU8 evset;
				Selectorkey178439 selectorkey;
				Selectorkey178439* LOC30;
				Readyinfo178441 LOC35;
				NI TMP691;
				if (!(res_180019 <= ((NI) (HEX3Atmp_180016)))) goto LA15;
				nimln(1876, "system.nim");
				i_179823 = ((int)chckRange(res_180019, ((int) (-2147483647 -1)), ((int) 2147483647)));
				nimln(165, "selectors.nim");
				if ((NU)(i_179823) > (NU)(63)) raiseIndexError();
				fd = (*s).events[(i_179823)- 0].data.fd;
				nimln(167, "selectors.nim");
				evset = 0;
				nimln(168, "selectors.nim");
				{
					NIM_BOOL LOC18;
					LOC18 = 0;
					nimln(349, "system.nim");
					nimln(168, "selectors.nim");
					if ((NU)(i_179823) > (NU)(63)) raiseIndexError();
					LOC18 = !(((NU32)((*s).events[(i_179823)- 0].events & ((NI) 8)) == ((NI) 0)));
					if (LOC18) goto LA19;
					nimln(349, "system.nim");
					nimln(168, "selectors.nim");
					if ((NU)(i_179823) > (NU)(63)) raiseIndexError();
					LOC18 = !(((NU32)((*s).events[(i_179823)- 0].events & ((NI) 16)) == ((NI) 0)));
					LA19: ;
					if (!LOC18) goto LA20;
					evset = (evset | 4);
				}
				LA20: ;
				nimln(169, "selectors.nim");
				{
					nimln(349, "system.nim");
					nimln(169, "selectors.nim");
					if ((NU)(i_179823) > (NU)(63)) raiseIndexError();
					if (!!((((NI) ((NU32)((*s).events[(i_179823)- 0].events & ((NI) 1)))) == ((NI) 0)))) goto LA24;
					evset = (evset | 1);
				}
				LA24: ;
				nimln(170, "selectors.nim");
				{
					nimln(349, "system.nim");
					nimln(170, "selectors.nim");
					if ((NU)(i_179823) > (NU)(63)) raiseIndexError();
					if (!!(((NU32)((*s).events[(i_179823)- 0].events & ((NI) 4)) == ((NI) 0)))) goto LA28;
					evset = (evset | 2);
				}
				LA28: ;
				memset((void*)(&selectorkey), 0, sizeof(selectorkey));
				nimln(171, "selectors.nim");
				LOC30 = 0;
				LOC30 = HEX5BHEX5D_178804((&(*s).fds), fd);
				selectorkey.fd = (*LOC30).fd;
				selectorkey.events = (*LOC30).events;
				selectorkey.data = (*LOC30).data;
				nimln(172, "selectors.nim");
				{
					if (!!(!((selectorkey.fd == ((int) 0))))) goto LA33;
					failedassertimpl_91603(((NimStringDesc*) &TMP690));
				}
				LA33: ;
				nimln(173, "selectors.nim");
				memset((void*)(&LOC35), 0, sizeof(LOC35));
				LOC35.Field0.fd = selectorkey.fd;
				LOC35.Field0.events = selectorkey.events;
				LOC35.Field0.data = selectorkey.data;
				LOC35.Field1 = evset;
				result = (TY179655*) incrSeqV2(&(result)->Sup, sizeof(Readyinfo178441));
				result->data[result->Sup.len].Field0.fd = LOC35.Field0.fd;
				result->data[result->Sup.len].Field0.events = LOC35.Field0.events;
				asgnRef((void**) (&result->data[result->Sup.len].Field0.data), LOC35.Field0.data);
				result->data[result->Sup.len].Field1 = LOC35.Field1;
				++result->Sup.len;
				nimln(1895, "system.nim");
				TMP691 = addInt(res_180019, ((NI) 1));
				res_180019 = (NI)(TMP691);
			} LA15: ;
		}
	}
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, newselector_180034)(Selector178456* Result) {
	nimfr("newSelector", "selectors.nim")
	nimln(178, "selectors.nim");
	(*Result).epollfd = epoll_create(((int) 64));
	nimln(179, "selectors.nim");
	{
		NI32 LOC5;
		if (!((*Result).epollfd < ((NI32) 0))) goto LA3;
		nimln(180, "selectors.nim");
		LOC5 = 0;
		LOC5 = oslasterror_127034();
		raiseoserror_127009(LOC5, ((NimStringDesc*) &TMP687));
	}
	LA3: ;
	nimln(184, "selectors.nim");
	inittable_180202(((NI) 64), (&(*Result).fds));
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_180417)(Selector178456* s, int fd) {
	NIM_BOOL result;
	nimfr("contains", "selectors.nim")
{	result = 0;
	nimln(188, "selectors.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = haskey_180423((*s).fds, fd);
		if (!LOC3) goto LA4;
		nimln(190, "selectors.nim");
		{
			Selectorkey178439 LOC8;
			nimln(349, "system.nim");
			nimln(190, "selectors.nim");
			memset((void*)(&LOC8), 0, sizeof(LOC8));
			HEX5BHEX5D_179417((*s).fds, fd, (&LOC8));
			if (!!((LOC8.events == 0))) goto LA9;
			nimln(191, "selectors.nim");
			result = epollhasfd_179411(s, fd);
		}
		goto LA6;
		LA9: ;
		{
			nimln(193, "selectors.nim");
			result = NIM_TRUE;
		}
		LA6: ;
	}
	goto LA1;
	LA4: ;
	{
		nimln(195, "selectors.nim");
		result = NIM_FALSE;
		goto BeforeRet;
	}
	LA1: ;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, HEX5BHEX5D_180479)(Selector178456* s, int fd, Selectorkey178439* Result) {
	nimfr("[]", "selectors.nim")
{	nimln(199, "selectors.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI178439));
	HEX5BHEX5D_179417((*s).fds, fd, Result);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, contains_180604)(Selector178456* s, Selectorkey178439 key) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	Selectorkey178439 LOC3;
	nimfr("contains", "selectors.nim")
{	result = 0;
	nimln(375, "selectors.nim");
	LOC1 = 0;
	nimln(1098, "system.nim");
	LOC1 = contains_180417(s, key.fd);
	if (!(LOC1)) goto LA2;
	nimln(375, "selectors.nim");
	memset((void*)(&LOC3), 0, sizeof(LOC3));
	HEX5BHEX5D_179417((*s).fds, key.fd, (&LOC3));
	LOC1 = HEX3DHEX3D_180813(LOC3, key);
	LA2: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsInit000)(void) {
	nimfr("selectors", "selectors.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_selectorsDatInit000)(void) {
static TNimNode* TMP668[3];
static TNimNode* TMP669[3];
NI TMP671;
static char* NIM_CONST TMP670[3] = {
"EvRead", 
"EvWrite", 
"EvError"};
static TNimNode* TMP688[2];
static TNimNode* TMP708[3];
static TNimNode TMP661[16];
NTI178439.size = sizeof(Selectorkey178439);
NTI178439.kind = 18;
NTI178439.base = 0;
TMP668[0] = &TMP661[1];
TMP661[1].kind = 1;
TMP661[1].offset = offsetof(Selectorkey178439, fd);
TMP661[1].typ = (&NTI8211);
TMP661[1].name = "fd";
TMP668[1] = &TMP661[2];
NTI178437.size = sizeof(NU8);
NTI178437.kind = 14;
NTI178437.base = 0;
NTI178437.flags = 3;
for (TMP671 = 0; TMP671 < 3; TMP671++) {
TMP661[TMP671+3].kind = 1;
TMP661[TMP671+3].offset = TMP671;
TMP661[TMP671+3].name = TMP670[TMP671];
TMP669[TMP671] = &TMP661[TMP671+3];
}
TMP661[6].len = 3; TMP661[6].kind = 2; TMP661[6].sons = &TMP669[0];
NTI178437.node = &TMP661[6];
NTI178446.size = sizeof(NU8);
NTI178446.kind = 19;
NTI178446.base = (&NTI178437);
NTI178446.flags = 3;
TMP661[7].len = 0; TMP661[7].kind = 0;
NTI178446.node = &TMP661[7];
TMP661[2].kind = 1;
TMP661[2].offset = offsetof(Selectorkey178439, events);
TMP661[2].typ = (&NTI178446);
TMP661[2].name = "events";
TMP668[2] = &TMP661[8];
TMP661[8].kind = 1;
TMP661[8].offset = offsetof(Selectorkey178439, data);
TMP661[8].typ = (&NTI4013);
TMP661[8].name = "data";
TMP661[0].len = 3; TMP661[0].kind = 2; TMP661[0].sons = &TMP668[0];
NTI178439.node = &TMP661[0];
NTI178441.size = sizeof(Readyinfo178441);
NTI178441.kind = 18;
NTI178441.base = 0;
TMP688[0] = &TMP661[10];
TMP661[10].kind = 1;
TMP661[10].offset = offsetof(Readyinfo178441, Field0);
TMP661[10].typ = (&NTI178439);
TMP661[10].name = "Field0";
TMP688[1] = &TMP661[11];
TMP661[11].kind = 1;
TMP661[11].offset = offsetof(Readyinfo178441, Field1);
TMP661[11].typ = (&NTI178446);
TMP661[11].name = "Field1";
TMP661[9].len = 2; TMP661[9].kind = 2; TMP661[9].sons = &TMP688[0];
NTI178441.node = &TMP661[9];
NTI179655.size = sizeof(TY179655*);
NTI179655.kind = 24;
NTI179655.base = (&NTI178441);
NTI179655.marker = TMP689;
NTI178456.size = sizeof(Selector178456);
NTI178456.kind = 18;
NTI178456.base = 0;
TMP708[0] = &TMP661[13];
TMP661[13].kind = 1;
TMP661[13].offset = offsetof(Selector178456, epollfd);
TMP661[13].typ = (&NTI8211);
TMP661[13].name = "epollFD";
TMP708[1] = &TMP661[14];
NTI178459.size = sizeof(TY178459);
NTI178459.kind = 16;
NTI178459.base = (&NTI177290);
NTI178459.flags = 3;
TMP661[14].kind = 1;
TMP661[14].offset = offsetof(Selector178456, events);
TMP661[14].typ = (&NTI178459);
TMP661[14].name = "events";
TMP708[2] = &TMP661[15];
TMP661[15].kind = 1;
TMP661[15].offset = offsetof(Selector178456, fds);
TMP661[15].typ = (&NTI178466);
TMP661[15].name = "fds";
TMP661[12].len = 3; TMP661[12].kind = 2; TMP661[12].sons = &TMP708[0];
NTI178456.node = &TMP661[12];
}

