/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_tables.o src/nimcache/stdlib_tables.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Table178466 Table178466;
typedef struct Selectorkey178439 Selectorkey178439;
typedef struct TNimObject TNimObject;
typedef struct Keyvaluepairseq178469 Keyvaluepairseq178469;
typedef struct Keyvaluepair178472 Keyvaluepair178472;
typedef struct Cell49347 Cell49347;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cellset49359 Cellset49359;
typedef struct Gcheap51418 Gcheap51418;
typedef struct Gcstack51416 Gcstack51416;
typedef struct Cellseq49363 Cellseq49363;
typedef struct Pagedesc49355 Pagedesc49355;
typedef struct Memregion31291 Memregion31291;
typedef struct Smallchunk31243 Smallchunk31243;
typedef struct Llchunk31285 Llchunk31285;
typedef struct Bigchunk31245 Bigchunk31245;
typedef struct Intset31217 Intset31217;
typedef struct Trunk31213 Trunk31213;
typedef struct Avlnode31289 Avlnode31289;
typedef struct Gcstat51414 Gcstat51414;
typedef struct Keyerror4051 Keyerror4051;
typedef struct Valueerror4049 Valueerror4049;
typedef struct Exception Exception;
typedef struct Basechunk31241 Basechunk31241;
typedef struct Freecell31233 Freecell31233;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Selectorkey178439  {
int fd;
NU8 events;
TNimObject* data;
};
struct  Table178466  {
Keyvaluepairseq178469* data;
NI counter;
};
struct Keyvaluepair178472 {
NI Field0;
int Field1;
Selectorkey178439 Field2;
};
struct  Cell49347  {
NI refcount;
TNimType* typ;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  Cellseq49363  {
NI len;
NI cap;
Cell49347** d;
};
struct  Cellset49359  {
NI counter;
NI max;
Pagedesc49355* head;
Pagedesc49355** data;
};
typedef Smallchunk31243* TY31306[512];
typedef Trunk31213* Trunkbuckets31215[256];
struct  Intset31217  {
Trunkbuckets31215 data;
};
struct  Memregion31291  {
NI minlargeobj;
NI maxlargeobj;
TY31306 freesmallchunks;
Llchunk31285* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk31245* freechunkslist;
Intset31217 chunkstarts;
Avlnode31289* root;
Avlnode31289* deleted;
Avlnode31289* last;
Avlnode31289* freeavlnodes;
};
struct  Gcstat51414  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap51418  {
Gcstack51416* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq49363 zct;
Cellseq49363 decstack;
Cellset49359 cycleroots;
Cellseq49363 tempstack;
NI recgclock;
Memregion31291 region;
Gcstat51414 stat;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Valueerror4049  {
  Exception Sup;
};
struct  Keyerror4051  {
  Valueerror4049 Sup;
};
struct  Gcstack51416  {
Gcstack51416* prev;
Gcstack51416* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY31222[8];
struct  Pagedesc49355  {
Pagedesc49355* next;
NI key;
TY31222 bits;
};
struct  Basechunk31241  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk31243  {
  Basechunk31241 Sup;
Smallchunk31243* next;
Smallchunk31243* prev;
Freecell31233* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk31285  {
NI size;
NI acc;
Llchunk31285* next;
};
struct  Bigchunk31245  {
  Basechunk31241 Sup;
Bigchunk31245* next;
Bigchunk31245* prev;
NI align;
NF data;
};
struct  Trunk31213  {
Trunk31213* next;
NI key;
TY31222 bits;
};
typedef Avlnode31289* TY31296[2];
struct  Avlnode31289  {
TY31296 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell31233  {
Freecell31233* next;
NI zerofield;
};
struct Keyvaluepairseq178469 {
  TGenericSeq Sup;
  Keyvaluepair178472 data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isempty_151274)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isfilled_151281)(NI hcode);
static N_INLINE(NIM_BOOL, mustrehash_151289)(NI length, NI counter);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nexttry_151404)(NI h, NI maxhash);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, rightsize_151541)(NI count);
N_NIMCALL(NI, nextpoweroftwo_147648)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, rawget_178585)(Table178466 t, int key, NI* hc);
static N_INLINE(NI, hash_178409)(int x);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incref_55422)(Cell49347* c);
static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c);
static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c);
N_NOINLINE(void, incl_50065)(Cellset49359* s, Cell49347* cell);
static N_INLINE(Cell49347*, usrtocell_53046)(void* usr);
static N_INLINE(void, decref_55004)(Cell49347* c);
static N_INLINE(void, rtladdzct_54604)(Cell49347* c);
N_NOINLINE(void, addzct_53017)(Cellseq49363* s, Cell49347* c);
N_NIMCALL(void, enlarge_178620)(Table178466* t);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP673)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, rawgetknownhc_178674)(Table178466 t, int key, NI hc);
N_NIMCALL(void, rawinsert_178699)(Table178466* t, Keyvaluepairseq178469** data, int key, Selectorkey178439 val, NI hc, NI h);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, ispoweroftwo_147638)(NI x);
STRING_LITERAL(TMP586, "\012  counter < length ", 20);
STRING_LITERAL(TMP683, "key not found: ", 15);
STRING_LITERAL(TMP686, "isPowerOfTwo(initialSize) ", 26);
extern TFrame* frameptr_20842;
extern Gcheap51418 gch_51459;
TNimType NTI178472; /* KeyValuePair */
extern TNimType NTI144005; /* Hash */
extern TNimType NTI8211; /* cint */
extern TNimType NTI178439; /* SelectorKey */
TNimType NTI178469; /* KeyValuePairSeq */
extern TNimType NTI179004; /* ref KeyError */
extern TNimType NTI4051; /* KeyError */
TNimType NTI178466; /* Table */
extern TNimType NTI108; /* int */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

static N_INLINE(NIM_BOOL, isempty_151274)(NI hcode) {
	NIM_BOOL result;
	nimfr("isEmpty", "tableimpl.nim")
	result = 0;
	nimln(15, "tableimpl.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isfilled_151281)(NI hcode) {
	NIM_BOOL result;
	nimfr("isFilled", "tableimpl.nim")
	result = 0;
	nimln(18, "tableimpl.nim");
	nimln(349, "system.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustrehash_151289)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL LOC5;
	NI TMP587;
	NI TMP588;
	NI TMP589;
	nimfr("mustRehash", "tableimpl.nim")
	result = 0;
	nimln(24, "tableimpl.nim");
	{
		if (!!((counter < length))) goto LA3;
		failedassertimpl_91603(((NimStringDesc*) &TMP586));
	}
	LA3: ;
	nimln(25, "tableimpl.nim");
	LOC5 = 0;
	TMP587 = mulInt(length, ((NI) 2));
	TMP588 = mulInt(counter, ((NI) 3));
	LOC5 = ((NI)(TMP587) < (NI)(TMP588));
	if (LOC5) goto LA6;
	TMP589 = subInt(length, counter);
	LOC5 = ((NI)(TMP589) < ((NI) 4));
	LA6: ;
	result = LOC5;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, nexttry_151404)(NI h, NI maxhash) {
	NI result;
	NI TMP590;
	nimfr("nextTry", "tableimpl.nim")
	result = 0;
	nimln(28, "tableimpl.nim");
	TMP590 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TMP590) & maxhash);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, rightsize_151541)(NI count) {
	NI result;
	NI TMP591;
	NI TMP592;
	NI TMP593;
	nimfr("rightSize", "tables.nim")
	result = 0;
	nimln(95, "tables.nim");
	TMP591 = mulInt(((NI) (count)), ((NI) 3));
	TMP592 = divInt(((NI) ((NI)(TMP591))), ((NI) 2));
	TMP593 = addInt(((NI) ((NI)(TMP592))), ((NI) 4));
	result = nextpoweroftwo_147648(((NI) ((NI)(TMP593))));
	popFrame();
	return result;
}

static N_INLINE(NI, hash_178409)(int x) {
	NI result;
	nimfr("hash", "hashes.nim")
	result = 0;
	nimln(121, "hashes.nim");
	result = ((NI) (x));
	popFrame();
	return result;
}

static N_INLINE(NI, rawget_178585)(Table178466 t, int key, NI* hc) {
	NI result;
	NI h;
	NI TMP665;
	nimfr("rawGet", "tableimpl.nim")
{	result = 0;
	nimln(43, "tableimpl.nim");
	(*hc) = hash_178409(key);
	nimln(44, "tableimpl.nim");
	{
		if (!((*hc) == ((NI) 0))) goto LA3;
		nimln(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3: ;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)((*hc) & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC7;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC7 = 0;
			LOC7 = isfilled_151281(t.data->data[h].Field0);
			if (!LOC7) goto LA6;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC10;
				LOC10 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field0 == (*hc));
				if (!(LOC10)) goto LA11;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC10 = (t.data->data[h].Field1 == key);
				LA11: ;
				if (!LOC10) goto LA12;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA12: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_151404(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA6: ;
	}
	nimln(40, "tableimpl.nim");
	TMP665 = subInt(((NI) -1), h);
	result = (NI)(TMP665);
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, canbecycleroot_53067)(Cell49347* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_53823)(Cell49347* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_50065((&gch_51459.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, incref_55422)(Cell49347* c) {
	nimfr("incRef", "gc.nim")
	nimln(229, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	nimln(232, "gc.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = canbecycleroot_53067(c);
		if (!LOC3) goto LA4;
		nimln(233, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	LA4: ;
	popFrame();
}

static N_INLINE(Cell49347*, usrtocell_53046)(void* usr) {
	Cell49347* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell49347*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell49347))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_54604)(Cell49347* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_53017((&gch_51459.zct), c);
	popFrame();
}

static N_INLINE(void, decref_55004)(Cell49347* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_54604(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_53067(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_53823(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr("asgnRef", "gc.nim")
	nimln(257, "gc.nim");
	{
		Cell49347* LOC5;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(257, "gc.nim");
		LOC5 = 0;
		LOC5 = usrtocell_53046(src);
		incref_55422(LOC5);
	}
	LA3: ;
	nimln(258, "gc.nim");
	{
		Cell49347* LOC10;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8;
		nimln(258, "gc.nim");
		LOC10 = 0;
		LOC10 = usrtocell_53046((*dest));
		decref_55004(LOC10);
	}
	LA8: ;
	nimln(259, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}
N_NIMCALL(void, TMP673)(void* p, NI op) {
	Keyvaluepairseq178469* a;
	NI LOC1;
	a = (Keyvaluepairseq178469*)p;
	LOC1 = 0;
	for (LOC1 = 0; LOC1 < a->Sup.len; LOC1++) {
	nimGCvisit((void*)a->data[LOC1].Field2.data, op);
	}
}

static N_INLINE(NI, rawgetknownhc_178674)(Table178466 t, int key, NI hc) {
	NI result;
	NI h;
	NI TMP674;
	nimfr("rawGetKnownHC", "tableimpl.nim")
{	result = 0;
	nimln(31, "tableimpl.nim");
	nimln(83, "tables.nim");
	h = (NI)(hc & (t.data ? (t.data->Sup.len-1) : -1));
	{
		nimln(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL LOC3;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			LOC3 = 0;
			LOC3 = isfilled_151281(t.data->data[h].Field0);
			if (!LOC3) goto LA2;
			nimln(37, "tableimpl.nim");
			{
				NIM_BOOL LOC6;
				LOC6 = 0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field0 == hc);
				if (!(LOC6)) goto LA7;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				LOC6 = (t.data->data[h].Field1 == key);
				LA7: ;
				if (!LOC6) goto LA8;
				nimln(38, "tableimpl.nim");
				result = h;
				goto BeforeRet;
			}
			LA8: ;
			nimln(39, "tableimpl.nim");
			nimln(83, "tables.nim");
			h = nexttry_151404(h, (t.data ? (t.data->Sup.len-1) : -1));
		} LA2: ;
	}
	nimln(40, "tableimpl.nim");
	TMP674 = subInt(((NI) -1), h);
	result = (NI)(TMP674);
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, rawinsert_178699)(Table178466* t, Keyvaluepairseq178469** data, int key, Selectorkey178439 val, NI hc, NI h) {
	nimfr("rawInsert", "tableimpl.nim")
	nimln(58, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field1 = key;
	nimln(59, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field2.fd = val.fd;
	(*data)->data[h].Field2.events = val.events;
	asgnRef((void**) (&(*data)->data[h].Field2.data), val.data);
	nimln(60, "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_NIMCALL(void, enlarge_178620)(Table178466* t) {
	Keyvaluepairseq178469* n;
	NI TMP666;
	Keyvaluepairseq178469* LOC1;
	nimfr("enlarge", "tables.nim")
	n = 0;
	nimln(188, "tables.nim");
	TMP666 = mulInt(((*t).data ? (*t).data->Sup.len : 0), ((NI) 2));
	n = (Keyvaluepairseq178469*) newSeq((&NTI178469), ((NI)chckRange((NI)(TMP666), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(189, "tables.nim");
	LOC1 = 0;
	LOC1 = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = LOC1;
	{
		NI i_178672;
		NI HEX3Atmp_178725;
		NI res_178728;
		i_178672 = 0;
		HEX3Atmp_178725 = 0;
		nimln(190, "tables.nim");
		HEX3Atmp_178725 = (n ? (n->Sup.len-1) : -1);
		nimln(1874, "system.nim");
		res_178728 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP676;
				if (!(res_178728 <= HEX3Atmp_178725)) goto LA4;
				nimln(1876, "system.nim");
				i_178672 = res_178728;
				nimln(191, "tables.nim");
				{
					NIM_BOOL LOC7;
					NI j;
					NI LOC10;
					NI TMP675;
					if ((NU)(i_178672) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC7 = 0;
					LOC7 = isfilled_151281(n->data[i_178672].Field0);
					if (!LOC7) goto LA8;
					nimln(192, "tables.nim");
					if ((NU)(i_178672) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_178672) >= (NU)(n->Sup.len)) raiseIndexError();
					LOC10 = 0;
					LOC10 = rawgetknownhc_178674((*t), n->data[i_178672].Field1, n->data[i_178672].Field0);
					TMP675 = subInt(((NI) -1), LOC10);
					j = (NI)(TMP675);
					nimln(193, "tables.nim");
					if ((NU)(i_178672) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_178672) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i_178672) >= (NU)(n->Sup.len)) raiseIndexError();
					rawinsert_178699(t, (&(*t).data), n->data[i_178672].Field1, n->data[i_178672].Field2, n->data[i_178672].Field0, j);
				}
				LA8: ;
				nimln(1890, "system.nim");
				TMP676 = addInt(res_178728, ((NI) 1));
				res_178728 = (NI)(TMP676);
			} LA4: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5DHEX3D_178571)(Table178466* t, int key, Selectorkey178439 val) {
	NI hc;
	NI index;
	nimfr("[]=", "tables.nim")
	hc = 0;
	nimln(92, "tableimpl.nim");
	index = rawget_178585((*t), key, (&hc));
	nimln(93, "tableimpl.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index)) goto LA3;
		nimln(93, "tableimpl.nim");
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2.fd = val.fd;
		(*t).data->data[index].Field2.events = val.events;
		asgnRef((void**) (&(*t).data->data[index].Field2.data), val.data);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP677;
		NI TMP678;
		nimln(83, "tableimpl.nim");
		{
			NIM_BOOL LOC8;
			nimln(84, "tables.nim");
			LOC8 = 0;
			LOC8 = mustrehash_151289(((*t).data ? (*t).data->Sup.len : 0), (*t).counter);
			if (!LOC8) goto LA9;
			nimln(84, "tableimpl.nim");
			enlarge_178620(t);
			nimln(85, "tableimpl.nim");
			index = rawgetknownhc_178674((*t), key, hc);
		}
		LA9: ;
		nimln(86, "tableimpl.nim");
		TMP677 = subInt(((NI) -1), index);
		index = (NI)(TMP677);
		nimln(87, "tableimpl.nim");
		rawinsert_178699(t, (&(*t).data), key, val, hc, index);
		nimln(88, "tableimpl.nim");
		TMP678 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP678);
	}
	LA1: ;
	popFrame();
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	memcpy(((NCSTRING) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((NCSTRING) ((*src).data)), (NI)((*src).Sup.len + ((NI) 1)));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr("asgnRefNoCycle", "gc.nim")
	nimln(264, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!((src == NIM_NIL))) goto LA3;
		nimln(265, "gc.nim");
		c = usrtocell_53046(src);
		nimln(182, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3: ;
	nimln(267, "gc.nim");
	{
		Cell49347* c;
		nimln(349, "system.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7;
		nimln(268, "gc.nim");
		c = usrtocell_53046((*dest));
		nimln(269, "gc.nim");
		{
			nimln(180, "gc.nim");
			(*c).refcount -= ((NI) 8);
			nimln(181, "gc.nim");
			if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA11;
			nimln(270, "gc.nim");
			rtladdzct_54604(c);
		}
		LA11: ;
	}
	LA7: ;
	nimln(271, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_NIMCALL(Selectorkey178439*, HEX5BHEX5D_178804)(Table178466* t, int key) {
	Selectorkey178439* result;
	NI hc_178817;
	NI index_178819;
	nimfr("[]", "tables.nim")
	result = 0;
	hc_178817 = 0;
	nimln(106, "tables.nim");
	index_178819 = rawget_178585((*t), key, (&hc_178817));
	nimln(107, "tables.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_178819)) goto LA3;
		nimln(107, "tables.nim");
		if ((NU)(index_178819) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index_178819].Field2);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror4051* e_179003;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		e_179003 = 0;
		nimln(2507, "system.nim");
		e_179003 = (Keyerror4051*) newObj((&NTI179004), sizeof(Keyerror4051));
		(*e_179003).Sup.Sup.Sup.m_type = (&NTI4051);
		nimln(2508, "system.nim");
		nimln(110, "tables.nim");
		LOC6 = 0;
		LOC7 = 0;
		LOC7 = nimIntToStr(key);
		LOC6 = rawNewString(LOC7->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP683));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_179003).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_179003, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(Selectorkey178439*, mget_179058)(Table178466* t, int key) {
	Selectorkey178439* result;
	NI hc_179071;
	NI index_179073;
	nimfr("mget", "tables.nim")
	result = 0;
	hc_179071 = 0;
	nimln(106, "tables.nim");
	index_179073 = rawget_178585((*t), key, (&hc_179071));
	nimln(107, "tables.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_179073)) goto LA3;
		nimln(107, "tables.nim");
		if ((NU)(index_179073) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		result = (&(*t).data->data[index_179073].Field2);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror4051* e_179203;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		e_179203 = 0;
		nimln(2507, "system.nim");
		e_179203 = (Keyerror4051*) newObj((&NTI179004), sizeof(Keyerror4051));
		(*e_179203).Sup.Sup.Sup.m_type = (&NTI4051);
		nimln(2508, "system.nim");
		nimln(110, "tables.nim");
		LOC6 = 0;
		LOC7 = 0;
		LOC7 = nimIntToStr(key);
		LOC6 = rawNewString(LOC7->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP683));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_179203).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_179203, "KeyError");
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, del_179325)(Table178466* t, int key) {
	NI hc;
	NI i;
	NI msk;
	nimfr("del", "tables.nim")
	hc = 0;
	nimln(115, "tableimpl.nim");
	i = rawget_178585((*t), key, (&hc));
	nimln(116, "tableimpl.nim");
	nimln(83, "tables.nim");
	msk = ((*t).data ? ((*t).data->Sup.len-1) : -1);
	nimln(117, "tableimpl.nim");
	{
		NI TMP684;
		nimln(353, "system.nim");
		if (!(((NI) 0) <= i)) goto LA3;
		nimln(118, "tableimpl.nim");
		if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[i].Field0 = ((NI) 0);
		nimln(119, "tableimpl.nim");
		TMP684 = subInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TMP684);
		{
			{
				nimln(121, "tableimpl.nim");
				while (1) {
					NI j;
					NI r;
					nimln(122, "tableimpl.nim");
					j = i;
					nimln(123, "tableimpl.nim");
					r = j;
					nimln(124, "tableimpl.nim");
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					(*t).data->data[i].Field0 = ((NI) 0);
					{
						nimln(125, "tableimpl.nim");
						while (1) {
							NI TMP685;
							nimln(126, "tableimpl.nim");
							TMP685 = addInt(i, ((NI) 1));
							i = (NI)((NI)(TMP685) & msk);
							nimln(127, "tableimpl.nim");
							{
								NIM_BOOL LOC12;
								if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
								LOC12 = 0;
								LOC12 = isempty_151274((*t).data->data[i].Field0);
								if (!LOC12) goto LA13;
								nimln(128, "tableimpl.nim");
								goto LA5;
							}
							LA13: ;
							nimln(129, "tableimpl.nim");
							if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							r = (NI)((*t).data->data[i].Field0 & msk);
							nimln(130, "tableimpl.nim");
							{
								NIM_BOOL LOC17;
								NIM_BOOL LOC18;
								NIM_BOOL LOC19;
								NIM_BOOL LOC22;
								NIM_BOOL LOC25;
								LOC17 = 0;
								LOC18 = 0;
								LOC19 = 0;
								nimln(353, "system.nim");
								LOC19 = (r <= i);
								if (!(LOC19)) goto LA20;
								nimln(357, "system.nim");
								LOC19 = (j < r);
								LA20: ;
								LOC18 = LOC19;
								if (LOC18) goto LA21;
								nimln(130, "tableimpl.nim");
								LOC22 = 0;
								nimln(357, "system.nim");
								LOC22 = (j < r);
								if (!(LOC22)) goto LA23;
								LOC22 = (i < j);
								LA23: ;
								LOC18 = LOC22;
								LA21: ;
								LOC17 = LOC18;
								if (LOC17) goto LA24;
								nimln(130, "tableimpl.nim");
								LOC25 = 0;
								nimln(357, "system.nim");
								LOC25 = (i < j);
								if (!(LOC25)) goto LA26;
								nimln(353, "system.nim");
								LOC25 = (r <= i);
								LA26: ;
								LOC17 = LOC25;
								LA24: ;
								if (!!(LOC17)) goto LA27;
								nimln(131, "tableimpl.nim");
								goto LA8;
							}
							LA27: ;
						}
					} LA8: ;
					nimln(132, "tableimpl.nim");
					if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)((*t).data->Sup.len)) raiseIndexError();
					(*t).data->data[j].Field0 = (*t).data->data[i].Field0;
					(*t).data->data[j].Field1 = (*t).data->data[i].Field1;
					(*t).data->data[j].Field2.fd = (*t).data->data[i].Field2.fd;
					(*t).data->data[j].Field2.events = (*t).data->data[i].Field2.events;
					asgnRef((void**) (&(*t).data->data[j].Field2.data), (*t).data->data[i].Field2.data);
				}
			}
		} LA5: ;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, HEX5BHEX5D_179417)(Table178466 t, int key, Selectorkey178439* Result) {
	NI hc_179428;
	NI index_179430;
	nimfr("[]", "tables.nim")
	hc_179428 = 0;
	nimln(106, "tables.nim");
	index_179430 = rawget_178585(t, key, (&hc_179428));
	nimln(107, "tables.nim");
	{
		nimln(353, "system.nim");
		if (!(((NI) 0) <= index_179430)) goto LA3;
		nimln(107, "tables.nim");
		if ((NU)(index_179430) >= (NU)(t.data->Sup.len)) raiseIndexError();
		(*Result).fd = t.data->data[index_179430].Field2.fd;
		(*Result).events = t.data->data[index_179430].Field2.events;
		unsureAsgnRef((void**) (&(*Result).data), t.data->data[index_179430].Field2.data);
	}
	goto LA1;
	LA3: ;
	{
		Keyerror4051* e_179603;
		NimStringDesc* LOC6;
		NimStringDesc* LOC7;
		e_179603 = 0;
		nimln(2507, "system.nim");
		e_179603 = (Keyerror4051*) newObj((&NTI179004), sizeof(Keyerror4051));
		(*e_179603).Sup.Sup.Sup.m_type = (&NTI4051);
		nimln(2508, "system.nim");
		nimln(110, "tables.nim");
		LOC6 = 0;
		LOC7 = 0;
		LOC7 = nimIntToStr(key);
		LOC6 = rawNewString(LOC7->Sup.len + 15);
appendString(LOC6, ((NimStringDesc*) &TMP683));
appendString(LOC6, LOC7);
		asgnRefNoCycle((void**) (&(*e_179603).Sup.Sup.message), LOC6);
		raiseException((Exception*)e_179603, "KeyError");
	}
	LA1: ;
	popFrame();
}

N_NIMCALL(void, inittable_180202)(NI initialsize, Table178466* Result) {
	nimfr("initTable", "tables.nim")
	nimln(222, "tables.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = ispoweroftwo_147638(initialsize);
		if (!!(LOC3)) goto LA4;
		failedassertimpl_91603(((NimStringDesc*) &TMP686));
	}
	LA4: ;
	nimln(223, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln(224, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (Keyvaluepairseq178469*) newSeq((&NTI178469), ((NI)chckRange(initialsize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_NIMCALL(NIM_BOOL, haskey_180423)(Table178466 t, int key) {
	NIM_BOOL result;
	NI hc;
	NI LOC1;
	nimfr("hasKey", "tables.nim")
	result = 0;
	hc = 0;
	nimln(150, "tables.nim");
	nimln(353, "system.nim");
	nimln(150, "tables.nim");
	LOC1 = 0;
	LOC1 = rawget_178585(t, key, (&hc));
	result = (((NI) 0) <= LOC1);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr("tables", "tables.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TMP667[3];
static TNimNode* TMP710[2];
static TNimNode TMP547[7];
NTI178472.size = sizeof(Keyvaluepair178472);
NTI178472.kind = 18;
NTI178472.base = 0;
TMP667[0] = &TMP547[1];
TMP547[1].kind = 1;
TMP547[1].offset = offsetof(Keyvaluepair178472, Field0);
TMP547[1].typ = (&NTI144005);
TMP547[1].name = "Field0";
TMP667[1] = &TMP547[2];
TMP547[2].kind = 1;
TMP547[2].offset = offsetof(Keyvaluepair178472, Field1);
TMP547[2].typ = (&NTI8211);
TMP547[2].name = "Field1";
TMP667[2] = &TMP547[3];
TMP547[3].kind = 1;
TMP547[3].offset = offsetof(Keyvaluepair178472, Field2);
TMP547[3].typ = (&NTI178439);
TMP547[3].name = "Field2";
TMP547[0].len = 3; TMP547[0].kind = 2; TMP547[0].sons = &TMP667[0];
NTI178472.node = &TMP547[0];
NTI178469.size = sizeof(Keyvaluepairseq178469*);
NTI178469.kind = 24;
NTI178469.base = (&NTI178472);
NTI178469.marker = TMP673;
NTI178466.size = sizeof(Table178466);
NTI178466.kind = 18;
NTI178466.base = 0;
TMP710[0] = &TMP547[5];
TMP547[5].kind = 1;
TMP547[5].offset = offsetof(Table178466, data);
TMP547[5].typ = (&NTI178469);
TMP547[5].name = "data";
TMP710[1] = &TMP547[6];
TMP547[6].kind = 1;
TMP547[6].offset = offsetof(Table178466, counter);
TMP547[6].typ = (&NTI108);
TMP547[6].name = "counter";
TMP547[4].len = 2; TMP547[4].kind = 2; TMP547[4].sons = &TMP710[0];
NTI178466.node = &TMP547[4];
}

