/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_epoll.o src/nimcache/stdlib_epoll.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/epoll.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI177290; /* epoll_event */
extern TNimType NTI124; /* uint32 */
TNimType NTI177288; /* epoll_data */
extern TNimType NTI8211; /* cint */
extern TFrame* frameptr_20842;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_epollInit000)(void) {
	nimfr("epoll", "epoll.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_epollDatInit000)(void) {
static TNimNode* TMP709[2];
static TNimNode TMP663[4];
NTI177290.size = sizeof(struct epoll_event);
NTI177290.kind = 18;
NTI177290.base = 0;
NTI177290.flags = 3;
TMP709[0] = &TMP663[1];
TMP663[1].kind = 1;
TMP663[1].offset = offsetof(struct epoll_event, events);
TMP663[1].typ = (&NTI124);
TMP663[1].name = "events";
TMP709[1] = &TMP663[2];
NTI177288.size = sizeof(union epoll_data);
NTI177288.kind = 18;
NTI177288.base = 0;
NTI177288.flags = 3;
TMP663[3].kind = 1;
TMP663[3].offset = offsetof(union epoll_data, fd);
TMP663[3].typ = (&NTI8211);
TMP663[3].name = "fd";
NTI177288.node = &TMP663[3];
TMP663[2].kind = 1;
TMP663[2].offset = offsetof(struct epoll_event, data);
TMP663[2].typ = (&NTI177288);
TMP663[2].name = "data";
TMP663[0].len = 2; TMP663[0].kind = 2; TMP663[0].sons = &TMP709[0];
NTI177290.node = &TMP663[0];
}

