/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_streams.o src/nimcache/stdlib_streams.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <setjmp.h>
#include <string.h>
#include <stdio.h>
typedef struct Ioerror4031 Ioerror4031;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Systemerror4029 Systemerror4029;
typedef struct Exception Exception;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Cell55949 Cell55949;
typedef struct Cellseq55965 Cellseq55965;
typedef struct Gcheap58018 Gcheap58018;
typedef struct Gcstack58016 Gcstack58016;
typedef struct Cellset55961 Cellset55961;
typedef struct Pagedesc55957 Pagedesc55957;
typedef struct Memregion37891 Memregion37891;
typedef struct Smallchunk37843 Smallchunk37843;
typedef struct Llchunk37885 Llchunk37885;
typedef struct Bigchunk37845 Bigchunk37845;
typedef struct Intset37817 Intset37817;
typedef struct Trunk37813 Trunk37813;
typedef struct Avlnode37889 Avlnode37889;
typedef struct Gcstat58014 Gcstat58014;
typedef struct Streamobj219227 Streamobj219227;
typedef struct TSafePoint TSafePoint;
typedef struct Stringstreamobj220311 Stringstreamobj220311;
typedef struct Filestreamobj220467 Filestreamobj220467;
typedef struct Basechunk37841 Basechunk37841;
typedef struct Freecell37833 Freecell37833;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Exception  {
  TNimObject Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
NimStringDesc* trace;
};
struct  Systemerror4029  {
  Exception Sup;
};
struct  Ioerror4031  {
  Systemerror4029 Sup;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Cell55949  {
NI refcount;
TNimType* typ;
};
struct  Cellseq55965  {
NI len;
NI cap;
Cell55949** d;
};
struct  Cellset55961  {
NI counter;
NI max;
Pagedesc55957* head;
Pagedesc55957** data;
};
typedef Smallchunk37843* TY37906[512];
typedef Trunk37813* Trunkbuckets37815[256];
struct  Intset37817  {
Trunkbuckets37815 data;
};
struct  Memregion37891  {
NI minlargeobj;
NI maxlargeobj;
TY37906 freesmallchunks;
Llchunk37885* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk37845* freechunkslist;
Intset37817 chunkstarts;
Avlnode37889* root;
Avlnode37889* deleted;
Avlnode37889* last;
Avlnode37889* freeavlnodes;
};
struct  Gcstat58014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap58018  {
Gcstack58016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq55965 zct;
Cellseq55965 decstack;
Cellset55961 cycleroots;
Cellseq55965 tempstack;
NI recgclock;
Memregion37891 region;
Gcstat58014 stat;
};
typedef N_NIMCALL_PTR(void, TY219228) (Streamobj219227* s);
typedef N_NIMCALL_PTR(NIM_BOOL, TY219232) (Streamobj219227* s);
typedef N_NIMCALL_PTR(void, TY219236) (Streamobj219227* s, NI pos);
typedef N_NIMCALL_PTR(NI, TY219241) (Streamobj219227* s);
typedef N_NIMCALL_PTR(NI, TY219245) (Streamobj219227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(NI, TY219251) (Streamobj219227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY219257) (Streamobj219227* s, void* buffer, NI buflen);
typedef N_NIMCALL_PTR(void, TY219263) (Streamobj219227* s);
struct  Streamobj219227  {
  TNimObject Sup;
TY219228 closeimpl;
TY219232 atendimpl;
TY219236 setpositionimpl;
TY219241 getpositionimpl;
TY219245 readdataimpl;
TY219251 peekdataimpl;
TY219257 writedataimpl;
TY219263 flushimpl;
};
typedef struct {
N_NIMCALL_PTR(NIM_BOOL, ClPrc) (Exception* e, void* ClEnv);
void* ClEnv;
} TY19611;
struct  TSafePoint  {
TSafePoint* prev;
NI status;
jmp_buf context;
NIM_BOOL hasRaiseAction;
TY19611 raiseAction;
};
struct  Stringstreamobj220311  {
  Streamobj219227 Sup;
NimStringDesc* data;
NI pos;
};
struct  Filestreamobj220467  {
  Streamobj219227 Sup;
FILE* f;
};
struct  Gcstack58016  {
Gcstack58016* prev;
Gcstack58016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY37822[8];
struct  Pagedesc55957  {
Pagedesc55957* next;
NI key;
TY37822 bits;
};
struct  Basechunk37841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk37843  {
  Basechunk37841 Sup;
Smallchunk37843* next;
Smallchunk37843* prev;
Freecell37833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk37885  {
NI size;
NI acc;
Llchunk37885* next;
};
struct  Bigchunk37845  {
  Basechunk37841 Sup;
Bigchunk37845* next;
Bigchunk37845* prev;
NI align;
NF data;
};
struct  Trunk37813  {
Trunk37813* next;
NI key;
TY37822 bits;
};
typedef Avlnode37889* TY37896[2];
struct  Avlnode37889  {
TY37896 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell37833  {
Freecell37833* next;
NI zerofield;
};
N_NIMCALL(Ioerror4031*, neweio_219205)(NimStringDesc* msg);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(Cell55949*, usrtocell_59673)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_30201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtladdzct_61204)(Cell55949* c);
N_NOINLINE(void, addzct_59644)(Cellseq55965* s, Cell55949* c);
N_NIMCALL(void, flush_219275)(Streamobj219227* s);
N_NIMCALL(void, close_219291)(Streamobj219227* s);
N_NIMCALL(void, close_219307)(Streamobj219227* s, Streamobj219227* unused);
N_NIMCALL(NIM_BOOL, atend_219317)(Streamobj219227* s);
N_NIMCALL(NIM_BOOL, atend_219327)(Streamobj219227* s, Streamobj219227* unused);
N_NIMCALL(void, setposition_219338)(Streamobj219227* s, NI pos);
N_NIMCALL(void, setposition_219348)(Streamobj219227* s, Streamobj219227* unused, NI pos);
N_NIMCALL(NI, getposition_219359)(Streamobj219227* s);
N_NIMCALL(NI, getposition_219369)(Streamobj219227* s, Streamobj219227* unused);
N_NIMCALL(NI, readdata_219380)(Streamobj219227* s, void* buffer, NI buflen);
N_NIMCALL(NimStringDesc*, readall_219392)(Streamobj219227* s);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newlen);
N_NIMCALL(NI, readdata_219423)(Streamobj219227* s, Streamobj219227* unused, void* buffer, NI buflen);
N_NIMCALL(NI, peekdata_219436)(Streamobj219227* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_219448)(Streamobj219227* s, void* buffer, NI buflen);
N_NIMCALL(void, writedata_219459)(Streamobj219227* s, Streamobj219227* unused, void* buffer, NI buflen);
N_NIMCALL(void, write_219483)(Streamobj219227* s, NimStringDesc* x);
N_NIMCALL(void, writeln_219493)(Streamobj219227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(void, writeline_219526)(Streamobj219227* s, NimStringDesc** args, NI argsLen0);
N_NIMCALL(NIM_CHAR, readchar_219584)(Streamobj219227* s);
N_NIMCALL(NIM_CHAR, peekchar_219595)(Streamobj219227* s);
N_NIMCALL(void, read_219611)(Streamobj219227* s, NIM_BOOL* result);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NIMCALL(NIM_BOOL, readbool_219606)(Streamobj219227* s);
N_NIMCALL(void, peek_219656)(Streamobj219227* s, NIM_BOOL* result);
N_NIMCALL(NIM_BOOL, peekbool_219651)(Streamobj219227* s);
N_NIMCALL(void, read_219698)(Streamobj219227* s, NI8* result);
N_NIMCALL(NI8, readint8_219693)(Streamobj219227* s);
N_NIMCALL(void, peek_219743)(Streamobj219227* s, NI8* result);
N_NIMCALL(NI8, peekint8_219738)(Streamobj219227* s);
N_NIMCALL(void, read_219785)(Streamobj219227* s, NI16* result);
N_NIMCALL(NI16, readint16_219780)(Streamobj219227* s);
N_NIMCALL(void, peek_219830)(Streamobj219227* s, NI16* result);
N_NIMCALL(NI16, peekint16_219825)(Streamobj219227* s);
N_NIMCALL(void, read_219872)(Streamobj219227* s, NI32* result);
N_NIMCALL(NI32, readint32_219867)(Streamobj219227* s);
N_NIMCALL(void, peek_219917)(Streamobj219227* s, NI32* result);
N_NIMCALL(NI32, peekint32_219912)(Streamobj219227* s);
N_NIMCALL(void, read_219959)(Streamobj219227* s, NI64* result);
N_NIMCALL(NI64, readint64_219954)(Streamobj219227* s);
N_NIMCALL(void, peek_220004)(Streamobj219227* s, NI64* result);
N_NIMCALL(NI64, peekint64_219999)(Streamobj219227* s);
N_NIMCALL(void, read_220046)(Streamobj219227* s, NF32* result);
N_NIMCALL(NF32, readfloat32_220041)(Streamobj219227* s);
N_NIMCALL(void, peek_220091)(Streamobj219227* s, NF32* result);
N_NIMCALL(NF32, peekfloat32_220086)(Streamobj219227* s);
N_NIMCALL(void, read_220133)(Streamobj219227* s, NF* result);
N_NIMCALL(NF, readfloat64_220128)(Streamobj219227* s);
N_NIMCALL(void, peek_220175)(Streamobj219227* s, NF* result);
N_NIMCALL(NF, peekfloat64_220170)(Streamobj219227* s);
N_NIMCALL(NimStringDesc*, readstr_220212)(Streamobj219227* s, NI length);
N_NIMCALL(NimStringDesc*, peekstr_220227)(Streamobj219227* s, NI length);
N_NIMCALL(NIM_BOOL, readline_220242)(Streamobj219227* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_NIMCALL(NIM_BOOL, peekline_220264)(Streamobj219227* s, NimStringDesc** line);
static N_INLINE(void, pushSafePoint)(TSafePoint* s);
static N_INLINE(void, popSafePoint)(void);
static N_INLINE(void, setFrame)(TFrame* s);
N_NIMCALL(void, reraiseException)(void);
N_NIMCALL(NimStringDesc*, readline_220277)(Streamobj219227* s);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, peekline_220297)(Streamobj219227* s);
N_NIMCALL(NIM_BOOL, ssatend_220322)(Streamobj219227* s_220324);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_NIMCALL(NI, clamp_220339)(NI x, NI a, NI b);
N_NIMCALL(void, sssetposition_220333)(Streamobj219227* s_220335, NI pos);
N_NIMCALL(NI, ssgetposition_220358)(Streamobj219227* s_220360);
N_NIMCALL(NI, ssreaddata_220369)(Streamobj219227* s_220371, void* buffer, NI buflen);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(NI, sspeekdata_220396)(Streamobj219227* s_220398, void* buffer, NI buflen);
N_NIMCALL(void, sswritedata_220414)(Streamobj219227* s_220416, void* buffer, NI buflen);
N_NIMCALL(void, ssclose_220436)(Streamobj219227* s_220438);
N_NIMCALL(Stringstreamobj220311*, newstringstream_220446)(NimStringDesc* s);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP937)(void* p, NI op);
N_NIMCALL(void, fsclose_220471)(Streamobj219227* s);
N_NIMCALL(void, fsflush_220489)(Streamobj219227* s);
N_NIMCALL(NIM_BOOL, fsatend_220495)(Streamobj219227* s);
N_NIMCALL(NIM_BOOL, endoffile_16860)(FILE* f);
N_NIMCALL(void, fssetposition_220502)(Streamobj219227* s, NI pos);
N_NIMCALL(void, setfilepos_16987)(FILE* f, NI64 pos);
N_NIMCALL(NI, fsgetposition_220509)(Streamobj219227* s);
N_NIMCALL(NI64, getfilepos_16991)(FILE* f);
N_NIMCALL(NI, fsreaddata_220517)(Streamobj219227* s, void* buffer, NI buflen);
N_NIMCALL(NI, readbuffer_16960)(FILE* f, void* buffer, NI len);
N_NIMCALL(NI, fspeekdata_220526)(Streamobj219227* s, void* buffer, NI buflen);
N_NIMCALL(void, fswritedata_220536)(Streamobj219227* s, void* buffer, NI buflen);
N_NIMCALL(NI, writebuffer_16982)(FILE* f, void* buffer, NI len);
N_NIMCALL(Filestreamobj220467*, newfilestream_220544)(FILE* f);
N_NIMCALL(void, TMP940)(void* p, NI op);
N_NIMCALL(Filestreamobj220467*, newfilestream_220559)(NimStringDesc* filename, NU8 mode);
N_NIMCALL(NIM_BOOL, open_16803)(FILE** f, NimStringDesc* filename, NU8 mode, NI bufsize);
N_NIMCALL(void, TMP1166)(void* p, NI op);
STRING_LITERAL(TMP923, "\012", 1);
STRING_LITERAL(TMP925, "cannot read from stream", 23);
STRING_LITERAL(TMP927, "", 0);
STRING_LITERAL(TMP939, "cannot write to stream", 22);
extern TNimType NTI16835; /* ref IOError */
extern TNimType NTI4031; /* IOError */
extern NIM_THREADVAR TFrame* frameptr_27442;
extern NIM_THREADVAR Gcheap58018 gch_58059;
extern NIM_THREADVAR TSafePoint* exchandler_27443;
extern TNimType NTI4011; /* RootObj */
TNimType NTI219227; /* StreamObj */
TNimType NTI219228; /* proc (s: Stream){.gcsafe.} */
TNimType NTI219232; /* proc (s: Stream): bool{.gcsafe.} */
TNimType NTI219236; /* proc (s: Stream, pos: int){.gcsafe.} */
TNimType NTI219241; /* proc (s: Stream): int{.gcsafe.} */
TNimType NTI219245; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI219251; /* proc (s: Stream, buffer: pointer, bufLen: int): int{.gcsafe.} */
TNimType NTI219257; /* proc (s: Stream, buffer: pointer, bufLen: int){.gcsafe.} */
TNimType NTI219263; /* proc (s: Stream){.gcsafe.} */
TNimType NTI220311; /* StringStreamObj */
extern TNimType NTI149; /* string */
extern TNimType NTI108; /* int */
TNimType NTI220309; /* StringStream */
TNimType NTI220467; /* FileStreamObj */
extern TNimType NTI16404; /* File */
TNimType NTI220465; /* FileStream */
TNimType NTI219225; /* Stream */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_27442 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_27442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_27442;
	frameptr_27442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_30201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_27442 = (*frameptr_27442).prev;
}

static N_INLINE(Cell55949*, usrtocell_59673)(void* usr) {
	Cell55949* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell55949*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell55949))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_61204)(Cell55949* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_59644((&gch_58059.zct), c);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	Cell55949* c;
	nimfr("nimGCunrefNoCycle", "gc.nim")
	nimln(246, "gc.nim");
	c = usrtocell_59673(p);
	nimln(248, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(249, "gc.nim");
		rtladdzct_61204(c);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(Ioerror4031*, neweio_219205)(NimStringDesc* msg) {
	Ioerror4031* result;
	NimStringDesc* LOC1;
	nimfr("newEIO", "streams.nim")
	result = 0;
	nimln(38, "streams.nim");
	result = (Ioerror4031*) newObj((&NTI16835), sizeof(Ioerror4031));
	(*result).Sup.Sup.Sup.m_type = (&NTI4031);
	nimln(39, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).Sup.Sup.message; (*result).Sup.Sup.message = copyStringRC1(msg);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
	return result;
}

N_NIMCALL(void, flush_219275)(Streamobj219227* s) {
	nimfr("flush", "streams.nim")
	nimln(64, "streams.nim");
	{
		if (!!((*s).flushimpl == 0)) goto LA3;
		(*s).flushimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_219291)(Streamobj219227* s) {
	nimfr("close", "streams.nim")
	nimln(68, "streams.nim");
	{
		if (!!((*s).closeimpl == 0)) goto LA3;
		(*s).closeimpl(s);
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, close_219307)(Streamobj219227* s, Streamobj219227* unused) {
	nimfr("close", "streams.nim")
	nimln(72, "streams.nim");
	(*s).closeimpl(s);
	popFrame();
}

N_NIMCALL(NIM_BOOL, atend_219317)(Streamobj219227* s) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(77, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, atend_219327)(Streamobj219227* s, Streamobj219227* unused) {
	NIM_BOOL result;
	nimfr("atEnd", "streams.nim")
	result = 0;
	nimln(82, "streams.nim");
	result = (*s).atendimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(void, setposition_219338)(Streamobj219227* s, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(86, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(void, setposition_219348)(Streamobj219227* s, Streamobj219227* unused, NI pos) {
	nimfr("setPosition", "streams.nim")
	nimln(90, "streams.nim");
	(*s).setpositionimpl(s, pos);
	popFrame();
}

N_NIMCALL(NI, getposition_219359)(Streamobj219227* s) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(94, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, getposition_219369)(Streamobj219227* s, Streamobj219227* unused) {
	NI result;
	nimfr("getPosition", "streams.nim")
	result = 0;
	nimln(98, "streams.nim");
	result = (*s).getpositionimpl(s);
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_219380)(Streamobj219227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(102, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NimStringDesc*, readall_219392)(Streamobj219227* s) {
	NimStringDesc* result;
	NI r;
	nimfr("readAll", "streams.nim")
	result = 0;
	nimln(107, "streams.nim");
	result = mnewString(((NI) 1000));
	nimln(108, "streams.nim");
	r = ((NI) 0);
	{
		nimln(109, "streams.nim");
		while (1) {
			NI readbytes;
			NI TMP920;
			NI TMP921;
			nimln(110, "streams.nim");
			if ((NU)(r) > (NU)(result->Sup.len)) raiseIndexError();
			readbytes = readdata_219380(s, ((void*) ((&result->data[r]))), ((NI) 1000));
			nimln(111, "streams.nim");
			{
				NI TMP919;
				if (!(readbytes < ((NI) 1000))) goto LA5;
				nimln(112, "streams.nim");
				TMP919 = addInt(r, readbytes);
				result = setLengthStr(result, ((NI)chckRange((NI)(TMP919), ((NI) 0), ((NI) IL64(9223372036854775807)))));
				nimln(113, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(114, "streams.nim");
			TMP920 = addInt(r, ((NI) 1000));
			r = (NI)(TMP920);
			nimln(115, "streams.nim");
			TMP921 = addInt(r, ((NI) 1000));
			result = setLengthStr(result, ((NI)chckRange((NI)(TMP921), ((NI) 0), ((NI) IL64(9223372036854775807)))));
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, readdata_219423)(Streamobj219227* s, Streamobj219227* unused, void* buffer, NI buflen) {
	NI result;
	nimfr("readData", "streams.nim")
	result = 0;
	nimln(120, "streams.nim");
	result = (*s).readdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(NI, peekdata_219436)(Streamobj219227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("peekData", "streams.nim")
	result = 0;
	nimln(125, "streams.nim");
	result = (*s).peekdataimpl(s, buffer, buflen);
	popFrame();
	return result;
}

N_NIMCALL(void, writedata_219448)(Streamobj219227* s, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(130, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, writedata_219459)(Streamobj219227* s, Streamobj219227* unused, void* buffer, NI buflen) {
	nimfr("writeData", "streams.nim")
	nimln(136, "streams.nim");
	(*s).writedataimpl(s, buffer, buflen);
	popFrame();
}

N_NIMCALL(void, write_219483)(Streamobj219227* s, NimStringDesc* x) {
	nimfr("write", "streams.nim")
	nimln(151, "streams.nim");
	writedata_219448(s, ((void*) (x->data)), (x ? x->Sup.len : 0));
	popFrame();
}

N_NIMCALL(void, writeln_219493)(Streamobj219227* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLn", "streams.nim")
	{
		NimStringDesc* str_219506;
		NI i_219510;
		str_219506 = 0;
		nimln(1965, "system.nim");
		i_219510 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP922;
				if (!(i_219510 < argsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_219510) >= (NU)(argsLen0)) raiseIndexError();
				str_219506 = args[i_219510];
				nimln(155, "streams.nim");
				write_219483(s, str_219506);
				nimln(1968, "system.nim");
				TMP922 = addInt(i_219510, ((NI) 1));
				i_219510 = (NI)(TMP922);
			} LA3: ;
		}
	}
	nimln(156, "streams.nim");
	write_219483(s, ((NimStringDesc*) &TMP923));
	popFrame();
}

N_NIMCALL(void, writeline_219526)(Streamobj219227* s, NimStringDesc** args, NI argsLen0) {
	nimfr("writeLine", "streams.nim")
	{
		NimStringDesc* str_219539;
		NI i_219543;
		str_219539 = 0;
		nimln(1965, "system.nim");
		i_219543 = ((NI) 0);
		{
			nimln(1966, "system.nim");
			while (1) {
				NI TMP924;
				if (!(i_219543 < argsLen0)) goto LA3;
				nimln(1967, "system.nim");
				if ((NU)(i_219543) >= (NU)(argsLen0)) raiseIndexError();
				str_219539 = args[i_219543];
				nimln(161, "streams.nim");
				write_219483(s, str_219539);
				nimln(1968, "system.nim");
				TMP924 = addInt(i_219543, ((NI) 1));
				i_219543 = (NI)(TMP924);
			} LA3: ;
		}
	}
	nimln(162, "streams.nim");
	write_219483(s, ((NimStringDesc*) &TMP923));
	popFrame();
}

N_NIMCALL(NIM_CHAR, readchar_219584)(Streamobj219227* s) {
	NIM_CHAR result;
	nimfr("readChar", "streams.nim")
	result = 0;
	nimln(177, "streams.nim");
	{
		NI LOC3;
		nimln(349, "system.nim");
		nimln(177, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_CHAR, peekchar_219595)(Streamobj219227* s) {
	NIM_CHAR result;
	nimfr("peekChar", "streams.nim")
	result = 0;
	nimln(182, "streams.nim");
	{
		NI LOC3;
		nimln(349, "system.nim");
		nimln(182, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) ((&result))), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		result = 0;
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, read_219611)(Streamobj219227* s, NIM_BOOL* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, readbool_219606)(Streamobj219227* s) {
	NIM_BOOL result;
	nimfr("readBool", "streams.nim")
	result = 0;
	nimln(186, "streams.nim");
	read_219611(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_219656)(Streamobj219227* s, NIM_BOOL* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, peekbool_219651)(Streamobj219227* s) {
	NIM_BOOL result;
	nimfr("peekBool", "streams.nim")
	result = 0;
	nimln(190, "streams.nim");
	peek_219656(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_219698)(Streamobj219227* s, NI8* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, readint8_219693)(Streamobj219227* s) {
	NI8 result;
	nimfr("readInt8", "streams.nim")
	result = 0;
	nimln(194, "streams.nim");
	read_219698(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_219743)(Streamobj219227* s, NI8* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 1));
		if (!!((LOC3 == ((NI) 1)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI8, peekint8_219738)(Streamobj219227* s) {
	NI8 result;
	nimfr("peekInt8", "streams.nim")
	result = 0;
	nimln(198, "streams.nim");
	peek_219743(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_219785)(Streamobj219227* s, NI16* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, readint16_219780)(Streamobj219227* s) {
	NI16 result;
	nimfr("readInt16", "streams.nim")
	result = 0;
	nimln(202, "streams.nim");
	read_219785(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_219830)(Streamobj219227* s, NI16* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 2));
		if (!!((LOC3 == ((NI) 2)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI16, peekint16_219825)(Streamobj219227* s) {
	NI16 result;
	nimfr("peekInt16", "streams.nim")
	result = 0;
	nimln(206, "streams.nim");
	peek_219830(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_219872)(Streamobj219227* s, NI32* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, readint32_219867)(Streamobj219227* s) {
	NI32 result;
	nimfr("readInt32", "streams.nim")
	result = 0;
	nimln(210, "streams.nim");
	read_219872(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_219917)(Streamobj219227* s, NI32* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI32, peekint32_219912)(Streamobj219227* s) {
	NI32 result;
	nimfr("peekInt32", "streams.nim")
	result = 0;
	nimln(214, "streams.nim");
	peek_219917(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_219959)(Streamobj219227* s, NI64* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, readint64_219954)(Streamobj219227* s) {
	NI64 result;
	nimfr("readInt64", "streams.nim")
	result = 0;
	nimln(218, "streams.nim");
	read_219959(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_220004)(Streamobj219227* s, NI64* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NI64, peekint64_219999)(Streamobj219227* s) {
	NI64 result;
	nimfr("peekInt64", "streams.nim")
	result = 0;
	nimln(222, "streams.nim");
	peek_220004(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_220046)(Streamobj219227* s, NF32* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, readfloat32_220041)(Streamobj219227* s) {
	NF32 result;
	nimfr("readFloat32", "streams.nim")
	result = 0;
	nimln(226, "streams.nim");
	read_220046(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_220091)(Streamobj219227* s, NF32* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 4));
		if (!!((LOC3 == ((NI) 4)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF32, peekfloat32_220086)(Streamobj219227* s) {
	NF32 result;
	nimfr("peekFloat32", "streams.nim")
	result = 0;
	nimln(230, "streams.nim");
	peek_220091(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, read_220133)(Streamobj219227* s, NF* result) {
	nimfr("read", "streams.nim")
	nimln(166, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(166, "streams.nim");
		LOC3 = 0;
		LOC3 = readdata_219380(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(167, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, readfloat64_220128)(Streamobj219227* s) {
	NF result;
	nimfr("readFloat64", "streams.nim")
	result = 0;
	nimln(234, "streams.nim");
	read_220133(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(void, peek_220175)(Streamobj219227* s, NF* result) {
	nimfr("peek", "streams.nim")
	nimln(171, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(171, "streams.nim");
		LOC3 = 0;
		LOC3 = peekdata_219436(s, ((void*) (result)), ((NI) 8));
		if (!!((LOC3 == ((NI) 8)))) goto LA4;
		nimln(172, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP925));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(NF, peekfloat64_220170)(Streamobj219227* s) {
	NF result;
	nimfr("peekFloat64", "streams.nim")
	result = 0;
	nimln(238, "streams.nim");
	peek_220175(s, (&result));
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readstr_220212)(Streamobj219227* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("readStr", "streams.nim")
	result = 0;
	nimln(243, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(244, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = readdata_219380(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(245, "streams.nim");
	{
		nimln(349, "system.nim");
		if (!!((L == length))) goto LA3;
		nimln(245, "streams.nim");
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, peekstr_220227)(Streamobj219227* s, NI length) {
	NimStringDesc* result;
	NI L;
	nimfr("peekStr", "streams.nim")
	result = 0;
	nimln(250, "streams.nim");
	result = mnewString(((NI)chckRange(length, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(251, "streams.nim");
	if ((NU)(((NI) 0)) > (NU)(result->Sup.len)) raiseIndexError();
	L = peekdata_219436(s, ((void*) ((&result->data[((NI) 0)]))), length);
	nimln(252, "streams.nim");
	{
		nimln(349, "system.nim");
		if (!!((L == length))) goto LA3;
		nimln(252, "streams.nim");
		result = setLengthStr(result, ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, readline_220242)(Streamobj219227* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr("readLine", "streams.nim")
{	result = 0;
	nimln(261, "streams.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln(262, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(263, "streams.nim");
			c = readchar_219584(s);
			nimln(264, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(265, "streams.nim");
				c = readchar_219584(s);
				nimln(266, "streams.nim");
				goto LA1;
			}
			goto LA3;
			LA5: ;
			{
				nimln(267, "streams.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA8;
				goto LA1;
			}
			goto LA3;
			LA8: ;
			{
				nimln(268, "streams.nim");
				if (!((NU8)(c) == (NU8)(0))) goto LA11;
				nimln(269, "streams.nim");
				{
					nimln(357, "system.nim");
					nimln(269, "streams.nim");
					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15;
					goto LA1;
				}
				goto LA13;
				LA15: ;
				{
					nimln(270, "streams.nim");
					result = NIM_FALSE;
					goto BeforeRet;
				}
				LA13: ;
			}
			goto LA3;
			LA11: ;
			LA3: ;
			nimln(271, "streams.nim");
			(*line) = addChar((*line), c);
		}
	} LA1: ;
	nimln(272, "streams.nim");
	result = NIM_TRUE;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(void, pushSafePoint)(TSafePoint* s) {
	(*s).hasRaiseAction = NIM_FALSE;
	(*s).prev = exchandler_27443;
	exchandler_27443 = s;
}

static N_INLINE(void, popSafePoint)(void) {
	exchandler_27443 = (*exchandler_27443).prev;
}

static N_INLINE(void, setFrame)(TFrame* s) {
	frameptr_27442 = s;
}

N_NIMCALL(NIM_BOOL, peekline_220264)(Streamobj219227* s, NimStringDesc** line) {
	NIM_BOOL volatile result;
	NI pos;
	TSafePoint TMP926;
	nimfr("peekLine", "streams.nim")
	result = 0;
	nimln(281, "streams.nim");
	pos = getposition_219359(s);
	nimln(282, "streams.nim");
	pushSafePoint(&TMP926);
	TMP926.status = setjmp(TMP926.context);
	if (TMP926.status == 0) {
		nimln(283, "streams.nim");
		result = readline_220242(s, line);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(282, "streams.nim");
		setposition_219338(s, pos);
	}
	if (TMP926.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, readline_220277)(Streamobj219227* s) {
	NimStringDesc* result;
	nimfr("readLine", "streams.nim")
	result = 0;
	nimln(288, "streams.nim");
	result = copyString(((NimStringDesc*) &TMP927));
	{
		nimln(289, "streams.nim");
		while (1) {
			NIM_CHAR c;
			nimln(290, "streams.nim");
			c = readchar_219584(s);
			nimln(291, "streams.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5;
				nimln(292, "streams.nim");
				c = readchar_219584(s);
				nimln(293, "streams.nim");
				goto LA1;
			}
			LA5: ;
			nimln(294, "streams.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = ((NU8)(c) == (NU8)(10));
				if (LOC9) goto LA10;
				LOC9 = ((NU8)(c) == (NU8)(0));
				LA10: ;
				if (!LOC9) goto LA11;
				nimln(295, "streams.nim");
				goto LA1;
			}
			goto LA7;
			LA11: ;
			{
				nimln(297, "streams.nim");
				result = addChar(result, c);
			}
			LA7: ;
		}
	} LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, peekline_220297)(Streamobj219227* s) {
	NimStringDesc* volatile result;
	NI pos;
	TSafePoint TMP928;
	nimfr("peekLine", "streams.nim")
	result = 0;
	nimln(302, "streams.nim");
	pos = getposition_219359(s);
	nimln(303, "streams.nim");
	pushSafePoint(&TMP928);
	TMP928.status = setjmp(TMP928.context);
	if (TMP928.status == 0) {
		nimln(304, "streams.nim");
		result = readline_220277(s);
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(303, "streams.nim");
		setposition_219338(s, pos);
	}
	if (TMP928.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, ssatend_220322)(Streamobj219227* s_220324) {
	NIM_BOOL result;
	Stringstreamobj220311* s;
	nimfr("ssAtEnd", "streams.nim")
{	result = 0;
	nimln(315, "streams.nim");
	if (s_220324) chckObj((*s_220324).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220324));
	nimln(316, "streams.nim");
	nimln(353, "system.nim");
	nimln(316, "streams.nim");
	result = (((*s).data ? (*s).data->Sup.len : 0) <= (*s).pos);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sssetposition_220333)(Streamobj219227* s_220335, NI pos) {
	Stringstreamobj220311* s;
	nimfr("ssSetPosition", "streams.nim")
	nimln(319, "streams.nim");
	if (s_220335) chckObj((*s_220335).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220335));
	nimln(320, "streams.nim");
	(*s).pos = clamp_220339(pos, ((NI) 0), ((*s).data ? (*s).data->Sup.len : 0));
	popFrame();
}

N_NIMCALL(NI, ssgetposition_220358)(Streamobj219227* s_220360) {
	NI result;
	Stringstreamobj220311* s;
	nimfr("ssGetPosition", "streams.nim")
{	result = 0;
	nimln(323, "streams.nim");
	if (s_220360) chckObj((*s_220360).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220360));
	nimln(324, "streams.nim");
	result = (*s).pos;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, ssreaddata_220369)(Streamobj219227* s_220371, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj220311* s;
	NI TMP931;
	nimfr("ssReadData", "streams.nim")
	result = 0;
	nimln(327, "streams.nim");
	if (s_220371) chckObj((*s_220371).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220371));
	nimln(328, "streams.nim");
	TMP931 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP931)) ? buflen : (NI)(TMP931));
	nimln(329, "streams.nim");
	{
		NI TMP932;
		nimln(357, "system.nim");
		if (!(((NI) 0) < result)) goto LA3;
		nimln(330, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(331, "streams.nim");
		TMP932 = addInt((*s).pos, result);
		(*s).pos = (NI)(TMP932);
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, sspeekdata_220396)(Streamobj219227* s_220398, void* buffer, NI buflen) {
	NI result;
	Stringstreamobj220311* s;
	NI TMP933;
	nimfr("ssPeekData", "streams.nim")
	result = 0;
	nimln(334, "streams.nim");
	if (s_220398) chckObj((*s_220398).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220398));
	nimln(335, "streams.nim");
	TMP933 = subInt(((*s).data ? (*s).data->Sup.len : 0), (*s).pos);
	result = ((buflen <= (NI)(TMP933)) ? buflen : (NI)(TMP933));
	nimln(336, "streams.nim");
	{
		nimln(357, "system.nim");
		if (!(((NI) 0) < result)) goto LA3;
		nimln(337, "streams.nim");
		if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
		memcpy(buffer, ((void*) ((&(*s).data->data[(*s).pos]))), ((NI)chckRange(result, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA3: ;
	popFrame();
	return result;
}

N_NIMCALL(void, sswritedata_220414)(Streamobj219227* s_220416, void* buffer, NI buflen) {
	Stringstreamobj220311* s;
	NI TMP936;
	nimfr("ssWriteData", "streams.nim")
{	nimln(340, "streams.nim");
	if (s_220416) chckObj((*s_220416).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220416));
	nimln(341, "streams.nim");
	{
		if (!(buflen <= ((NI) 0))) goto LA3;
		nimln(342, "streams.nim");
		goto BeforeRet;
	}
	LA3: ;
	nimln(343, "streams.nim");
	{
		NI TMP934;
		NI TMP935;
		nimln(357, "system.nim");
		nimln(343, "streams.nim");
		TMP934 = addInt((*s).pos, buflen);
		if (!(((*s).data ? (*s).data->Sup.len : 0) < (NI)(TMP934))) goto LA7;
		nimln(344, "streams.nim");
		TMP935 = addInt((*s).pos, buflen);
		(*s).data = setLengthStr((*s).data, ((NI)chckRange((NI)(TMP935), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	}
	LA7: ;
	nimln(345, "streams.nim");
	if ((NU)((*s).pos) > (NU)((*s).data->Sup.len)) raiseIndexError();
	memcpy(((void*) ((&(*s).data->data[(*s).pos]))), buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln(346, "streams.nim");
	TMP936 = addInt((*s).pos, buflen);
	(*s).pos = (NI)(TMP936);
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, ssclose_220436)(Streamobj219227* s_220438) {
	Stringstreamobj220311* s;
	NimStringDesc* LOC1;
	nimfr("ssClose", "streams.nim")
	nimln(349, "streams.nim");
	if (s_220438) chckObj((*s_220438).Sup.m_type, (&NTI220311));
	s = ((Stringstreamobj220311*) (s_220438));
	nimln(350, "streams.nim");
	LOC1 = 0;
	LOC1 = (*s).data; (*s).data = copyStringRC1(NIM_NIL);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP937)(void* p, NI op) {
	Stringstreamobj220311* a;
	a = (Stringstreamobj220311*)p;
	nimGCvisit((void*)(*a).data, op);
}

N_NIMCALL(Stringstreamobj220311*, newstringstream_220446)(NimStringDesc* s) {
	Stringstreamobj220311* result;
	NimStringDesc* LOC1;
	nimfr("newStringStream", "streams.nim")
	result = 0;
	nimln(354, "streams.nim");
	result = (Stringstreamobj220311*) newObj((&NTI220309), sizeof(Stringstreamobj220311));
	(*result).Sup.Sup.m_type = (&NTI220311);
	nimln(355, "streams.nim");
	LOC1 = 0;
	LOC1 = (*result).data; (*result).data = copyStringRC1(s);
	if (LOC1) nimGCunrefNoCycle(LOC1);
	nimln(356, "streams.nim");
	(*result).pos = ((NI) 0);
	nimln(357, "streams.nim");
	(*result).Sup.closeimpl = ssclose_220436;
	nimln(358, "streams.nim");
	(*result).Sup.atendimpl = ssatend_220322;
	nimln(359, "streams.nim");
	(*result).Sup.setpositionimpl = sssetposition_220333;
	nimln(360, "streams.nim");
	(*result).Sup.getpositionimpl = ssgetposition_220358;
	nimln(361, "streams.nim");
	(*result).Sup.readdataimpl = ssreaddata_220369;
	nimln(362, "streams.nim");
	(*result).Sup.peekdataimpl = sspeekdata_220396;
	nimln(363, "streams.nim");
	(*result).Sup.writedataimpl = sswritedata_220414;
	popFrame();
	return result;
}

N_NIMCALL(void, fsclose_220471)(Streamobj219227* s) {
	nimfr("fsClose", "streams.nim")
	nimln(374, "streams.nim");
	{
		nimln(349, "system.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI220467));
		if (!!(((*((Filestreamobj220467*) (s))).f == NIM_NIL))) goto LA3;
		nimln(375, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI220467));
		fclose((*((Filestreamobj220467*) (s))).f);
		nimln(376, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI220467));
		(*((Filestreamobj220467*) (s))).f = NIM_NIL;
	}
	LA3: ;
	popFrame();
}

N_NIMCALL(void, fsflush_220489)(Streamobj219227* s) {
	nimfr("fsFlush", "streams.nim")
	nimln(377, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI220467));
	fflush((*((Filestreamobj220467*) (s))).f);
	popFrame();
}

N_NIMCALL(NIM_BOOL, fsatend_220495)(Streamobj219227* s) {
	NIM_BOOL result;
	nimfr("fsAtEnd", "streams.nim")
{	result = 0;
	nimln(378, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI220467));
	result = endoffile_16860((*((Filestreamobj220467*) (s))).f);
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(void, fssetposition_220502)(Streamobj219227* s, NI pos) {
	nimfr("fsSetPosition", "streams.nim")
	nimln(379, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI220467));
	setfilepos_16987((*((Filestreamobj220467*) (s))).f, ((NI64) (pos)));
	popFrame();
}

N_NIMCALL(NI, fsgetposition_220509)(Streamobj219227* s) {
	NI result;
	NI64 LOC1;
	nimfr("fsGetPosition", "streams.nim")
{	result = 0;
	nimln(380, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI220467));
	LOC1 = 0;
	LOC1 = getfilepos_16991((*((Filestreamobj220467*) (s))).f);
	result = ((NI) (LOC1));
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

N_NIMCALL(NI, fsreaddata_220517)(Streamobj219227* s, void* buffer, NI buflen) {
	NI result;
	nimfr("fsReadData", "streams.nim")
	result = 0;
	nimln(383, "streams.nim");
	if (s) chckObj((*s).Sup.m_type, (&NTI220467));
	result = readbuffer_16960((*((Filestreamobj220467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
	return result;
}

N_NIMCALL(NI, fspeekdata_220526)(Streamobj219227* s, void* buffer, NI buflen) {
	NI volatile result;
	NI pos;
	TSafePoint TMP938;
	nimfr("fsPeekData", "streams.nim")
	result = 0;
	nimln(386, "streams.nim");
	pos = fsgetposition_220509(s);
	nimln(387, "streams.nim");
	pushSafePoint(&TMP938);
	TMP938.status = setjmp(TMP938.context);
	if (TMP938.status == 0) {
		nimln(388, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI220467));
		result = readbuffer_16960((*((Filestreamobj220467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		popSafePoint();
	}
	else {
		popSafePoint();
		setFrame((TFrame*)&FR);
	}
	{
		nimln(387, "streams.nim");
		fssetposition_220502(s, pos);
	}
	if (TMP938.status != 0) reraiseException();
	popFrame();
	return result;
}

N_NIMCALL(void, fswritedata_220536)(Streamobj219227* s, void* buffer, NI buflen) {
	nimfr("fsWriteData", "streams.nim")
	nimln(391, "streams.nim");
	{
		NI LOC3;
		Ioerror4031* LOC6;
		nimln(349, "system.nim");
		nimln(391, "streams.nim");
		if (s) chckObj((*s).Sup.m_type, (&NTI220467));
		LOC3 = 0;
		LOC3 = writebuffer_16982((*((Filestreamobj220467*) (s))).f, buffer, ((NI)chckRange(buflen, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		if (!!((LOC3 == buflen))) goto LA4;
		nimln(392, "streams.nim");
		LOC6 = 0;
		LOC6 = neweio_219205(((NimStringDesc*) &TMP939));
		raiseException((Exception*)LOC6, "IOError");
	}
	LA4: ;
	popFrame();
}
N_NIMCALL(void, TMP940)(void* p, NI op) {
	Filestreamobj220467* a;
	a = (Filestreamobj220467*)p;
}

N_NIMCALL(Filestreamobj220467*, newfilestream_220544)(FILE* f) {
	Filestreamobj220467* result;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	nimln(396, "streams.nim");
	result = (Filestreamobj220467*) newObj((&NTI220465), sizeof(Filestreamobj220467));
	(*result).Sup.Sup.m_type = (&NTI220467);
	nimln(397, "streams.nim");
	(*result).f = f;
	nimln(398, "streams.nim");
	(*result).Sup.closeimpl = fsclose_220471;
	nimln(399, "streams.nim");
	(*result).Sup.atendimpl = fsatend_220495;
	nimln(400, "streams.nim");
	(*result).Sup.setpositionimpl = fssetposition_220502;
	nimln(401, "streams.nim");
	(*result).Sup.getpositionimpl = fsgetposition_220509;
	nimln(402, "streams.nim");
	(*result).Sup.readdataimpl = fsreaddata_220517;
	nimln(403, "streams.nim");
	(*result).Sup.peekdataimpl = fspeekdata_220526;
	nimln(404, "streams.nim");
	(*result).Sup.writedataimpl = fswritedata_220536;
	nimln(405, "streams.nim");
	(*result).Sup.flushimpl = fsflush_220489;
	popFrame();
	return result;
}

N_NIMCALL(Filestreamobj220467*, newfilestream_220559)(NimStringDesc* filename, NU8 mode) {
	Filestreamobj220467* result;
	FILE* f;
	nimfr("newFileStream", "streams.nim")
	result = 0;
	f = 0;
	nimln(412, "streams.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = open_16803(&f, filename, mode, ((NI) -1));
		if (!LOC3) goto LA4;
		result = newfilestream_220544(f);
	}
	LA4: ;
	popFrame();
	return result;
}
N_NIMCALL(void, TMP1166)(void* p, NI op) {
	Streamobj219227* a;
	a = (Streamobj219227*)p;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void) {
	nimfr("streams", "streams.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void) {
static TNimNode* TMP929[8];
static TNimNode* TMP930[2];
static TNimNode TMP917[13];
NTI219227.size = sizeof(Streamobj219227);
NTI219227.kind = 17;
NTI219227.base = (&NTI4011);
NTI219227.flags = 1;
TMP929[0] = &TMP917[1];
NTI219228.size = sizeof(TY219228);
NTI219228.kind = 25;
NTI219228.base = 0;
NTI219228.flags = 3;
TMP917[1].kind = 1;
TMP917[1].offset = offsetof(Streamobj219227, closeimpl);
TMP917[1].typ = (&NTI219228);
TMP917[1].name = "closeImpl";
TMP929[1] = &TMP917[2];
NTI219232.size = sizeof(TY219232);
NTI219232.kind = 25;
NTI219232.base = 0;
NTI219232.flags = 3;
TMP917[2].kind = 1;
TMP917[2].offset = offsetof(Streamobj219227, atendimpl);
TMP917[2].typ = (&NTI219232);
TMP917[2].name = "atEndImpl";
TMP929[2] = &TMP917[3];
NTI219236.size = sizeof(TY219236);
NTI219236.kind = 25;
NTI219236.base = 0;
NTI219236.flags = 3;
TMP917[3].kind = 1;
TMP917[3].offset = offsetof(Streamobj219227, setpositionimpl);
TMP917[3].typ = (&NTI219236);
TMP917[3].name = "setPositionImpl";
TMP929[3] = &TMP917[4];
NTI219241.size = sizeof(TY219241);
NTI219241.kind = 25;
NTI219241.base = 0;
NTI219241.flags = 3;
TMP917[4].kind = 1;
TMP917[4].offset = offsetof(Streamobj219227, getpositionimpl);
TMP917[4].typ = (&NTI219241);
TMP917[4].name = "getPositionImpl";
TMP929[4] = &TMP917[5];
NTI219245.size = sizeof(TY219245);
NTI219245.kind = 25;
NTI219245.base = 0;
NTI219245.flags = 3;
TMP917[5].kind = 1;
TMP917[5].offset = offsetof(Streamobj219227, readdataimpl);
TMP917[5].typ = (&NTI219245);
TMP917[5].name = "readDataImpl";
TMP929[5] = &TMP917[6];
NTI219251.size = sizeof(TY219251);
NTI219251.kind = 25;
NTI219251.base = 0;
NTI219251.flags = 3;
TMP917[6].kind = 1;
TMP917[6].offset = offsetof(Streamobj219227, peekdataimpl);
TMP917[6].typ = (&NTI219251);
TMP917[6].name = "peekDataImpl";
TMP929[6] = &TMP917[7];
NTI219257.size = sizeof(TY219257);
NTI219257.kind = 25;
NTI219257.base = 0;
NTI219257.flags = 3;
TMP917[7].kind = 1;
TMP917[7].offset = offsetof(Streamobj219227, writedataimpl);
TMP917[7].typ = (&NTI219257);
TMP917[7].name = "writeDataImpl";
TMP929[7] = &TMP917[8];
NTI219263.size = sizeof(TY219263);
NTI219263.kind = 25;
NTI219263.base = 0;
NTI219263.flags = 3;
TMP917[8].kind = 1;
TMP917[8].offset = offsetof(Streamobj219227, flushimpl);
TMP917[8].typ = (&NTI219263);
TMP917[8].name = "flushImpl";
TMP917[0].len = 8; TMP917[0].kind = 2; TMP917[0].sons = &TMP929[0];
NTI219227.node = &TMP917[0];
NTI220311.size = sizeof(Stringstreamobj220311);
NTI220311.kind = 17;
NTI220311.base = (&NTI219227);
TMP930[0] = &TMP917[10];
TMP917[10].kind = 1;
TMP917[10].offset = offsetof(Stringstreamobj220311, data);
TMP917[10].typ = (&NTI149);
TMP917[10].name = "data";
TMP930[1] = &TMP917[11];
TMP917[11].kind = 1;
TMP917[11].offset = offsetof(Stringstreamobj220311, pos);
TMP917[11].typ = (&NTI108);
TMP917[11].name = "pos";
TMP917[9].len = 2; TMP917[9].kind = 2; TMP917[9].sons = &TMP930[0];
NTI220311.node = &TMP917[9];
NTI220309.size = sizeof(Stringstreamobj220311*);
NTI220309.kind = 22;
NTI220309.base = (&NTI220311);
NTI220309.marker = TMP937;
NTI220467.size = sizeof(Filestreamobj220467);
NTI220467.kind = 17;
NTI220467.base = (&NTI219227);
NTI220467.flags = 1;
TMP917[12].kind = 1;
TMP917[12].offset = offsetof(Filestreamobj220467, f);
TMP917[12].typ = (&NTI16404);
TMP917[12].name = "f";
NTI220467.node = &TMP917[12];
NTI220465.size = sizeof(Filestreamobj220467*);
NTI220465.kind = 22;
NTI220465.base = (&NTI220467);
NTI220465.marker = TMP940;
NTI219225.size = sizeof(Streamobj219227*);
NTI219225.kind = 22;
NTI219225.base = (&NTI219227);
NTI219225.marker = TMP1166;
}

