/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_oids.o src/nimcache/stdlib_oids.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <time.h>
#include <stdlib.h>
typedef struct Oid142005 Oid142005;
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct  Oid142005  {
NI32 time;
NI32 fuzz;
NI32 count;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
N_NIMCALL(NIM_BOOL, HEX3DHEX3D_142016)(Oid142005 oid1, Oid142005 oid2);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NI, hexbyte_142027)(NIM_CHAR hex);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(Oid142005, parseoid_142092)(NCSTRING str);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, oidtostring_142122)(Oid142005 oid, NCSTRING str_142125);
N_NOINLINE(void, raiseIndexError)(void);
N_NIMCALL(NimStringDesc*, HEX24_142166)(Oid142005 oid);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(Oid142005, genoid_142183)(void);
static N_INLINE(NI, atomicinc_18001)(NI* memloc, NI x);
static N_INLINE(void, bigendian32_141090)(void* outp, void* inp);
N_NIMCALL(void, swapendian32_141025)(void* outp, void* inp);
N_NIMCALL(time_t, generatedtime_142217)(Oid142005 oid);
STRING_LITERAL(TMP543, "0123456789abcdef", 16);
extern TFrame* frameptr_20842;
NI incr_142176;
NI32 fuzz_142177;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(NIM_BOOL, HEX3DHEX3D_142016)(Oid142005 oid1, Oid142005 oid2) {
	NIM_BOOL result;
	NIM_BOOL LOC1;
	NIM_BOOL LOC2;
	nimfr("==", "oids.nim")
{	result = 0;
	nimln(30, "oids.nim");
	LOC1 = 0;
	LOC2 = 0;
	LOC2 = (oid1.time == oid2.time);
	if (!(LOC2)) goto LA3;
	LOC2 = (oid1.fuzz == oid2.fuzz);
	LA3: ;
	LOC1 = LOC2;
	if (!(LOC1)) goto LA4;
	LOC1 = (oid1.count == oid2.count);
	LA4: ;
	result = LOC1;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(NI, hexbyte_142027)(NIM_CHAR hex) {
	NI result;
	nimfr("hexbyte", "oids.nim")
	result = 0;
	nimln(33, "oids.nim");
	switch (((NU8)(hex))) {
	case 48 ... 57:
	{
		NI TMP533;
		nimln(34, "oids.nim");
		TMP533 = subInt(((NI) (((NU8)(hex)))), ((NI) 48));
		result = ((NI) ((NI)(TMP533)));
	}
	break;
	case 97 ... 102:
	{
		NI TMP534;
		NI TMP535;
		nimln(35, "oids.nim");
		TMP534 = subInt(((NI) (((NU8)(hex)))), ((NI) 97));
		TMP535 = addInt(((NI) ((NI)(TMP534))), ((NI) 10));
		result = ((NI) ((NI)(TMP535)));
	}
	break;
	case 65 ... 70:
	{
		NI TMP536;
		NI TMP537;
		nimln(36, "oids.nim");
		TMP536 = subInt(((NI) (((NU8)(hex)))), ((NI) 65));
		TMP537 = addInt(((NI) ((NI)(TMP536))), ((NI) 10));
		result = ((NI) ((NI)(TMP537)));
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(Oid142005, parseoid_142092)(NCSTRING str) {
	Oid142005 result;
	NCSTRING bytes;
	NI i;
	nimfr("parseOid", "oids.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(41, "oids.nim");
	bytes = ((NCSTRING) ((&result.time)));
	nimln(42, "oids.nim");
	i = ((NI) 0);
	{
		nimln(43, "oids.nim");
		while (1) {
			NI TMP538;
			NI LOC3;
			NI TMP539;
			NI TMP540;
			NI LOC4;
			NI TMP541;
			if (!(i < ((NI) 12))) goto LA2;
			nimln(44, "oids.nim");
			TMP538 = mulInt(((NI) 2), i);
			LOC3 = 0;
			LOC3 = hexbyte_142027(str[(NI)(TMP538)]);
			TMP539 = mulInt(((NI) 2), i);
			TMP540 = addInt((NI)(TMP539), ((NI) 1));
			LOC4 = 0;
			LOC4 = hexbyte_142027(str[(NI)(TMP540)]);
			bytes[i] = ((NIM_CHAR) (((NI)chckRange((NI)((NI)((NU64)(LOC3) << (NU64)(((NI) 4))) | LOC4), ((NI) 0), ((NI) 255)))));
			nimln(45, "oids.nim");
			TMP541 = addInt(i, ((NI) 1));
			i = (NI)(TMP541);
		} LA2: ;
	}
	popFrame();
	return result;
}

N_NIMCALL(void, oidtostring_142122)(Oid142005 oid, NCSTRING str_142125) {
	NCSTRING str;
	Oid142005 o;
	NCSTRING bytes;
	NI i;
	nimfr("oidToString", "oids.nim")
	nimln(50, "oids.nim");
	str = str_142125;
	nimln(51, "oids.nim");
	o = oid;
	nimln(52, "oids.nim");
	bytes = ((NCSTRING) ((&o)));
	nimln(53, "oids.nim");
	i = ((NI) 0);
	{
		nimln(54, "oids.nim");
		while (1) {
			NI b;
			NI TMP542;
			NI TMP544;
			NI TMP545;
			NI TMP546;
			if (!(i < ((NI) 12))) goto LA2;
			nimln(55, "oids.nim");
			b = ((NU8)(bytes[i]));
			nimln(56, "oids.nim");
			TMP542 = mulInt(((NI) 2), i);
			if ((NU)((NI)((NU64)((NI)(((NI) (b)) & ((NI) 240))) >> (NU64)(((NI) 4)))) > (NU)(((NimStringDesc*) &TMP543)->Sup.len)) raiseIndexError();
			str[(NI)(TMP542)] = ((NimStringDesc*) &TMP543)->data[(NI)((NU64)((NI)(((NI) (b)) & ((NI) 240))) >> (NU64)(((NI) 4)))];
			nimln(57, "oids.nim");
			TMP544 = mulInt(((NI) 2), i);
			TMP545 = addInt((NI)(TMP544), ((NI) 1));
			if ((NU)((NI)(((NI) (b)) & ((NI) 15))) > (NU)(((NimStringDesc*) &TMP543)->Sup.len)) raiseIndexError();
			str[(NI)(TMP545)] = ((NimStringDesc*) &TMP543)->data[(NI)(((NI) (b)) & ((NI) 15))];
			nimln(58, "oids.nim");
			TMP546 = addInt(i, ((NI) 1));
			i = (NI)(TMP546);
		} LA2: ;
	}
	nimln(59, "oids.nim");
	str[((NI) 24)] = 0;
	popFrame();
}

N_NIMCALL(NimStringDesc*, HEX24_142166)(Oid142005 oid) {
	NimStringDesc* result;
	nimfr("$", "oids.nim")
	result = 0;
	nimln(62, "oids.nim");
	result = mnewString(((NI) 24));
	nimln(63, "oids.nim");
	oidtostring_142122(oid, result->data);
	popFrame();
	return result;
}

static N_INLINE(NI, atomicinc_18001)(NI* memloc, NI x) {
	NI result;
	result = 0;
	(*memloc) += x;
	result = (*memloc);
	return result;
}

static N_INLINE(void, bigendian32_141090)(void* outp, void* inp) {
	nimfr("bigEndian32", "endians.nim")
	nimln(58, "endians.nim");
	swapendian32_141025(outp, inp);
	popFrame();
}

N_NIMCALL(Oid142005, genoid_142183)(void) {
	Oid142005 result;
	int t;
	NI32 i;
	NI LOC1;
	nimfr("genOid", "oids.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(75, "oids.nim");
	t = time(NIM_NIL);
	nimln(77, "oids.nim");
	i = ((NI32)chckRange(incr_142176, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)));
	nimln(78, "oids.nim");
	LOC1 = 0;
	LOC1 = atomicinc_18001((&incr_142176), ((NI) 1));
	nimln(80, "oids.nim");
	{
		if (!(fuzz_142177 == ((NI32) 0))) goto LA4;
		nimln(82, "oids.nim");
		srand(t);
		nimln(83, "oids.nim");
		fuzz_142177 = rand();
	}
	LA4: ;
	nimln(84, "oids.nim");
	bigendian32_141090(((void*) ((&result.time))), ((void*) ((&t))));
	nimln(85, "oids.nim");
	result.fuzz = fuzz_142177;
	nimln(86, "oids.nim");
	bigendian32_141090(((void*) ((&result.count))), ((void*) ((&i))));
	popFrame();
	return result;
}

N_NIMCALL(time_t, generatedtime_142217)(Oid142005 oid) {
	time_t result;
	NI32 tmp;
	NI32 dummy;
	nimfr("generatedTime", "oids.nim")
	result = 0;
	tmp = 0;
	nimln(91, "oids.nim");
	dummy = oid.time;
	nimln(92, "oids.nim");
	bigendian32_141090(((void*) ((&tmp))), ((void*) ((&dummy))));
	nimln(93, "oids.nim");
	result = ((time_t) (tmp));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_oidsInit000)(void) {
	nimfr("oids", "oids.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_oidsDatInit000)(void) {
}

