/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_threadpool.o src/nimcache/stdlib_threadpool.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/types.h>
#include <string.h>
#include <pthread.h>
typedef struct Semaphore154008 Semaphore154008;
typedef struct Barrier Barrier;
typedef struct Flowvarbaseobj154247 Flowvarbaseobj154247;
typedef struct TNimObject TNimObject;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct Awaitinfo154243 Awaitinfo154243;
typedef struct Worker154257 Worker154257;
typedef struct Tofreequeue154253 Tofreequeue154253;
typedef struct Cell55949 Cell55949;
typedef struct Cellseq55965 Cellseq55965;
typedef struct Gcheap58018 Gcheap58018;
typedef struct Gcstack58016 Gcstack58016;
typedef struct Cellset55961 Cellset55961;
typedef struct Pagedesc55957 Pagedesc55957;
typedef struct Memregion37891 Memregion37891;
typedef struct Smallchunk37843 Smallchunk37843;
typedef struct Llchunk37885 Llchunk37885;
typedef struct Bigchunk37845 Bigchunk37845;
typedef struct Intset37817 Intset37817;
typedef struct Trunk37813 Trunk37813;
typedef struct Avlnode37889 Avlnode37889;
typedef struct Gcstat58014 Gcstat58014;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Thread155620 Thread155620;
typedef struct Gcthread21406 Gcthread21406;
typedef struct Threadpoolstate152207 Threadpoolstate152207;
typedef struct Flowvarobj250295 Flowvarobj250295;
typedef struct Basechunk37841 Basechunk37841;
typedef struct Freecell37833 Freecell37833;
struct  Semaphore154008  {
pthread_cond_t c;
pthread_mutex_t L;
NI counter;
};
typedef NU8 TY154102[24];
struct  Barrier  {
NI entered;
Semaphore154008 cv;
NI left;
TY154102 cacheAlign2;
NIM_BOOL interest;
};
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimObject  {
TNimType* m_type;
};
struct  Flowvarbaseobj154247  {
  TNimObject Sup;
NIM_BOOL ready;
NIM_BOOL usessemaphore;
NIM_BOOL awaited;
Semaphore154008 cv;
Awaitinfo154243* ai;
NI idx;
void* data;
void* owner;
};
typedef N_NIMCALL_PTR(void, Workerproc154255) (void* thread, void* args);
typedef void* TY154285[128];
struct  Tofreequeue154253  {
NI len;
pthread_mutex_t lock;
Semaphore154008 empty;
TY154285 data;
};
struct  Worker154257  {
Semaphore154008 taskarrived;
Semaphore154008 taskstarted;
Workerproc154255 f;
void* data;
NIM_BOOL ready;
NIM_BOOL initialized;
NIM_BOOL shutdown;
Tofreequeue154253 q;
Semaphore154008 readyfortask;
};
struct  Cell55949  {
NI refcount;
TNimType* typ;
};
struct  Cellseq55965  {
NI len;
NI cap;
Cell55949** d;
};
struct  Cellset55961  {
NI counter;
NI max;
Pagedesc55957* head;
Pagedesc55957** data;
};
typedef Smallchunk37843* TY37906[512];
typedef Trunk37813* Trunkbuckets37815[256];
struct  Intset37817  {
Trunkbuckets37815 data;
};
struct  Memregion37891  {
NI minlargeobj;
NI maxlargeobj;
TY37906 freesmallchunks;
Llchunk37885* llmem;
NI currmem;
NI maxmem;
NI freemem;
NI lastsize;
Bigchunk37845* freechunkslist;
Intset37817 chunkstarts;
Avlnode37889* root;
Avlnode37889* deleted;
Avlnode37889* last;
Avlnode37889* freeavlnodes;
};
struct  Gcstat58014  {
NI stackscans;
NI cyclecollections;
NI maxthreshold;
NI maxstacksize;
NI maxstackcells;
NI cycletablesize;
NI64 maxpause;
};
struct  Gcheap58018  {
Gcstack58016* stack;
void* stackbottom;
NI cyclethreshold;
Cellseq55965 zct;
Cellseq55965 decstack;
Cellset55961 cycleroots;
Cellseq55965 tempstack;
NI recgclock;
Memregion37891 region;
Gcstat58014 stat;
};
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Awaitinfo154243  {
Semaphore154008 cv;
NI idx;
};
struct  Gcthread21406  {
pthread_t sys;
};
typedef N_NIMCALL_PTR(void, TY155630) (Worker154257* m_155627);
struct  Thread155620  {
  Gcthread21406 Sup;
TY155630 datafn;
Worker154257* data;
};
typedef Thread155620 TY155633[256];
typedef Worker154257 TY155636[256];
typedef Thread155620 TY155642[32];
typedef Worker154257 TY155645[32];
typedef N_NIMCALL_PTR(void, TY156014) (Worker154257* arg_156016);
struct  Threadpoolstate152207  {
NI calls;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct  Flowvarobj250295  {
  Flowvarbaseobj154247 Sup;
NimStringDesc* blob;
};
struct  Gcstack58016  {
Gcstack58016* prev;
Gcstack58016* next;
void* starts;
void* pos;
NI maxstacksize;
};
typedef NI TY37822[8];
struct  Pagedesc55957  {
Pagedesc55957* next;
NI key;
TY37822 bits;
};
struct  Basechunk37841  {
NI prevsize;
NI size;
NIM_BOOL used;
};
struct  Smallchunk37843  {
  Basechunk37841 Sup;
Smallchunk37843* next;
Smallchunk37843* prev;
Freecell37833* freelist;
NI free;
NI acc;
NF data;
};
struct  Llchunk37885  {
NI size;
NI acc;
Llchunk37885* next;
};
struct  Bigchunk37845  {
  Basechunk37841 Sup;
Bigchunk37845* next;
Bigchunk37845* prev;
NI align;
NF data;
};
struct  Trunk37813  {
Trunk37813* next;
NI key;
TY37822 bits;
};
typedef Avlnode37889* TY37896[2];
struct  Avlnode37889  {
TY37896 link;
NI key;
NI upperbound;
NI level;
};
struct  Freecell37833  {
Freecell37833* next;
NI zerofield;
};
N_NIMCALL(Semaphore154008, createsemaphore_154015)(void);
static N_INLINE(void, initcond_153319)(pthread_cond_t* cond);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_30201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initlock_153268)(pthread_mutex_t* lock);
static N_INLINE(void, destroysemaphore_154026)(Semaphore154008* cv);
static N_INLINE(void, deinitcond_153329)(pthread_cond_t* cond);
static N_INLINE(void, deinitlock_153278)(pthread_mutex_t* lock);
N_NIMCALL(void, await_154038)(Semaphore154008* cv);
N_NIMCALL(void, acquire_153299)(pthread_mutex_t* lock);
static N_INLINE(void, wait_153339)(pthread_cond_t* cond, pthread_mutex_t* lock);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(void, release_153309)(pthread_mutex_t* lock);
N_NIMCALL(void, signal_154068)(Semaphore154008* cv);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(void, signal_153351)(pthread_cond_t* cond);
static N_INLINE(void, barrierEnter)(Barrier* b);
static N_INLINE(void, barrierLeave)(Barrier* b);
static N_INLINE(NI, atomicinc_18001)(NI* memloc, NI x);
static N_INLINE(void, openBarrier)(Barrier* b);
N_NIMCALL(void, closeBarrier)(Barrier* b);
N_NIMCALL(void, await_154302)(Flowvarbaseobj154247* fv);
N_NIMCALL(NIM_BOOL, selectworker_154313)(Worker154257* w, Workerproc154255 fn, void* data);
N_NIMCALL(void, cleanflowvars_154341)(Worker154257* w);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, nimGCunref)(void* p);
static N_INLINE(void, decref_61604)(Cell55949* c);
static N_INLINE(void, rtladdzct_61204)(Cell55949* c);
N_NOINLINE(void, addzct_59644)(Cellseq55965* s, Cell55949* c);
static N_INLINE(NIM_BOOL, canbecycleroot_59694)(Cell55949* c);
static N_INLINE(void, rtladdcycleroot_60423)(Cell55949* c);
N_NOINLINE(void, incl_56665)(Cellset55961* s, Cell55949* cell);
static N_INLINE(Cell55949*, usrtocell_59673)(void* usr);
N_NIMCALL(void, wakeupworkertoprocessqueue_154399)(Worker154257* w);
static N_INLINE(void, cpurelax_19401)(void);
N_NIMCALL(void, HEX3Aanonymous_154416)(void* w_154418, void* a);
N_NIMCALL(void, finished_154441)(Flowvarbaseobj154247* fv);
N_NOINLINE(void, raiseassert_99571)(NimStringDesc* msg);
N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj154247* fv);
N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj154247* fv);
N_NIMCALL(NI, awaitany_154622)(Flowvarbaseobj154247** flowvars, NI flowvarsLen0);
N_NIMCALL(NIM_BOOL, isready_154738)(Flowvarbaseobj154247* fv);
N_NIMCALL(void, nimArgsPassingDone)(void* p);
N_NIMCALL(void, slave_154788)(Worker154257* w);
N_NIMCALL(void, failedassertimpl_99603)(NimStringDesc* msg);
static N_INLINE(NI, atomicdec_18006)(NI* memloc, NI x);
N_NIMCALL(void, distinguishedslave_155215)(Worker154257* w);
N_NIMCALL(void, setminpoolsize_155801)(NI size);
N_NIMCALL(void, setmaxpoolsize_155811)(NI size);
N_NIMCALL(void, createthread_156007)(Thread155620* t, TY156014 tp, Worker154257* param);
N_NOCONV(void*, threadprocwrapper_156406)(void* closure);
N_NIMCALL(void, threadprocwrapstackframe_156605)(Thread155620* thrd);
N_NIMCALL(void, threadprocwrapdispatch_156809)(Thread155620* thrd);
N_NOINLINE(void, activateworkerthread_156001)(NI i);
N_NOINLINE(void, activatedistinguishedthread_158207)(NI i);
N_NIMCALL(void, setup_158234)(void);
N_NIMCALL(NI, ncpicountProcessors)(void);
N_NIMCALL(NIM_BOOL, preferspawn_158448)(void);
N_NIMCALL(void, nimSpawn3)(Workerproc154255 fn, void* data);
N_NIMCALL(NIM_BOOL, tryacquire_153288)(pthread_mutex_t* lock);
N_NIMCALL(NU8, advice_152215)(Threadpoolstate152207* s);
N_NIMCALL(void, nimSpawn4)(Workerproc154255 fn, void* data, NI id);
N_NIMCALL(void, sync_158663)(void);
N_NIMCALL(void, fvfinalizer_250306)(Flowvarobj250295* fv);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
N_NIMCALL(void, TMP1217)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
STRING_LITERAL(TMP549, "isNil(fv.ai) flowVar is still attached to an \'awaitAny\'", 55);
STRING_LITERAL(TMP555, "not w.ready ", 12);
extern NIM_THREADVAR TFrame* frameptr_27442;
extern NIM_THREADVAR Gcheap58018 gch_58059;
NI currentpoolsize_154774;
NI maxpoolsize_154775;
NI minpoolsize_154776;
Semaphore154008 gsomeready_154777;
Worker154257* readyworker_154779;
TY155633 workers_155634;
TY155636 workersdata_155637;
TY155642 distinguished_155643;
TY155645 distinguisheddata_155646;
Threadpoolstate152207 state_158488;
pthread_mutex_t statelock_158489;
pthread_mutex_t distinguishedlock_158632;
extern TNimType NTI4011; /* RootObj */
TNimType NTI154247; /* FlowVarBaseObj */
extern TNimType NTI138; /* bool */
TNimType NTI154008; /* Semaphore */
extern TNimType NTI153204; /* Cond */
extern TNimType NTI153202; /* SysLock */
extern TNimType NTI108; /* int */
TNimType NTI154243; /* AwaitInfo */
TNimType NTI154264; /* ptr AwaitInfo */
extern TNimType NTI153; /* pointer */
TNimType NTI250295; /* FlowVarObj */
extern TNimType NTI149; /* string */
TNimType NTI250292; /* FlowVar */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_27442 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_27442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_27442;
	frameptr_27442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_30201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_27442 = (*frameptr_27442).prev;
}

static N_INLINE(void, initcond_153319)(pthread_cond_t* cond) {
	nimfr("initCond", "locks.nim")
	nimln(44, "locks.nim");
	pthread_cond_init(cond, NIM_NIL);
	popFrame();
}

static N_INLINE(void, initlock_153268)(pthread_mutex_t* lock) {
	nimfr("initLock", "locks.nim")
	nimln(23, "locks.nim");
	pthread_mutex_init(lock, NIM_NIL);
	popFrame();
}

N_NIMCALL(Semaphore154008, createsemaphore_154015)(void) {
	Semaphore154008 result;
	memset((void*)(&result), 0, sizeof(result));
	initcond_153319((&result.c));
	initlock_153268((&result.L));
	return result;
}

static N_INLINE(void, deinitcond_153329)(pthread_cond_t* cond) {
	nimfr("deinitCond", "locks.nim")
	nimln(48, "locks.nim");
	pthread_cond_destroy(cond);
	popFrame();
}

static N_INLINE(void, deinitlock_153278)(pthread_mutex_t* lock) {
	nimfr("deinitLock", "locks.nim")
	nimln(27, "locks.nim");
	pthread_mutex_destroy(lock);
	popFrame();
}

static N_INLINE(void, destroysemaphore_154026)(Semaphore154008* cv) {
	deinitcond_153329((&(*cv).c));
	deinitlock_153278((&(*cv).L));
}

static N_INLINE(void, wait_153339)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	nimfr("wait", "locks.nim")
	nimln(52, "locks.nim");
	pthread_cond_wait(cond, lock);
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, await_154038)(Semaphore154008* cv) {
	NI TMP545;
	acquire_153299((&(*cv).L));
	{
		while (1) {
			if (!((*cv).counter <= ((NI) 0))) goto LA2;
			wait_153339((&(*cv).c), (&(*cv).L));
		} LA2: ;
	}
	TMP545 = subInt((*cv).counter, ((NI) 1));
	(*cv).counter = (NI)(TMP545);
	release_153309((&(*cv).L));
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

static N_INLINE(void, signal_153351)(pthread_cond_t* cond) {
	nimfr("signal", "locks.nim")
	nimln(56, "locks.nim");
	pthread_cond_signal(cond);
	popFrame();
}

N_NIMCALL(void, signal_154068)(Semaphore154008* cv) {
	NI TMP546;
	acquire_153299((&(*cv).L));
	TMP546 = addInt((*cv).counter, ((NI) 1));
	(*cv).counter = (NI)(TMP546);
	release_153309((&(*cv).L));
	signal_153351((&(*cv).c));
}

static N_INLINE(void, barrierEnter)(Barrier* b) {
	NI TMP547;
	TMP547 = addInt((*b).entered, ((NI) 1));
	(*b).entered = (NI)(TMP547);
}

static N_INLINE(NI, atomicinc_18001)(NI* memloc, NI x) {
	NI result;
	result = 0;
	result = __atomic_add_fetch(memloc, x, __ATOMIC_RELAXED);
	return result;
}

static N_INLINE(void, barrierLeave)(Barrier* b) {
	NI LOC1;
	LOC1 = 0;
	LOC1 = atomicinc_18001((&(*b).left), ((NI) 1));
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		NIM_BOOL LOC4;
		LOC4 = 0;
		LOC4 = (*b).interest;
		if (!(LOC4)) goto LA5;
		LOC4 = ((*b).entered <= (*b).left);
		LA5: ;
		if (!LOC4) goto LA6;
		signal_154068((&(*b).cv));
	}
	LA6: ;
}

static N_INLINE(void, openBarrier)(Barrier* b) {
	(*b).entered = ((NI) 0);
	(*b).left = ((NI) 0);
	(*b).interest = NIM_FALSE;
}

N_NIMCALL(void, closeBarrier)(Barrier* b) {
	__atomic_thread_fence(__ATOMIC_SEQ_CST);
	{
		if (!!(((*b).left == (*b).entered))) goto LA3;
		(*b).cv = createsemaphore_154015();
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		(*b).interest = NIM_TRUE;
		__atomic_thread_fence(__ATOMIC_SEQ_CST);
		{
			while (1) {
				if (!!(((*b).left == (*b).entered))) goto LA6;
				await_154038((&(*b).cv));
			} LA6: ;
		}
		destroysemaphore_154026((&(*b).cv));
	}
	LA3: ;
}

N_NIMCALL(void, await_154302)(Flowvarbaseobj154247* fv) {
	nimfr("await", "threadpool.nim")
	nimln(136, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (*fv).usessemaphore;
		if (!(LOC3)) goto LA4;
		LOC3 = !((*fv).awaited);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(137, "threadpool.nim");
		(*fv).awaited = NIM_TRUE;
		nimln(138, "threadpool.nim");
		await_154038((&(*fv).cv));
		nimln(139, "threadpool.nim");
		destroysemaphore_154026((&(*fv).cv));
	}
	LA5: ;
	popFrame();
}

N_NIMCALL(NIM_BOOL, selectworker_154313)(Worker154257* w, Workerproc154255 fn, void* data) {
	NIM_BOOL result;
	nimfr("selectWorker", "threadpool.nim")
	result = 0;
	nimln(142, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
		if (!LOC3) goto LA4;
		nimln(143, "threadpool.nim");
		(*w).data = data;
		nimln(144, "threadpool.nim");
		(*w).f = fn;
		nimln(145, "threadpool.nim");
		signal_154068((&(*w).taskarrived));
		nimln(146, "threadpool.nim");
		await_154038((&(*w).taskstarted));
		nimln(147, "threadpool.nim");
		result = NIM_TRUE;
	}
	LA4: ;
	popFrame();
	return result;
}

static N_INLINE(void, rtladdzct_61204)(Cell55949* c) {
	nimfr("rtlAddZCT", "gc.nim")
	nimln(212, "gc.nim");
	addzct_59644((&gch_58059.zct), c);
	popFrame();
}

static N_INLINE(NIM_BOOL, canbecycleroot_59694)(Cell55949* c) {
	NIM_BOOL result;
	nimfr("canBeCycleRoot", "gc.nim")
	result = 0;
	nimln(134, "gc.nim");
	nimln(1104, "system.nim");
	result = !((((*(*c).typ).flags &(1<<((((NU8) 1))&7)))!=0));
	popFrame();
	return result;
}

static N_INLINE(void, rtladdcycleroot_60423)(Cell55949* c) {
	nimfr("rtlAddCycleRoot", "gc.nim")
	nimln(202, "gc.nim");
	{
		nimln(349, "system.nim");
		nimln(147, "gc.nim");
		if (!!((((NI) ((NI)((*c).refcount & ((NI) 3)))) == ((NI) 3)))) goto LA3;
		nimln(152, "gc.nim");
		(*c).refcount = (NI)((NI)((*c).refcount & ((NI) -4)) | ((NI) 3));
		nimln(204, "gc.nim");
		incl_56665((&gch_58059.cycleroots), c);
	}
	LA3: ;
	popFrame();
}

static N_INLINE(void, decref_61604)(Cell55949* c) {
	nimfr("decRef", "gc.nim")
	nimln(219, "gc.nim");
	{
		nimln(180, "gc.nim");
		(*c).refcount -= ((NI) 8);
		nimln(181, "gc.nim");
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3;
		nimln(220, "gc.nim");
		rtladdzct_61204(c);
	}
	goto LA1;
	LA3: ;
	{
		NIM_BOOL LOC6;
		nimln(221, "gc.nim");
		LOC6 = 0;
		LOC6 = canbecycleroot_59694(c);
		if (!LOC6) goto LA7;
		nimln(224, "gc.nim");
		rtladdcycleroot_60423(c);
	}
	goto LA1;
	LA7: ;
	LA1: ;
	popFrame();
}

static N_INLINE(Cell55949*, usrtocell_59673)(void* usr) {
	Cell55949* result;
	nimfr("usrToCell", "gc.nim")
	result = 0;
	nimln(131, "gc.nim");
	result = ((Cell55949*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(Cell55949))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunref)(void* p) {
	Cell55949* LOC1;
	nimfr("nimGCunref", "gc.nim")
	nimln(236, "gc.nim");
	LOC1 = 0;
	LOC1 = usrtocell_59673(p);
	decref_61604(LOC1);
	popFrame();
}

N_NIMCALL(void, cleanflowvars_154341)(Worker154257* w) {
	Tofreequeue154253* q;
	nimfr("cleanFlowVars", "threadpool.nim")
	nimln(150, "threadpool.nim");
	q = (&(*w).q);
	nimln(151, "threadpool.nim");
	acquire_153299((&(*q).lock));
	{
		NI i_154366;
		NI HEX3Atmp_154377;
		NI res_154380;
		i_154366 = 0;
		HEX3Atmp_154377 = 0;
		nimln(152, "threadpool.nim");
		HEX3Atmp_154377 = subInt((*q).len, 1);
		nimln(1874, "system.nim");
		res_154380 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP548;
				if (!(res_154380 <= HEX3Atmp_154377)) goto LA3;
				nimln(1876, "system.nim");
				i_154366 = res_154380;
				nimln(153, "threadpool.nim");
				if ((NU)(i_154366) > (NU)(127)) raiseIndexError();
				nimGCunref(((TNimObject*) ((*q).data[(i_154366)- 0])));
				nimln(1895, "system.nim");
				TMP548 = addInt(res_154380, ((NI) 1));
				res_154380 = (NI)(TMP548);
			} LA3: ;
		}
	}
	nimln(155, "threadpool.nim");
	(*q).len = ((NI) 0);
	nimln(156, "threadpool.nim");
	release_153309((&(*q).lock));
	popFrame();
}

static N_INLINE(void, cpurelax_19401)(void) {
	asm volatile("pause" ::: "memory");
}

N_NIMCALL(void, HEX3Aanonymous_154416)(void* w_154418, void* a) {
	Worker154257* w;
	nimfr(":anonymous", "threadpool.nim")
	nimln(166, "threadpool.nim");
	w = ((Worker154257*) (w_154418));
	nimln(167, "threadpool.nim");
	cleanflowvars_154341(w);
	nimln(168, "threadpool.nim");
	signal_154068((&(*w).q.empty));
	popFrame();
}

N_NIMCALL(void, wakeupworkertoprocessqueue_154399)(Worker154257* w) {
	nimfr("wakeupWorkerToProcessQueue", "threadpool.nim")
	{
		nimln(161, "threadpool.nim");
		while (1) {
			NIM_BOOL LOC3;
			LOC3 = 0;
			LOC3 = __sync_bool_compare_and_swap((&(*w).ready), NIM_TRUE, NIM_FALSE);
			if (!!(LOC3)) goto LA2;
			nimln(162, "threadpool.nim");
			cpurelax_19401();
		} LA2: ;
	}
	nimln(164, "threadpool.nim");
	(*w).data = NIM_NIL;
	nimln(165, "threadpool.nim");
	(*w).f = HEX3Aanonymous_154416;
	nimln(169, "threadpool.nim");
	signal_154068((&(*w).taskarrived));
	popFrame();
}

N_NIMCALL(void, finished_154441)(Flowvarbaseobj154247* fv) {
	Worker154257* owner;
	Tofreequeue154253* q;
	NI TMP550;
	nimfr("finished", "threadpool.nim")
{	nimln(172, "threadpool.nim");
	{
		if (!!((*fv).ai == 0)) goto LA3;
		raiseassert_99571(((NimStringDesc*) &TMP549));
	}
	LA3: ;
	nimln(176, "threadpool.nim");
	await_154302(fv);
	nimln(177, "threadpool.nim");
	{
		if (!(*fv).data == 0) goto LA7;
		goto BeforeRet;
	}
	LA7: ;
	nimln(178, "threadpool.nim");
	owner = ((Worker154257*) ((*fv).owner));
	nimln(179, "threadpool.nim");
	q = (&(*owner).q);
	nimln(180, "threadpool.nim");
	acquire_153299((&(*q).lock));
	{
		nimln(181, "threadpool.nim");
		while (1) {
			if (!!(((*q).len < ((NI) 128)))) goto LA10;
			nimln(183, "threadpool.nim");
			release_153309((&(*q).lock));
			nimln(184, "threadpool.nim");
			wakeupworkertoprocessqueue_154399(owner);
			nimln(185, "threadpool.nim");
			await_154038((&(*q).empty));
			nimln(186, "threadpool.nim");
			acquire_153299((&(*q).lock));
		} LA10: ;
	}
	nimln(187, "threadpool.nim");
	if ((NU)((*q).len) > (NU)(127)) raiseIndexError();
	(*q).data[((*q).len)- 0] = ((void*) ((*fv).data));
	nimln(188, "threadpool.nim");
	TMP550 = addInt((*q).len, ((NI) 1));
	(*q).len = (NI)(TMP550);
	nimln(189, "threadpool.nim");
	release_153309((&(*q).lock));
	nimln(190, "threadpool.nim");
	(*fv).data = NIM_NIL;
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nimFlowVarCreateSemaphore)(Flowvarbaseobj154247* fv) {
	nimfr("nimFlowVarCreateSemaphore", "threadpool.nim")
	nimln(198, "threadpool.nim");
	(*fv).cv = createsemaphore_154015();
	nimln(199, "threadpool.nim");
	(*fv).usessemaphore = NIM_TRUE;
	popFrame();
}

N_NIMCALL(void, nimFlowVarSignal)(Flowvarbaseobj154247* fv) {
	nimfr("nimFlowVarSignal", "threadpool.nim")
	nimln(202, "threadpool.nim");
	{
		NI TMP551;
		nimln(349, "system.nim");
		if (!!(((*fv).ai == NIM_NIL))) goto LA3;
		nimln(203, "threadpool.nim");
		acquire_153299((&(*(*fv).ai).cv.L));
		nimln(204, "threadpool.nim");
		(*(*fv).ai).idx = (*fv).idx;
		nimln(205, "threadpool.nim");
		TMP551 = addInt((*(*fv).ai).cv.counter, ((NI) 1));
		(*(*fv).ai).cv.counter = (NI)(TMP551);
		nimln(206, "threadpool.nim");
		release_153309((&(*(*fv).ai).cv.L));
		nimln(207, "threadpool.nim");
		signal_153351((&(*(*fv).ai).cv.c));
	}
	LA3: ;
	nimln(208, "threadpool.nim");
	{
		if (!(*fv).usessemaphore) goto LA7;
		nimln(209, "threadpool.nim");
		signal_154068((&(*fv).cv));
	}
	LA7: ;
	popFrame();
}

N_NIMCALL(NI, awaitany_154622)(Flowvarbaseobj154247** flowvars, NI flowvarsLen0) {
	NI result;
	Awaitinfo154243 ai;
	NI conflicts;
	nimfr("awaitAny", "threadpool.nim")
	result = 0;
	memset((void*)(&ai), 0, sizeof(ai));
	nimln(254, "threadpool.nim");
	ai.cv = createsemaphore_154015();
	nimln(255, "threadpool.nim");
	conflicts = ((NI) 0);
	{
		NI i_154639;
		NI HEX3Atmp_154699;
		NI res_154702;
		i_154639 = 0;
		HEX3Atmp_154699 = 0;
		nimln(256, "threadpool.nim");
		HEX3Atmp_154699 = (flowvarsLen0-1);
		nimln(1874, "system.nim");
		res_154702 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP553;
				if (!(res_154702 <= HEX3Atmp_154699)) goto LA3;
				nimln(1876, "system.nim");
				i_154639 = res_154702;
				nimln(257, "threadpool.nim");
				{
					NIM_BOOL LOC6;
					if ((NU)(i_154639) >= (NU)(flowvarsLen0)) raiseIndexError();
					LOC6 = 0;
					LOC6 = __sync_bool_compare_and_swap(&(*flowvars[i_154639]).ai, NIM_NIL, (&ai));
					if (!LOC6) goto LA7;
					nimln(258, "threadpool.nim");
					if ((NU)(i_154639) >= (NU)(flowvarsLen0)) raiseIndexError();
					(*flowvars[i_154639]).idx = i_154639;
				}
				goto LA4;
				LA7: ;
				{
					NI TMP552;
					nimln(260, "threadpool.nim");
					TMP552 = addInt(conflicts, ((NI) 1));
					conflicts = (NI)(TMP552);
				}
				LA4: ;
				nimln(1895, "system.nim");
				TMP553 = addInt(res_154702, ((NI) 1));
				res_154702 = (NI)(TMP553);
			} LA3: ;
		}
	}
	nimln(261, "threadpool.nim");
	{
		if (!(conflicts < flowvarsLen0)) goto LA12;
		nimln(262, "threadpool.nim");
		await_154038((&ai.cv));
		nimln(263, "threadpool.nim");
		result = ai.idx;
		{
			NI i_154681;
			NI HEX3Atmp_154707;
			NI res_154710;
			i_154681 = 0;
			HEX3Atmp_154707 = 0;
			nimln(264, "threadpool.nim");
			HEX3Atmp_154707 = (flowvarsLen0-1);
			nimln(1874, "system.nim");
			res_154710 = ((NI) 0);
			{
				nimln(1875, "system.nim");
				while (1) {
					NIM_BOOL LOC17;
					NI TMP554;
					if (!(res_154710 <= HEX3Atmp_154707)) goto LA16;
					nimln(1876, "system.nim");
					i_154681 = res_154710;
					nimln(265, "threadpool.nim");
					if ((NU)(i_154681) >= (NU)(flowvarsLen0)) raiseIndexError();
					LOC17 = 0;
					LOC17 = __sync_bool_compare_and_swap(&(*flowvars[i_154681]).ai, (&ai), NIM_NIL);
					nimln(1895, "system.nim");
					TMP554 = addInt(res_154710, ((NI) 1));
					res_154710 = (NI)(TMP554);
				} LA16: ;
			}
		}
	}
	goto LA10;
	LA12: ;
	{
		nimln(267, "threadpool.nim");
		result = ((NI) -1);
	}
	LA10: ;
	nimln(268, "threadpool.nim");
	destroysemaphore_154026((&ai.cv));
	popFrame();
	return result;
}

N_NIMCALL(NIM_BOOL, isready_154738)(Flowvarbaseobj154247* fv) {
	NIM_BOOL result;
	nimfr("isReady", "threadpool.nim")
	result = 0;
	nimln(274, "threadpool.nim");
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (*fv).usessemaphore;
		if (!(LOC3)) goto LA4;
		LOC3 = !((*fv).awaited);
		LA4: ;
		if (!LOC3) goto LA5;
		nimln(275, "threadpool.nim");
		acquire_153299((&(*fv).cv.L));
		nimln(276, "threadpool.nim");
		nimln(357, "system.nim");
		result = (((NI) 0) < (*fv).cv.counter);
		nimln(277, "threadpool.nim");
		release_153309((&(*fv).cv.L));
	}
	goto LA1;
	LA5: ;
	{
		nimln(279, "threadpool.nim");
		result = NIM_TRUE;
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(void, nimArgsPassingDone)(void* p) {
	Worker154257* w;
	nimfr("nimArgsPassingDone", "threadpool.nim")
	nimln(282, "threadpool.nim");
	w = ((Worker154257*) (p));
	nimln(283, "threadpool.nim");
	signal_154068((&(*w).taskstarted));
	popFrame();
}

static N_INLINE(NI, atomicdec_18006)(NI* memloc, NI x) {
	NI result;
	result = 0;
	result = __atomic_sub_fetch(memloc, x, __ATOMIC_RELAXED);
	return result;
}

N_NIMCALL(void, slave_154788)(Worker154257* w) {
	nimfr("slave", "threadpool.nim")
	{
		nimln(301, "threadpool.nim");
		while (1) {
			nimln(303, "threadpool.nim");
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln(306, "threadpool.nim");
			readyworker_154779 = w;
			nimln(307, "threadpool.nim");
			signal_154068((&gsomeready_154777));
			nimln(308, "threadpool.nim");
			await_154038((&(*w).taskarrived));
			nimln(311, "threadpool.nim");
			{
				if (!!(!((*w).ready))) goto LA5;
				failedassertimpl_99603(((NimStringDesc*) &TMP555));
			}
			LA5: ;
			nimln(312, "threadpool.nim");
			(*w).f(((void*) (w)), (*w).data);
			nimln(313, "threadpool.nim");
			{
				nimln(349, "system.nim");
				if (!!(((*w).q.len == ((NI) 0)))) goto LA9;
				nimln(313, "threadpool.nim");
				cleanflowvars_154341(w);
			}
			LA9: ;
			nimln(314, "threadpool.nim");
			{
				NI LOC15;
				if (!(*w).shutdown) goto LA13;
				nimln(315, "threadpool.nim");
				(*w).shutdown = NIM_FALSE;
				nimln(316, "threadpool.nim");
				LOC15 = 0;
				LOC15 = atomicdec_18006((&currentpoolsize_154774), ((NI) 1));
			}
			LA13: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, distinguishedslave_155215)(Worker154257* w) {
	nimfr("distinguishedSlave", "threadpool.nim")
	{
		nimln(319, "threadpool.nim");
		while (1) {
			nimln(321, "threadpool.nim");
			__atomic_store_n((&(*w).ready), NIM_TRUE, __ATOMIC_SEQ_CST);
			nimln(324, "threadpool.nim");
			signal_154068((&(*w).readyfortask));
			nimln(325, "threadpool.nim");
			await_154038((&(*w).taskarrived));
			nimln(326, "threadpool.nim");
			{
				if (!!(!((*w).ready))) goto LA5;
				failedassertimpl_99603(((NimStringDesc*) &TMP555));
			}
			LA5: ;
			nimln(327, "threadpool.nim");
			(*w).f(((void*) (w)), (*w).data);
			nimln(328, "threadpool.nim");
			{
				nimln(349, "system.nim");
				if (!!(((*w).q.len == ((NI) 0)))) goto LA9;
				nimln(328, "threadpool.nim");
				cleanflowvars_154341(w);
			}
			LA9: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, setminpoolsize_155801)(NI size) {
	nimfr("setMinPoolSize", "threadpool.nim")
	nimln(342, "threadpool.nim");
	minpoolsize_154776 = ((NI) (size));
	popFrame();
}

N_NIMCALL(void, setmaxpoolsize_155811)(NI size) {
	nimfr("setMaxPoolSize", "threadpool.nim")
	nimln(347, "threadpool.nim");
	maxpoolsize_154775 = ((NI) (size));
	nimln(348, "threadpool.nim");
	{
		nimln(357, "system.nim");
		if (!(maxpoolsize_154775 < currentpoolsize_154774)) goto LA3;
		{
			NI i_155825;
			NI HEX3Atmp_155829;
			NI TMP556;
			NI res_155832;
			i_155825 = 0;
			HEX3Atmp_155829 = 0;
			nimln(349, "threadpool.nim");
			TMP556 = subInt(currentpoolsize_154774, ((NI) 1));
			HEX3Atmp_155829 = (NI)(TMP556);
			nimln(1874, "system.nim");
			res_155832 = maxpoolsize_154775;
			{
				nimln(1875, "system.nim");
				while (1) {
					Worker154257* w;
					NI TMP557;
					if (!(res_155832 <= HEX3Atmp_155829)) goto LA7;
					nimln(1876, "system.nim");
					i_155825 = res_155832;
					nimln(350, "threadpool.nim");
					if ((NU)(i_155825) > (NU)(255)) raiseIndexError();
					w = (&workersdata_155637[(i_155825)- 0]);
					nimln(351, "threadpool.nim");
					(*w).shutdown = NIM_TRUE;
					nimln(1895, "system.nim");
					TMP557 = addInt(res_155832, ((NI) 1));
					res_155832 = (NI)(TMP557);
				} LA7: ;
			}
		}
	}
	LA3: ;
	popFrame();
}

N_NOINLINE(void, activateworkerthread_156001)(NI i) {
	nimfr("activateWorkerThread", "threadpool.nim")
	nimln(357, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_155637[(i)- 0].taskarrived = createsemaphore_154015();
	nimln(358, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_155637[(i)- 0].taskstarted = createsemaphore_154015();
	nimln(359, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_155637[(i)- 0].initialized = NIM_TRUE;
	nimln(360, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	workersdata_155637[(i)- 0].q.empty = createsemaphore_154015();
	nimln(361, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	initlock_153268((&workersdata_155637[(i)- 0].q.lock));
	nimln(362, "threadpool.nim");
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	if ((NU)(i) > (NU)(255)) raiseIndexError();
	createthread_156007((&workers_155634[(i)- 0]), slave_154788, (&workersdata_155637[(i)- 0]));
	popFrame();
}

N_NOINLINE(void, activatedistinguishedthread_158207)(NI i) {
	nimfr("activateDistinguishedThread", "threadpool.nim")
	nimln(369, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_155646[(i)- 0].taskarrived = createsemaphore_154015();
	nimln(370, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_155646[(i)- 0].taskstarted = createsemaphore_154015();
	nimln(371, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_155646[(i)- 0].initialized = NIM_TRUE;
	nimln(372, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_155646[(i)- 0].q.empty = createsemaphore_154015();
	nimln(373, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	initlock_153268((&distinguisheddata_155646[(i)- 0].q.lock));
	nimln(374, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	distinguisheddata_155646[(i)- 0].readyfortask = createsemaphore_154015();
	nimln(375, "threadpool.nim");
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	if ((NU)(i) > (NU)(31)) raiseIndexError();
	createthread_156007((&distinguished_155643[(i)- 0]), distinguishedslave_155215, (&distinguisheddata_155646[(i)- 0]));
	popFrame();
}

N_NIMCALL(void, setup_158234)(void) {
	NI p;
	nimfr("setup", "threadpool.nim")
	nimln(378, "threadpool.nim");
	p = ncpicountProcessors();
	nimln(381, "threadpool.nim");
	currentpoolsize_154774 = ((p <= ((NI) 256)) ? p : ((NI) 256));
	nimln(382, "threadpool.nim");
	readyworker_154779 = (&workersdata_155637[(((NI) 0))- 0]);
	{
		NI i_158424;
		NI HEX3Atmp_158426;
		NI res_158429;
		i_158424 = 0;
		HEX3Atmp_158426 = 0;
		nimln(383, "threadpool.nim");
		HEX3Atmp_158426 = subInt(currentpoolsize_154774, 1);
		nimln(1874, "system.nim");
		res_158429 = ((NI) 0);
		{
			nimln(1875, "system.nim");
			while (1) {
				NI TMP558;
				if (!(res_158429 <= HEX3Atmp_158426)) goto LA3;
				nimln(1876, "system.nim");
				i_158424 = res_158429;
				nimln(383, "threadpool.nim");
				activateworkerthread_156001(i_158424);
				nimln(1895, "system.nim");
				TMP558 = addInt(res_158429, ((NI) 1));
				res_158429 = (NI)(TMP558);
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(NIM_BOOL, preferspawn_158448)(void) {
	NIM_BOOL result;
	nimfr("preferSpawn", "threadpool.nim")
	result = 0;
	nimln(389, "threadpool.nim");
	nimln(357, "system.nim");
	result = (((NI) 0) < gsomeready_154777.counter);
	popFrame();
	return result;
}

N_NIMCALL(void, nimSpawn3)(Workerproc154255 fn, void* data) {
	nimfr("nimSpawn3", "threadpool.nim")
{	{
		nimln(426, "threadpool.nim");
		while (1) {
			nimln(427, "threadpool.nim");
			{
				NIM_BOOL LOC5;
				LOC5 = 0;
				LOC5 = selectworker_154313(readyworker_154779, fn, data);
				if (!LOC5) goto LA6;
				goto BeforeRet;
			}
			LA6: ;
			{
				NI i_158521;
				NI HEX3Atmp_158604;
				NI res_158607;
				i_158521 = 0;
				HEX3Atmp_158604 = 0;
				nimln(428, "threadpool.nim");
				HEX3Atmp_158604 = subInt(currentpoolsize_154774, 1);
				nimln(1874, "system.nim");
				res_158607 = ((NI) 0);
				{
					nimln(1875, "system.nim");
					while (1) {
						NI TMP559;
						if (!(res_158607 <= HEX3Atmp_158604)) goto LA10;
						nimln(1876, "system.nim");
						i_158521 = res_158607;
						nimln(429, "threadpool.nim");
						{
							NIM_BOOL LOC13;
							if ((NU)(i_158521) > (NU)(255)) raiseIndexError();
							LOC13 = 0;
							LOC13 = selectworker_154313((&workersdata_155637[(i_158521)- 0]), fn, data);
							if (!LOC13) goto LA14;
							goto BeforeRet;
						}
						LA14: ;
						nimln(1895, "system.nim");
						TMP559 = addInt(res_158607, ((NI) 1));
						res_158607 = (NI)(TMP559);
					} LA10: ;
				}
			}
			nimln(433, "threadpool.nim");
			{
				NIM_BOOL LOC18;
				LOC18 = 0;
				LOC18 = (state_158488.calls < maxpoolsize_154775);
				if (LOC18) goto LA19;
				LOC18 = (((NI) ((NI)(state_158488.calls & ((NI) 127)))) == ((NI) 0));
				LA19: ;
				if (!LOC18) goto LA20;
				nimln(435, "threadpool.nim");
				{
					NIM_BOOL LOC24;
					NU8 LOC27;
					LOC24 = 0;
					LOC24 = tryacquire_153288((&statelock_158489));
					if (!LOC24) goto LA25;
					nimln(436, "threadpool.nim");
					LOC27 = 0;
					LOC27 = advice_152215((&state_158488));
					switch (LOC27) {
					case ((NU8) 0):
					{
					}
					break;
					case ((NU8) 1):
					{
						nimln(439, "threadpool.nim");
						{
							Worker154257* w;
							NI LOC38;
							if (!(currentpoolsize_154774 < maxpoolsize_154775)) goto LA32;
							nimln(440, "threadpool.nim");
							{
								if ((NU)(currentpoolsize_154774) > (NU)(255)) raiseIndexError();
								if (!!(workersdata_155637[(currentpoolsize_154774)- 0].initialized)) goto LA36;
								nimln(441, "threadpool.nim");
								activateworkerthread_156001(currentpoolsize_154774);
							}
							LA36: ;
							nimln(442, "threadpool.nim");
							if ((NU)(currentpoolsize_154774) > (NU)(255)) raiseIndexError();
							w = (&workersdata_155637[(currentpoolsize_154774)- 0]);
							nimln(443, "threadpool.nim");
							LOC38 = 0;
							LOC38 = atomicinc_18001((&currentpoolsize_154774), ((NI) 1));
							nimln(444, "threadpool.nim");
							{
								NIM_BOOL LOC41;
								LOC41 = 0;
								LOC41 = selectworker_154313(w, fn, data);
								if (!LOC41) goto LA42;
								nimln(445, "threadpool.nim");
								release_153309((&statelock_158489));
								nimln(446, "threadpool.nim");
								goto BeforeRet;
							}
							LA42: ;
						}
						LA32: ;
					}
					break;
					case ((NU8) 2):
					{
						nimln(449, "threadpool.nim");
						{
							Worker154257* w;
							NI TMP560;
							nimln(357, "system.nim");
							if (!(minpoolsize_154776 < currentpoolsize_154774)) goto LA47;
							nimln(450, "threadpool.nim");
							TMP560 = subInt(currentpoolsize_154774, ((NI) 1));
							if ((NU)((NI)(TMP560)) > (NU)(255)) raiseIndexError();
							w = (&workersdata_155637[((NI)(TMP560))- 0]);
							nimln(451, "threadpool.nim");
							(*w).shutdown = NIM_TRUE;
						}
						LA47: ;
					}
					break;
					}
					nimln(453, "threadpool.nim");
					release_153309((&statelock_158489));
				}
				LA25: ;
			}
			LA20: ;
			nimln(468, "threadpool.nim");
			await_154038((&gsomeready_154777));
		}
	}
	}BeforeRet: ;
	popFrame();
}

N_NIMCALL(void, nimSpawn4)(Workerproc154255 fn, void* data, NI id) {
	nimfr("nimSpawn4", "threadpool.nim")
	nimln(476, "threadpool.nim");
	acquire_153299((&distinguishedlock_158632));
	nimln(477, "threadpool.nim");
	{
		if (!!(distinguisheddata_155646[(id)- 0].initialized)) goto LA3;
		nimln(478, "threadpool.nim");
		activatedistinguishedthread_158207(((NI) (id)));
	}
	LA3: ;
	nimln(479, "threadpool.nim");
	release_153309((&distinguishedlock_158632));
	{
		nimln(480, "threadpool.nim");
		while (1) {
			nimln(481, "threadpool.nim");
			{
				NIM_BOOL LOC9;
				LOC9 = 0;
				LOC9 = selectworker_154313((&distinguisheddata_155646[(id)- 0]), fn, data);
				if (!LOC9) goto LA10;
				goto LA5;
			}
			LA10: ;
			nimln(482, "threadpool.nim");
			await_154038((&distinguisheddata_155646[(id)- 0].readyfortask));
		}
	} LA5: ;
	popFrame();
}

N_NIMCALL(void, sync_158663)(void) {
	nimfr("sync", "threadpool.nim")
	{
		nimln(488, "threadpool.nim");
		while (1) {
			NIM_BOOL allready;
			nimln(489, "threadpool.nim");
			allready = NIM_TRUE;
			{
				NI i_158684;
				NI HEX3Atmp_158688;
				NI res_158691;
				i_158684 = 0;
				HEX3Atmp_158688 = 0;
				nimln(490, "threadpool.nim");
				HEX3Atmp_158688 = subInt(currentpoolsize_154774, 1);
				nimln(1874, "system.nim");
				res_158691 = ((NI) 0);
				{
					nimln(1875, "system.nim");
					while (1) {
						NIM_BOOL LOC10;
						NI TMP561;
						if (!(res_158691 <= HEX3Atmp_158688)) goto LA5;
						nimln(1876, "system.nim");
						i_158684 = res_158691;
						nimln(491, "threadpool.nim");
						{
							if (!!(allready)) goto LA8;
							goto LA3;
						}
						LA8: ;
						nimln(492, "threadpool.nim");
						LOC10 = 0;
						LOC10 = allready;
						if (!(LOC10)) goto LA11;
						if ((NU)(i_158684) > (NU)(255)) raiseIndexError();
						LOC10 = workersdata_155637[(i_158684)- 0].ready;
						LA11: ;
						allready = LOC10;
						nimln(1895, "system.nim");
						TMP561 = addInt(res_158691, ((NI) 1));
						res_158691 = (NI)(TMP561);
					} LA5: ;
				}
			} LA3: ;
			nimln(493, "threadpool.nim");
			{
				if (!allready) goto LA14;
				goto LA1;
			}
			LA14: ;
			nimln(494, "threadpool.nim");
			await_154038((&gsomeready_154777));
		}
	} LA1: ;
	popFrame();
}

N_NIMCALL(void, fvfinalizer_250306)(Flowvarobj250295* fv) {
	Flowvarbaseobj154247* LOC1;
	nimfr("fvFinalizer", "threadpool.nim")
	nimln(192, "threadpool.nim");
	LOC1 = 0;
	LOC1 = &fv->Sup;
	finished_154441(LOC1);
	popFrame();
}
N_NIMCALL(void, TMP1217)(void* p, NI op) {
	Flowvarobj250295* a;
	a = (Flowvarobj250295*)p;
	nimGCvisit((void*)(*a).blob, op);
}

N_NIMCALL(Flowvarobj250295*, nimcreateflowvar_250299)(void) {
	Flowvarobj250295* result;
	nimfr("nimCreateFlowVar", "threadpool.nim")
	result = 0;
	nimln(195, "threadpool.nim");
	result = (Flowvarobj250295*) newObj((&NTI250292), sizeof(Flowvarobj250295));
	(*result).Sup.Sup.m_type = (&NTI250295);
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, HEX5E_250356)(Flowvarobj250295* fv) {
	NimStringDesc* result;
	Flowvarbaseobj154247* LOC1;
	nimfr("^", "threadpool.nim")
	result = 0;
	nimln(238, "threadpool.nim");
	LOC1 = 0;
	LOC1 = &fv->Sup;
	await_154302(LOC1);
	nimln(241, "threadpool.nim");
	result = copyString(((NimStringDesc*) ((*fv).Sup.data)));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolInit000)(void) {
	nimfr("threadpool", "threadpool.nim")
	nimln(295, "threadpool.nim");
	maxpoolsize_154775 = ((NI) 256);
	nimln(296, "threadpool.nim");
	minpoolsize_154776 = ((NI) 4);
	nimln(297, "threadpool.nim");
	gsomeready_154777 = createsemaphore_154015();
	nimln(422, "threadpool.nim");
	initlock_153268((&statelock_158489));
	nimln(473, "threadpool.nim");
	initlock_153268((&distinguishedlock_158632));
	nimln(496, "threadpool.nim");
	setup_158234();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_threadpoolDatInit000)(void) {
static TNimNode* TMP1214[8];
static TNimNode* TMP1215[3];
static TNimNode* TMP1216[2];
static TNimNode TMP530[17];
NTI154247.size = sizeof(Flowvarbaseobj154247);
NTI154247.kind = 17;
NTI154247.base = (&NTI4011);
NTI154247.flags = 1;
TMP1214[0] = &TMP530[1];
TMP530[1].kind = 1;
TMP530[1].offset = offsetof(Flowvarbaseobj154247, ready);
TMP530[1].typ = (&NTI138);
TMP530[1].name = "ready";
TMP1214[1] = &TMP530[2];
TMP530[2].kind = 1;
TMP530[2].offset = offsetof(Flowvarbaseobj154247, usessemaphore);
TMP530[2].typ = (&NTI138);
TMP530[2].name = "usesSemaphore";
TMP1214[2] = &TMP530[3];
TMP530[3].kind = 1;
TMP530[3].offset = offsetof(Flowvarbaseobj154247, awaited);
TMP530[3].typ = (&NTI138);
TMP530[3].name = "awaited";
TMP1214[3] = &TMP530[4];
NTI154008.size = sizeof(Semaphore154008);
NTI154008.kind = 18;
NTI154008.base = 0;
NTI154008.flags = 3;
TMP1215[0] = &TMP530[6];
TMP530[6].kind = 1;
TMP530[6].offset = offsetof(Semaphore154008, c);
TMP530[6].typ = (&NTI153204);
TMP530[6].name = "c";
TMP1215[1] = &TMP530[7];
TMP530[7].kind = 1;
TMP530[7].offset = offsetof(Semaphore154008, L);
TMP530[7].typ = (&NTI153202);
TMP530[7].name = "L";
TMP1215[2] = &TMP530[8];
TMP530[8].kind = 1;
TMP530[8].offset = offsetof(Semaphore154008, counter);
TMP530[8].typ = (&NTI108);
TMP530[8].name = "counter";
TMP530[5].len = 3; TMP530[5].kind = 2; TMP530[5].sons = &TMP1215[0];
NTI154008.node = &TMP530[5];
TMP530[4].kind = 1;
TMP530[4].offset = offsetof(Flowvarbaseobj154247, cv);
TMP530[4].typ = (&NTI154008);
TMP530[4].name = "cv";
TMP1214[4] = &TMP530[9];
NTI154243.size = sizeof(Awaitinfo154243);
NTI154243.kind = 18;
NTI154243.base = 0;
NTI154243.flags = 3;
TMP1216[0] = &TMP530[11];
TMP530[11].kind = 1;
TMP530[11].offset = offsetof(Awaitinfo154243, cv);
TMP530[11].typ = (&NTI154008);
TMP530[11].name = "cv";
TMP1216[1] = &TMP530[12];
TMP530[12].kind = 1;
TMP530[12].offset = offsetof(Awaitinfo154243, idx);
TMP530[12].typ = (&NTI108);
TMP530[12].name = "idx";
TMP530[10].len = 2; TMP530[10].kind = 2; TMP530[10].sons = &TMP1216[0];
NTI154243.node = &TMP530[10];
NTI154264.size = sizeof(Awaitinfo154243*);
NTI154264.kind = 21;
NTI154264.base = (&NTI154243);
NTI154264.flags = 3;
TMP530[9].kind = 1;
TMP530[9].offset = offsetof(Flowvarbaseobj154247, ai);
TMP530[9].typ = (&NTI154264);
TMP530[9].name = "ai";
TMP1214[5] = &TMP530[13];
TMP530[13].kind = 1;
TMP530[13].offset = offsetof(Flowvarbaseobj154247, idx);
TMP530[13].typ = (&NTI108);
TMP530[13].name = "idx";
TMP1214[6] = &TMP530[14];
TMP530[14].kind = 1;
TMP530[14].offset = offsetof(Flowvarbaseobj154247, data);
TMP530[14].typ = (&NTI153);
TMP530[14].name = "data";
TMP1214[7] = &TMP530[15];
TMP530[15].kind = 1;
TMP530[15].offset = offsetof(Flowvarbaseobj154247, owner);
TMP530[15].typ = (&NTI153);
TMP530[15].name = "owner";
TMP530[0].len = 8; TMP530[0].kind = 2; TMP530[0].sons = &TMP1214[0];
NTI154247.node = &TMP530[0];
NTI250295.size = sizeof(Flowvarobj250295);
NTI250295.kind = 17;
NTI250295.base = (&NTI154247);
TMP530[16].kind = 1;
TMP530[16].offset = offsetof(Flowvarobj250295, blob);
TMP530[16].typ = (&NTI149);
TMP530[16].name = "blob";
NTI250295.node = &TMP530[16];
NTI250292.size = sizeof(Flowvarobj250295*);
NTI250292.kind = 22;
NTI250292.base = (&NTI250295);
NTI250292.marker = TMP1217;
(&NTI250292)->finalizer = (void*)fvfinalizer_250306;
}

