/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -pthread  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_locks.o src/nimcache/stdlib_locks.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <pthread.h>
#include <sys/types.h>
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
static N_INLINE(NIM_BOOL, tryacquiresys_153218)(pthread_mutex_t* L);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_30201)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, initlock_153268)(pthread_mutex_t* lock);
static N_INLINE(void, deinitlock_153278)(pthread_mutex_t* lock);
N_NIMCALL(NIM_BOOL, tryacquire_153288)(pthread_mutex_t* lock);
N_NIMCALL(void, acquire_153299)(pthread_mutex_t* lock);
N_NIMCALL(void, release_153309)(pthread_mutex_t* lock);
static N_INLINE(void, initcond_153319)(pthread_cond_t* cond);
static N_INLINE(void, deinitcond_153329)(pthread_cond_t* cond);
static N_INLINE(void, wait_153339)(pthread_cond_t* cond, pthread_mutex_t* lock);
static N_INLINE(void, signal_153351)(pthread_cond_t* cond);
extern NIM_THREADVAR TFrame* frameptr_27442;
TNimType NTI153204; /* Cond */
TNimType NTI153202; /* SysLock */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_27442 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_27442).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_27442;
	frameptr_27442 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_30201();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_27442 = (*frameptr_27442).prev;
}

static N_INLINE(NIM_BOOL, tryacquiresys_153218)(pthread_mutex_t* L) {
	NIM_BOOL result;
	int LOC1;
	nimfr("tryAcquireSys", "syslocks.nim")
	result = 0;
	nimln(90, "syslocks.nim");
	LOC1 = 0;
	LOC1 = pthread_mutex_trylock(L);
	result = (LOC1 == ((NI32) 0));
	popFrame();
	return result;
}

static N_INLINE(void, initlock_153268)(pthread_mutex_t* lock) {
	nimfr("initLock", "locks.nim")
	nimln(23, "locks.nim");
	pthread_mutex_init(lock, NIM_NIL);
	popFrame();
}

static N_INLINE(void, deinitlock_153278)(pthread_mutex_t* lock) {
	nimfr("deinitLock", "locks.nim")
	nimln(27, "locks.nim");
	pthread_mutex_destroy(lock);
	popFrame();
}

N_NIMCALL(NIM_BOOL, tryacquire_153288)(pthread_mutex_t* lock) {
	NIM_BOOL result;
	nimfr("tryAcquire", "locks.nim")
	result = 0;
	nimln(31, "locks.nim");
	result = tryacquiresys_153218(lock);
	popFrame();
	return result;
}

N_NIMCALL(void, acquire_153299)(pthread_mutex_t* lock) {
	nimfr("acquire", "locks.nim")
	nimln(35, "locks.nim");
	pthread_mutex_lock(lock);
	popFrame();
}

N_NIMCALL(void, release_153309)(pthread_mutex_t* lock) {
	nimfr("release", "locks.nim")
	nimln(39, "locks.nim");
	pthread_mutex_unlock(lock);
	popFrame();
}

static N_INLINE(void, initcond_153319)(pthread_cond_t* cond) {
	nimfr("initCond", "locks.nim")
	nimln(44, "locks.nim");
	pthread_cond_init(cond, NIM_NIL);
	popFrame();
}

static N_INLINE(void, deinitcond_153329)(pthread_cond_t* cond) {
	nimfr("deinitCond", "locks.nim")
	nimln(48, "locks.nim");
	pthread_cond_destroy(cond);
	popFrame();
}

static N_INLINE(void, wait_153339)(pthread_cond_t* cond, pthread_mutex_t* lock) {
	nimfr("wait", "locks.nim")
	nimln(52, "locks.nim");
	pthread_cond_wait(cond, lock);
	popFrame();
}

static N_INLINE(void, signal_153351)(pthread_cond_t* cond) {
	nimfr("signal", "locks.nim")
	nimln(56, "locks.nim");
	pthread_cond_signal(cond);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, stdlib_locksInit000)(void) {
	nimfr("locks", "locks.nim")
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_locksDatInit000)(void) {
static TNimNode TMP543[2];
NTI153204.size = sizeof(pthread_cond_t);
NTI153204.kind = 18;
NTI153204.base = 0;
NTI153204.flags = 3;
TMP543[0].len = 0; TMP543[0].kind = 2;
NTI153204.node = &TMP543[0];
NTI153202.size = sizeof(pthread_mutex_t);
NTI153202.kind = 18;
NTI153202.base = 0;
NTI153202.flags = 3;
TMP543[1].len = 0; TMP543[1].kind = 2;
NTI153202.node = &TMP543[1];
}

