/* Generated by Nim Compiler v0.12.1 */
/*   (c) 2015 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/renzhen/Nim12.0/lib -o src/nimcache/stdlib_nativesockets.o src/nimcache/stdlib_nativesockets.c */
#define NIM_INTBITS 64

#include "nimbase.h"
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <netdb.h>
#include <string.h>
#include <arpa/inet.h>
#include <fcntl.h>
#include <sys/select.h>
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct Servent162610 Servent162610;
typedef struct TY17205 TY17205;
typedef struct Hostent162612 Hostent162612;
typedef struct TY165817 TY165817;
typedef struct TY166847 TY166847;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct  TGenericSeq  {
NI len;
NI reserved;
};
struct  NimStringDesc  {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct  Servent162610  {
NimStringDesc* name;
TY17205* aliases;
NU16 port;
NimStringDesc* proto;
};
struct  Hostent162612  {
NimStringDesc* name;
TY17205* aliases;
NU8 addrtype;
NI length;
TY17205* addrlist;
};
typedef NIM_CHAR TY115055[256];
typedef NIM_CHAR TY115080[16];
struct TY165817 {
NimStringDesc* Field0;
NU16 Field1;
};
typedef NIM_CHAR TY166206[64];
typedef N_NIMCALL_PTR(void, TY3889) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, TY3894) (void* p);
struct  TNimType  {
NI size;
NU8 kind;
NU8 flags;
TNimType* base;
TNimNode* node;
void* finalizer;
TY3889 marker;
TY3894 deepcopy;
};
struct  TNimNode  {
NU8 kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TY17205 {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct TY166847 {
  TGenericSeq Sup;
  int data[SEQ_DECL_SIZE];
};
N_NIMCALL(int, toint_162829)(NU8 domain);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackoverflow_23601)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(int, toint_162835)(NU8 typ);
N_NIMCALL(int, toint_162841)(NU8 p);
N_NIMCALL(int, newnativesocket_163004)(NU8 domain, NU8 socktype, NU8 protocol);
N_NIMCALL(int, newnativesocket_163016)(int domain, int socktype, int protocol);
N_NIMCALL(void, close_163028)(int socket);
N_NIMCALL(int, bindaddr_163214)(int socket, struct sockaddr* name, socklen_t namelen);
N_NIMCALL(int, listen_163227)(int socket, int backlog);
N_NIMCALL(struct addrinfo*, getaddrinfo_163408)(NimStringDesc* address, NU16 port, NU8 domain, NU8 socktype, NU8 protocol);
N_NIMCALL(NimStringDesc*, HEX24_8801)(NU64 x);
N_NOINLINE(void, raiseoserror_127009)(NI32 errorcode, NimStringDesc* additionalinfo);
N_NIMCALL(NI32, oslasterror_127034)(void);
N_NIMCALL(NimStringDesc*, cstrToNimstr)(NCSTRING str);
N_NIMCALL(void, dealloc_163808)(struct addrinfo* ai);
N_NIMCALL(NI32, ntohl_163818)(NI32 x);
N_NIMCALL(NI16, ntohs_164007)(NI16 x);
N_NIMCALL(void, getservbyname_164219)(NimStringDesc* name, NimStringDesc* proto, Servent162610* Result);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(TY17205*, cstringarraytoseq_17443)(NCSTRING* a);
N_NIMCALL(void, getservbyport_164420)(NU16 port, NimStringDesc* proto, Servent162610* Result);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void, gethostbyaddr_164620)(NimStringDesc* ip, Hostent162612* Result);
N_NIMCALL(void, gethostbyname_165010)(NimStringDesc* name, Hostent162612* Result);
N_NIMCALL(NU8, getsockdomain_165408)(int socket);
N_NIMCALL(NimStringDesc*, getaddrstring_165425)(struct sockaddr* sockaddr);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, mnewString)(NI len);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI start);
N_NIMCALL(NimStringDesc*, copyStr)(NimStringDesc* s, NI first);
N_NIMCALL(NU16, getsockname_165612)(int socket);
N_NIMCALL(void, getlocaladdr_165813)(int socket, NU8 domain, TY165817* Result);
N_NIMCALL(void, getpeeraddr_166223)(int socket, NU8 domain, TY165817* Result);
N_NIMCALL(NI, getsockoptint_166623)(int socket, NI level, NI optname);
N_NIMCALL(void, setsockoptint_166641)(int socket, NI level, NI optname, NI optval);
N_NIMCALL(void, setblocking_166655)(int s, NIM_BOOL blocking);
N_NIMCALL(struct timeval, timevalfrommilliseconds_166828)(NI timeout);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
N_NOINLINE(void, raiseOverflow)(void);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NIMCALL(void, createfdset_166843)(fd_set* fd, TY166847* s, NI* m);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NIMCALL(void, failedassertimpl_91603)(NimStringDesc* msg);
N_NIMCALL(void, prunesocketset_167046)(TY166847** s, fd_set* fd);
N_NIMCALL(TGenericSeq*, setLengthSeq)(TGenericSeq* seq, NI elemsize, NI newlen);
N_NIMCALL(NI, select_167113)(TY166847** readfds, NI timeout);
N_NIMCALL(NI, selectwrite_167170)(TY166847** writefds, NI timeout);
STRING_LITERAL(TMP614, "Service not found.", 18);
STRING_LITERAL(TMP615, "unknown h_addrtype", 18);
STRING_LITERAL(TMP616, "", 0);
STRING_LITERAL(TMP617, "unknown socket family in getSockFamily", 38);
STRING_LITERAL(TMP618, "unknown socket family in getAddrString", 38);
STRING_LITERAL(TMP619, "invalid socket family in getLocalAddr", 37);
STRING_LITERAL(TMP625, "len(a) == L seq modified while iterating over it", 48);
int osinvalidsocket_162651;
int nativeafinet_162652;
int nativeafinet6_162653;
extern TFrame* frameptr_20842;
TNimType NTI162604; /* Domain */
TNimType NTI162606; /* SockType */
TNimType NTI162608; /* Protocol */

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI LOC1;
	LOC1 = 0;
	{
		if (!(frameptr_20842 == NIM_NIL)) goto LA4;
		LOC1 = ((NI) 0);
	}
	goto LA2;
	LA4: ;
	{
		LOC1 = ((NI) ((NI16)((*frameptr_20842).calldepth + ((NI16) 1))));
	}
	LA2: ;
	(*s).calldepth = ((NI16) (LOC1));
	(*s).prev = frameptr_20842;
	frameptr_20842 = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9;
		stackoverflow_23601();
	}
	LA9: ;
}

static N_INLINE(void, popFrame)(void) {
	frameptr_20842 = (*frameptr_20842).prev;
}

N_NIMCALL(int, toint_162829)(NU8 domain) {
	int result;
	nimfr("toInt", "nativesockets.nim")
	result = 0;
	nimln(125, "nativesockets.nim");
	switch (domain) {
	case ((NU8) 0):
	{
		nimln(126, "nativesockets.nim");
		result = AF_UNIX;
	}
	break;
	case ((NU8) 2):
	{
		nimln(127, "nativesockets.nim");
		result = AF_INET;
	}
	break;
	case ((NU8) 23):
	{
		nimln(128, "nativesockets.nim");
		result = AF_INET6;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, toint_162835)(NU8 typ) {
	int result;
	nimfr("toInt", "nativesockets.nim")
	result = 0;
	nimln(132, "nativesockets.nim");
	switch (typ) {
	case ((NU8) 1):
	{
		nimln(133, "nativesockets.nim");
		result = SOCK_STREAM;
	}
	break;
	case ((NU8) 2):
	{
		nimln(134, "nativesockets.nim");
		result = SOCK_DGRAM;
	}
	break;
	case ((NU8) 5):
	{
		nimln(135, "nativesockets.nim");
		result = SOCK_SEQPACKET;
	}
	break;
	case ((NU8) 3):
	{
		nimln(136, "nativesockets.nim");
		result = SOCK_RAW;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, toint_162841)(NU8 p) {
	int result;
	nimfr("toInt", "nativesockets.nim")
	result = 0;
	nimln(140, "nativesockets.nim");
	switch (p) {
	case ((NU8) 6):
	{
		nimln(141, "nativesockets.nim");
		result = IPPROTO_TCP;
	}
	break;
	case ((NU8) 17):
	{
		nimln(142, "nativesockets.nim");
		result = IPPROTO_UDP;
	}
	break;
	case ((NU8) 18):
	{
		nimln(143, "nativesockets.nim");
		result = IPPROTO_IP;
	}
	break;
	case ((NU8) 19):
	{
		nimln(144, "nativesockets.nim");
		result = IPPROTO_IPV6;
	}
	break;
	case ((NU8) 20):
	{
		nimln(145, "nativesockets.nim");
		result = IPPROTO_RAW;
	}
	break;
	case ((NU8) 21):
	{
		nimln(146, "nativesockets.nim");
		result = IPPROTO_ICMP;
	}
	break;
	default:
	{
	}
	break;
	}
	popFrame();
	return result;
}

N_NIMCALL(int, newnativesocket_163004)(NU8 domain, NU8 socktype, NU8 protocol) {
	int result;
	int LOC1;
	int LOC2;
	int LOC3;
	nimfr("newNativeSocket", "nativesockets.nim")
	result = 0;
	nimln(163, "nativesockets.nim");
	nimln(164, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = toint_162829(domain);
	LOC2 = 0;
	LOC2 = toint_162835(socktype);
	LOC3 = 0;
	LOC3 = toint_162841(protocol);
	result = socket(LOC1, LOC2, LOC3);
	popFrame();
	return result;
}

N_NIMCALL(int, newnativesocket_163016)(int domain, int socktype, int protocol) {
	int result;
	nimfr("newNativeSocket", "nativesockets.nim")
	result = 0;
	nimln(168, "nativesockets.nim");
	nimln(172, "nativesockets.nim");
	result = socket(domain, socktype, protocol);
	popFrame();
	return result;
}

N_NIMCALL(void, close_163028)(int socket) {
	int LOC1;
	nimfr("close", "nativesockets.nim")
	nimln(179, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = close(socket);
	popFrame();
}

N_NIMCALL(int, bindaddr_163214)(int socket, struct sockaddr* name, socklen_t namelen) {
	int result;
	nimfr("bindAddr", "nativesockets.nim")
	result = 0;
	nimln(184, "nativesockets.nim");
	result = bind(socket, name, namelen);
	popFrame();
	return result;
}

N_NIMCALL(int, listen_163227)(int socket, int backlog) {
	int result;
	nimfr("listen", "nativesockets.nim")
	result = 0;
	nimln(193, "nativesockets.nim");
	result = listen(socket, backlog);
	popFrame();
	return result;
}

N_NIMCALL(struct addrinfo*, getaddrinfo_163408)(NimStringDesc* address, NU16 port, NU8 domain, NU8 socktype, NU8 protocol) {
	struct addrinfo* result;
	struct addrinfo hints;
	int gairesult;
	NimStringDesc* LOC1;
	nimfr("getAddrInfo", "nativesockets.nim")
	result = 0;
	memset((void*)(&hints), 0, sizeof(hints));
	nimln(202, "nativesockets.nim");
	result = NIM_NIL;
	nimln(203, "nativesockets.nim");
	hints.ai_family = toint_162829(domain);
	nimln(204, "nativesockets.nim");
	hints.ai_socktype = toint_162835(socktype);
	nimln(205, "nativesockets.nim");
	hints.ai_protocol = toint_162841(protocol);
	nimln(208, "nativesockets.nim");
	hints.ai_flags = AI_V4MAPPED;
	nimln(209, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = HEX24_8801(port);
	gairesult = getaddrinfo(address->data, LOC1->data, (&hints), &result);
	nimln(210, "nativesockets.nim");
	{
		NI32 LOC6;
		NCSTRING LOC7;
		NimStringDesc* LOC8;
		nimln(349, "system.nim");
		if (!!((gairesult == ((NI32) 0)))) goto LA4;
		nimln(214, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		LOC7 = 0;
		LOC7 = (char *)gai_strerror(gairesult);
		LOC8 = 0;
		LOC8 = cstrToNimstr(LOC7);
		raiseoserror_127009(LOC6, LOC8);
	}
	LA4: ;
	popFrame();
	return result;
}

N_NIMCALL(void, dealloc_163808)(struct addrinfo* ai) {
	nimfr("dealloc", "nativesockets.nim")
	nimln(217, "nativesockets.nim");
	freeaddrinfo(ai);
	popFrame();
}

N_NIMCALL(NI32, ntohl_163818)(NI32 x) {
	NI32 result;
	nimfr("ntohl", "nativesockets.nim")
	result = 0;
	nimln(224, "nativesockets.nim");
	nimln(226, "nativesockets.nim");
	nimln(225, "nativesockets.nim");
	nimln(224, "nativesockets.nim");
	nimln(225, "nativesockets.nim");
	nimln(226, "nativesockets.nim");
	nimln(227, "nativesockets.nim");
	result = (NI32)((NI32)((NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 24))) | (NI32)((NI32)((NU32)(x) >> (NU32)(((NI32) 8))) & ((NI32) 65280))) | (NI32)((NI32)((NU32)(x) << (NU32)(((NI32) 8))) & ((NI32) 16711680))) | (NI32)((NU32)(x) << (NU32)(((NI32) 24))));
	popFrame();
	return result;
}

N_NIMCALL(NI16, ntohs_164007)(NI16 x) {
	NI16 result;
	nimfr("ntohs", "nativesockets.nim")
	result = 0;
	nimln(234, "nativesockets.nim");
	result = (NI16)((NI16)((NU16)(x) >> (NU16)(((NI16) 8))) | (NI16)((NU16)(x) << (NU16)(((NI16) 8))));
	popFrame();
	return result;
}

N_NIMCALL(void, getservbyname_164219)(NimStringDesc* name, NimStringDesc* proto, Servent162610* Result) {
	struct servent* s;
	nimfr("getServByName", "nativesockets.nim")
	nimln(257, "nativesockets.nim");
	s = getservbyname(name->data, proto->data);
	nimln(258, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_127034();
		raiseoserror_127009(LOC5, ((NimStringDesc*) &TMP614));
	}
	LA3: ;
	nimln(259, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln(260, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_17443((*s).s_aliases));
	nimln(261, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln(262, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = 0;
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (a <= i);
		if (!(LOC3)) goto LA4;
		LOC3 = (i <= b);
		LA4: ;
		if (!LOC3) goto LA5;
		result = i;
		goto BeforeRet;
	}
	goto LA1;
	LA5: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1: ;
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, getservbyport_164420)(NU16 port, NimStringDesc* proto, Servent162610* Result) {
	struct servent* s;
	nimfr("getServByPort", "nativesockets.nim")
	nimln(273, "nativesockets.nim");
	s = getservbyport(((int)chckRange(((NI)(NU)(NU16)(((NI16)chckRange(port, ((NI16) -32768), ((NI16) 32767))))), ((int) (-2147483647 -1)), ((int) 2147483647))), proto->data);
	nimln(274, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_127034();
		raiseoserror_127009(LOC5, ((NimStringDesc*) &TMP614));
	}
	LA3: ;
	nimln(275, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).s_name));
	nimln(276, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_17443((*s).s_aliases));
	nimln(277, "nativesockets.nim");
	(*Result).port = ((NU16) ((*s).s_port));
	nimln(278, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).proto), cstrToNimstr((*s).s_proto));
	popFrame();
}

N_NIMCALL(void, gethostbyaddr_164620)(NimStringDesc* ip, Hostent162612* Result) {
	struct in_addr myaddr;
	struct hostent* s;
	nimfr("getHostByAddr", "nativesockets.nim")
	memset((void*)(&myaddr), 0, sizeof(myaddr));
	nimln(283, "nativesockets.nim");
	myaddr.s_addr = inet_addr(ip->data);
	nimln(290, "nativesockets.nim");
	s = gethostbyaddr(((void*) ((&myaddr))), ((socklen_t) (((NI)sizeof(struct in_addr)))), AF_INET);
	nimln(292, "nativesockets.nim");
	{
		NI32 LOC5;
		NCSTRING LOC6;
		NimStringDesc* LOC7;
		if (!(s == NIM_NIL)) goto LA3;
		nimln(293, "nativesockets.nim");
		LOC5 = 0;
		LOC5 = oslasterror_127034();
		LOC6 = 0;
		LOC6 = (char *)hstrerror(h_errno);
		LOC7 = 0;
		LOC7 = cstrToNimstr(LOC6);
		raiseoserror_127009(LOC5, LOC7);
	}
	LA3: ;
	nimln(295, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln(296, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_17443((*s).h_aliases));
	nimln(300, "nativesockets.nim");
	{
		if (!((*s).h_addrtype == AF_INET)) goto LA10;
		nimln(301, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 2);
	}
	goto LA8;
	LA10: ;
	{
		nimln(302, "nativesockets.nim");
		if (!((*s).h_addrtype == AF_INET6)) goto LA13;
		nimln(303, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 23);
	}
	goto LA8;
	LA13: ;
	{
		NI32 LOC16;
		nimln(305, "nativesockets.nim");
		LOC16 = 0;
		LOC16 = oslasterror_127034();
		raiseoserror_127009(LOC16, ((NimStringDesc*) &TMP615));
	}
	LA8: ;
	nimln(306, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_17443((*s).h_addr_list));
	nimln(307, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_NIMCALL(void, gethostbyname_165010)(NimStringDesc* name, Hostent162612* Result) {
	struct hostent* s;
	nimfr("getHostByName", "nativesockets.nim")
	nimln(314, "nativesockets.nim");
	s = gethostbyname(name->data);
	nimln(315, "nativesockets.nim");
	{
		NI32 LOC5;
		if (!(s == NIM_NIL)) goto LA3;
		LOC5 = 0;
		LOC5 = oslasterror_127034();
		raiseoserror_127009(LOC5, ((NimStringDesc*) &TMP616));
	}
	LA3: ;
	nimln(316, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).name), cstrToNimstr((*s).h_name));
	nimln(317, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).aliases), cstringarraytoseq_17443((*s).h_aliases));
	nimln(321, "nativesockets.nim");
	{
		if (!((*s).h_addrtype == AF_INET)) goto LA8;
		nimln(322, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 2);
	}
	goto LA6;
	LA8: ;
	{
		nimln(323, "nativesockets.nim");
		if (!((*s).h_addrtype == AF_INET6)) goto LA11;
		nimln(324, "nativesockets.nim");
		(*Result).addrtype = ((NU8) 23);
	}
	goto LA6;
	LA11: ;
	{
		NI32 LOC14;
		nimln(326, "nativesockets.nim");
		LOC14 = 0;
		LOC14 = oslasterror_127034();
		raiseoserror_127009(LOC14, ((NimStringDesc*) &TMP615));
	}
	LA6: ;
	nimln(327, "nativesockets.nim");
	unsureAsgnRef((void**) (&(*Result).addrlist), cstringarraytoseq_17443((*s).h_addr_list));
	nimln(328, "nativesockets.nim");
	(*Result).length = ((NI) ((*s).h_length));
	popFrame();
}

N_NIMCALL(NU8, getsockdomain_165408)(int socket) {
	NU8 result;
	struct sockaddr name;
	socklen_t namelen;
	nimfr("getSockDomain", "nativesockets.nim")
	result = 0;
	memset((void*)(&name), 0, sizeof(name));
	nimln(333, "nativesockets.nim");
	namelen = ((socklen_t) (((NI)sizeof(struct sockaddr))));
	nimln(334, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(335, "nativesockets.nim");
		nimln(334, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(336, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP616));
	}
	LA4: ;
	nimln(337, "nativesockets.nim");
	{
		if (!(name.sa_family == nativeafinet_162652)) goto LA9;
		nimln(338, "nativesockets.nim");
		result = ((NU8) 2);
	}
	goto LA7;
	LA9: ;
	{
		nimln(339, "nativesockets.nim");
		if (!(name.sa_family == nativeafinet6_162653)) goto LA12;
		nimln(340, "nativesockets.nim");
		result = ((NU8) 23);
	}
	goto LA7;
	LA12: ;
	{
		NI32 LOC15;
		nimln(342, "nativesockets.nim");
		LOC15 = 0;
		LOC15 = oslasterror_127034();
		raiseoserror_127009(LOC15, ((NimStringDesc*) &TMP617));
	}
	LA7: ;
	popFrame();
	return result;
}

N_NIMCALL(NimStringDesc*, getaddrstring_165425)(struct sockaddr* sockaddr) {
	NimStringDesc* result;
	nimfr("getAddrString", "nativesockets.nim")
	result = 0;
	nimln(347, "nativesockets.nim");
	{
		NCSTRING LOC5;
		if (!((*sockaddr).sa_family == nativeafinet_162652)) goto LA3;
		nimln(348, "nativesockets.nim");
		LOC5 = 0;
		LOC5 = inet_ntoa((*((struct sockaddr_in*) (sockaddr))).sin_addr);
		result = cstrToNimstr(LOC5);
	}
	goto LA1;
	LA3: ;
	{
		struct in6_addr* addr6;
		NCSTRING LOC9;
		nimln(349, "nativesockets.nim");
		if (!((*sockaddr).sa_family == nativeafinet6_162653)) goto LA7;
		nimln(352, "nativesockets.nim");
		result = mnewString(((NI)chckRange(INET6_ADDRSTRLEN, ((NI) 0), ((NI) IL64(9223372036854775807)))));
		nimln(353, "nativesockets.nim");
		addr6 = (&(*((struct sockaddr_in6*) (sockaddr))).sin6_addr);
		nimln(354, "nativesockets.nim");
		nimln(355, "nativesockets.nim");
		LOC9 = 0;
		LOC9 = (char *)inet_ntop(AF_INET6, ((void*) (addr6)), result->data, ((NI32)chckRange((result ? result->Sup.len : 0), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
		nimln(356, "nativesockets.nim");
		{
			int LOC12;
			nimln(349, "system.nim");
			nimln(356, "nativesockets.nim");
			LOC12 = 0;
			LOC12 = IN6_IS_ADDR_V4MAPPED(addr6);
			if (!!((LOC12 == ((NI32) 0)))) goto LA13;
			nimln(357, "nativesockets.nim");
			result = copyStr(result, ((NI) 7));
		}
		LA13: ;
	}
	goto LA1;
	LA7: ;
	{
		NI32 LOC16;
		nimln(359, "nativesockets.nim");
		LOC16 = 0;
		LOC16 = oslasterror_127034();
		raiseoserror_127009(LOC16, ((NimStringDesc*) &TMP618));
	}
	LA1: ;
	popFrame();
	return result;
}

N_NIMCALL(NU16, getsockname_165612)(int socket) {
	NU16 result;
	struct sockaddr_in name;
	socklen_t namelen;
	NI16 LOC7;
	nimfr("getSockName", "nativesockets.nim")
	result = 0;
	memset((void*)(&name), 0, sizeof(name));
	nimln(368, "nativesockets.nim");
	name.sin_family = AF_INET;
	nimln(371, "nativesockets.nim");
	namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
	nimln(372, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(373, "nativesockets.nim");
		nimln(372, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
		if (!(LOC3 == ((NI32) -1))) goto LA4;
		nimln(374, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP616));
	}
	LA4: ;
	nimln(375, "nativesockets.nim");
	LOC7 = 0;
	LOC7 = ntohs_164007(name.sin_port);
	result = ((NU16) (LOC7));
	popFrame();
	return result;
}

N_NIMCALL(void, getlocaladdr_165813)(int socket, NU8 domain, TY165817* Result) {
	nimfr("getLocalAddr", "nativesockets.nim")
	nimln(381, "nativesockets.nim");
	switch (domain) {
	case ((NU8) 2):
	{
		struct sockaddr_in name;
		socklen_t namelen;
		NCSTRING LOC8;
		NI16 LOC9;
		memset((void*)(&name), 0, sizeof(name));
		nimln(387, "nativesockets.nim");
		name.sin_family = AF_INET;
		nimln(388, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln(389, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			nimln(390, "nativesockets.nim");
			nimln(389, "nativesockets.nim");
			LOC4 = 0;
			LOC4 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(391, "nativesockets.nim");
			LOC7 = 0;
			LOC7 = oslasterror_127034();
			raiseoserror_127009(LOC7, ((NimStringDesc*) &TMP616));
		}
		LA5: ;
		nimln(392, "nativesockets.nim");
		LOC8 = 0;
		LOC8 = inet_ntoa(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(393, "nativesockets.nim");
		LOC9 = 0;
		LOC9 = ntohs_164007(name.sin_port);
		(*Result).Field1 = ((NU16) (LOC9));
	}
	break;
	case ((NU8) 23):
	{
		struct sockaddr_in6 name;
		socklen_t namelen;
		TY166206 buf;
		NI16 LOC23;
		memset((void*)(&name), 0, sizeof(name));
		nimln(399, "nativesockets.nim");
		name.sin6_family = AF_INET6;
		nimln(400, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln(401, "nativesockets.nim");
		{
			int LOC13;
			NI32 LOC16;
			nimln(402, "nativesockets.nim");
			nimln(401, "nativesockets.nim");
			LOC13 = 0;
			LOC13 = getsockname(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC13 == ((NI32) -1))) goto LA14;
			nimln(403, "nativesockets.nim");
			LOC16 = 0;
			LOC16 = oslasterror_127034();
			raiseoserror_127009(LOC16, ((NimStringDesc*) &TMP616));
		}
		LA14: ;
		memset((void*)buf, 0, sizeof(buf));
		nimln(406, "nativesockets.nim");
		{
			NCSTRING LOC19;
			NI32 LOC22;
			nimln(407, "nativesockets.nim");
			nimln(406, "nativesockets.nim");
			nimln(407, "nativesockets.nim");
			LOC19 = 0;
			LOC19 = (char *)inet_ntop(name.sin6_family, ((void*) ((&name))), ((NCSTRING) (buf)), ((NI32)chckRange(((NI)sizeof(TY166206)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!LOC19 == 0) goto LA20;
			nimln(408, "nativesockets.nim");
			LOC22 = 0;
			LOC22 = oslasterror_127034();
			raiseoserror_127009(LOC22, ((NimStringDesc*) &TMP616));
		}
		LA20: ;
		nimln(409, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf))));
		LOC23 = 0;
		LOC23 = ntohs_164007(name.sin6_port);
		(*Result).Field1 = ((NU16) (LOC23));
	}
	break;
	default:
	{
		nimln(411, "nativesockets.nim");
		raiseoserror_127009(((NI32) -1), ((NimStringDesc*) &TMP619));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(void, getpeeraddr_166223)(int socket, NU8 domain, TY165817* Result) {
	nimfr("getPeerAddr", "nativesockets.nim")
	nimln(417, "nativesockets.nim");
	switch (domain) {
	case ((NU8) 2):
	{
		struct sockaddr_in name;
		socklen_t namelen;
		NCSTRING LOC8;
		NI16 LOC9;
		memset((void*)(&name), 0, sizeof(name));
		nimln(423, "nativesockets.nim");
		name.sin_family = AF_INET;
		nimln(424, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in))));
		nimln(425, "nativesockets.nim");
		{
			int LOC4;
			NI32 LOC7;
			nimln(426, "nativesockets.nim");
			nimln(425, "nativesockets.nim");
			LOC4 = 0;
			LOC4 = getpeername(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC4 == ((NI32) -1))) goto LA5;
			nimln(427, "nativesockets.nim");
			LOC7 = 0;
			LOC7 = oslasterror_127034();
			raiseoserror_127009(LOC7, ((NimStringDesc*) &TMP616));
		}
		LA5: ;
		nimln(428, "nativesockets.nim");
		LOC8 = 0;
		LOC8 = inet_ntoa(name.sin_addr);
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(LOC8));
		nimln(429, "nativesockets.nim");
		LOC9 = 0;
		LOC9 = ntohs_164007(name.sin_port);
		(*Result).Field1 = ((NU16) (LOC9));
	}
	break;
	case ((NU8) 23):
	{
		struct sockaddr_in6 name;
		socklen_t namelen;
		TY166206 buf;
		NI16 LOC23;
		memset((void*)(&name), 0, sizeof(name));
		nimln(435, "nativesockets.nim");
		name.sin6_family = AF_INET6;
		nimln(436, "nativesockets.nim");
		namelen = ((socklen_t) (((NI)sizeof(struct sockaddr_in6))));
		nimln(437, "nativesockets.nim");
		{
			int LOC13;
			NI32 LOC16;
			nimln(438, "nativesockets.nim");
			nimln(437, "nativesockets.nim");
			LOC13 = 0;
			LOC13 = getpeername(socket, ((struct sockaddr*) ((&name))), (&namelen));
			if (!(LOC13 == ((NI32) -1))) goto LA14;
			nimln(439, "nativesockets.nim");
			LOC16 = 0;
			LOC16 = oslasterror_127034();
			raiseoserror_127009(LOC16, ((NimStringDesc*) &TMP616));
		}
		LA14: ;
		memset((void*)buf, 0, sizeof(buf));
		nimln(442, "nativesockets.nim");
		{
			NCSTRING LOC19;
			NI32 LOC22;
			nimln(443, "nativesockets.nim");
			nimln(442, "nativesockets.nim");
			nimln(443, "nativesockets.nim");
			LOC19 = 0;
			LOC19 = (char *)inet_ntop(name.sin6_family, ((void*) ((&name))), ((NCSTRING) (buf)), ((NI32)chckRange(((NI)sizeof(TY166206)), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
			if (!LOC19 == 0) goto LA20;
			nimln(444, "nativesockets.nim");
			LOC22 = 0;
			LOC22 = oslasterror_127034();
			raiseoserror_127009(LOC22, ((NimStringDesc*) &TMP616));
		}
		LA20: ;
		nimln(445, "nativesockets.nim");
		unsureAsgnRef((void**) (&(*Result).Field0), cstrToNimstr(((NCSTRING) (buf))));
		LOC23 = 0;
		LOC23 = ntohs_164007(name.sin6_port);
		(*Result).Field1 = ((NU16) (LOC23));
	}
	break;
	default:
	{
		nimln(447, "nativesockets.nim");
		raiseoserror_127009(((NI32) -1), ((NimStringDesc*) &TMP619));
	}
	break;
	}
	popFrame();
}

N_NIMCALL(NI, getsockoptint_166623)(int socket, NI level, NI optname) {
	NI result;
	int res;
	socklen_t size;
	nimfr("getSockOptInt", "nativesockets.nim")
	result = 0;
	res = 0;
	nimln(453, "nativesockets.nim");
	size = ((socklen_t) 4);
	nimln(454, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(455, "nativesockets.nim");
		nimln(454, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = getsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&res))), (&size));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(456, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP616));
	}
	LA4: ;
	nimln(457, "nativesockets.nim");
	result = ((NI) (res));
	popFrame();
	return result;
}

N_NIMCALL(void, setsockoptint_166641)(int socket, NI level, NI optname, NI optval) {
	int value;
	nimfr("setSockOptInt", "nativesockets.nim")
	nimln(462, "nativesockets.nim");
	value = ((int)chckRange(optval, ((int) (-2147483647 -1)), ((int) 2147483647)));
	nimln(463, "nativesockets.nim");
	{
		int LOC3;
		NI32 LOC6;
		nimln(464, "nativesockets.nim");
		nimln(463, "nativesockets.nim");
		LOC3 = 0;
		LOC3 = setsockopt(socket, ((int)chckRange(level, ((int) (-2147483647 -1)), ((int) 2147483647))), ((int)chckRange(optname, ((int) (-2147483647 -1)), ((int) 2147483647))), ((void*) ((&value))), ((socklen_t) 4));
		if (!(LOC3 < ((NI32) 0))) goto LA4;
		nimln(465, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP616));
	}
	LA4: ;
	popFrame();
}

N_NIMCALL(void, setblocking_166655)(int s, NIM_BOOL blocking) {
	NI x;
	int LOC1;
	nimfr("setBlocking", "nativesockets.nim")
	nimln(476, "nativesockets.nim");
	LOC1 = 0;
	LOC1 = fcntl(s, F_GETFL, ((NI) 0));
	x = ((NI) (LOC1));
	nimln(477, "nativesockets.nim");
	{
		NI32 LOC6;
		if (!(x == ((NI) -1))) goto LA4;
		nimln(478, "nativesockets.nim");
		LOC6 = 0;
		LOC6 = oslasterror_127034();
		raiseoserror_127009(LOC6, ((NimStringDesc*) &TMP616));
	}
	goto LA2;
	LA4: ;
	{
		NI mode;
		nimln(480, "nativesockets.nim");
		{
			if (!blocking) goto LA10;
			mode = (NI)(x & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));
		}
		goto LA8;
		LA10: ;
		{
			mode = (NI)(x | ((NI) (O_NONBLOCK)));
		}
		LA8: ;
		nimln(481, "nativesockets.nim");
		{
			int LOC15;
			NI32 LOC18;
			LOC15 = 0;
			LOC15 = fcntl(s, F_SETFL, mode);
			if (!(LOC15 == ((NI32) -1))) goto LA16;
			nimln(482, "nativesockets.nim");
			LOC18 = 0;
			LOC18 = oslasterror_127034();
			raiseoserror_127009(LOC18, ((NimStringDesc*) &TMP616));
		}
		LA16: ;
	}
	LA2: ;
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = 0;
	{
		if (!(b == ((NI) 0))) goto LA3;
		raiseDivByZero();
	}
	LA3: ;
	{
		NIM_BOOL LOC7;
		LOC7 = 0;
		LOC7 = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(LOC7)) goto LA8;
		LOC7 = (b == ((NI) -1));
		LA8: ;
		if (!LOC7) goto LA9;
		raiseOverflow();
	}
	LA9: ;
	result = (NI)(a / b);
	goto BeforeRet;
	}BeforeRet: ;
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(struct timeval, timevalfrommilliseconds_166828)(NI timeout) {
	struct timeval result;
	nimfr("timeValFromMilliseconds", "nativesockets.nim")
	memset((void*)(&result), 0, sizeof(result));
	nimln(485, "nativesockets.nim");
	{
		NI seconds;
		NI TMP620;
		NI TMP621;
		NI TMP622;
		NI TMP623;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(486, "nativesockets.nim");
		TMP620 = divInt(timeout, ((NI) 1000));
		seconds = (NI)(TMP620);
		nimln(487, "nativesockets.nim");
		result.tv_sec = ((NI) (((NI32)chckRange(seconds, ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
		nimln(488, "nativesockets.nim");
		TMP621 = mulInt(seconds, ((NI) 1000));
		TMP622 = subInt(timeout, (NI)(TMP621));
		TMP623 = mulInt((NI)(TMP622), ((NI) 1000));
		result.tv_usec = ((NI) (((NI32)chckRange((NI)(TMP623), ((NI32) (-2147483647 -1)), ((NI32) 2147483647)))));
	}
	LA3: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = 0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL LOC3;
		LOC3 = 0;
		LOC3 = (((NI) 0) <= (NI)(result ^ a));
		if (LOC3) goto LA4;
		LOC3 = (((NI) 0) <= (NI)(result ^ b));
		LA4: ;
		if (!LOC3) goto LA5;
		goto BeforeRet;
	}
	LA5: ;
	raiseOverflow();
	}BeforeRet: ;
	return result;
}

N_NIMCALL(void, createfdset_166843)(fd_set* fd, TY166847* s, NI* m) {
	nimfr("createFdSet", "nativesockets.nim")
	nimln(491, "nativesockets.nim");
	FD_ZERO(fd);
	{
		int i_167011;
		NI i_167028;
		NI L_167030;
		i_167011 = 0;
		nimln(3365, "system.nim");
		i_167028 = ((NI) 0);
		nimln(3366, "system.nim");
		L_167030 = (s ? s->Sup.len : 0);
		{
			nimln(3367, "system.nim");
			while (1) {
				NI TMP624;
				if (!(i_167028 < L_167030)) goto LA3;
				nimln(3368, "system.nim");
				if ((NU)(i_167028) >= (NU)(s->Sup.len)) raiseIndexError();
				i_167011 = s->data[i_167028];
				nimln(493, "nativesockets.nim");
				(*m) = (((*m) >= ((NI) (i_167011))) ? (*m) : ((NI) (i_167011)));
				nimln(494, "nativesockets.nim");
				FD_SET(i_167011, fd);
				nimln(3369, "system.nim");
				TMP624 = addInt(i_167028, ((NI) 1));
				i_167028 = (NI)(TMP624);
				nimln(3370, "system.nim");
				{
					if (!!(((s ? s->Sup.len : 0) == L_167030))) goto LA6;
					failedassertimpl_91603(((NimStringDesc*) &TMP625));
				}
				LA6: ;
			} LA3: ;
		}
	}
	popFrame();
}

N_NIMCALL(void, prunesocketset_167046)(TY166847** s, fd_set* fd) {
	NI i;
	NI L;
	nimfr("pruneSocketSet", "nativesockets.nim")
	nimln(497, "nativesockets.nim");
	i = ((NI) 0);
	nimln(498, "nativesockets.nim");
	L = ((*s) ? (*s)->Sup.len : 0);
	{
		nimln(499, "nativesockets.nim");
		while (1) {
			if (!(i < L)) goto LA2;
			nimln(500, "nativesockets.nim");
			{
				int LOC5;
				NI TMP626;
				NI TMP627;
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				LOC5 = 0;
				LOC5 = FD_ISSET((*s)->data[i], fd);
				if (!(LOC5 == ((NI32) 0))) goto LA6;
				nimln(501, "nativesockets.nim");
				if ((NU)(i) >= (NU)((*s)->Sup.len)) raiseIndexError();
				TMP626 = subInt(L, ((NI) 1));
				if ((NU)((NI)(TMP626)) >= (NU)((*s)->Sup.len)) raiseIndexError();
				(*s)->data[i] = (*s)->data[(NI)(TMP626)];
				nimln(502, "nativesockets.nim");
				TMP627 = subInt(L, ((NI) 1));
				L = (NI)(TMP627);
			}
			goto LA3;
			LA6: ;
			{
				NI TMP628;
				nimln(504, "nativesockets.nim");
				TMP628 = addInt(i, ((NI) 1));
				i = (NI)(TMP628);
			}
			LA3: ;
		} LA2: ;
	}
	nimln(505, "nativesockets.nim");
	(*s) = (TY166847*) setLengthSeq(&((*s))->Sup, sizeof(int), ((NI)chckRange(L, ((NI) 0), ((NI) IL64(9223372036854775807)))));
	popFrame();
}

N_NIMCALL(NI, select_167113)(TY166847** readfds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set rd;
	NI m;
	nimfr("select", "nativesockets.nim")
	result = 0;
	nimln(515, "nativesockets.nim");
	tv = timevalfrommilliseconds_166828(timeout);
	memset((void*)(&rd), 0, sizeof(rd));
	nimln(518, "nativesockets.nim");
	m = ((NI) 0);
	nimln(519, "nativesockets.nim");
	createfdset_166843((&rd), (*readfds), (&m));
	nimln(521, "nativesockets.nim");
	{
		NI TMP629;
		int LOC5;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(522, "nativesockets.nim");
		TMP629 = addInt(m, ((NI) 1));
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI)(TMP629), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP630;
		int LOC7;
		nimln(524, "nativesockets.nim");
		TMP630 = addInt(m, ((NI) 1));
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI)(TMP630), ((int) (-2147483647 -1)), ((int) 2147483647))), (&rd), NIM_NIL, NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(526, "nativesockets.nim");
	prunesocketset_167046(readfds, (&rd));
	popFrame();
	return result;
}

N_NIMCALL(NI, selectwrite_167170)(TY166847** writefds, NI timeout) {
	NI result;
	struct timeval tv;
	fd_set wr;
	NI m;
	nimfr("selectWrite", "nativesockets.nim")
	result = 0;
	nimln(537, "nativesockets.nim");
	tv = timevalfrommilliseconds_166828(timeout);
	memset((void*)(&wr), 0, sizeof(wr));
	nimln(540, "nativesockets.nim");
	m = ((NI) 0);
	nimln(541, "nativesockets.nim");
	createfdset_166843((&wr), (*writefds), (&m));
	nimln(543, "nativesockets.nim");
	{
		NI TMP631;
		int LOC5;
		nimln(349, "system.nim");
		if (!!((timeout == ((NI) -1)))) goto LA3;
		nimln(544, "nativesockets.nim");
		TMP631 = addInt(m, ((NI) 1));
		LOC5 = 0;
		LOC5 = select(((int)chckRange((NI)(TMP631), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, (&tv));
		result = ((NI) (LOC5));
	}
	goto LA1;
	LA3: ;
	{
		NI TMP632;
		int LOC7;
		nimln(546, "nativesockets.nim");
		TMP632 = addInt(m, ((NI) 1));
		LOC7 = 0;
		LOC7 = select(((int)chckRange((NI)(TMP632), ((int) (-2147483647 -1)), ((int) 2147483647))), NIM_NIL, (&wr), NIM_NIL, NIM_NIL);
		result = ((NI) (LOC7));
	}
	LA1: ;
	nimln(548, "nativesockets.nim");
	prunesocketset_167046(writefds, (&wr));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsInit000)(void) {
	nimfr("nativesockets", "nativesockets.nim")
	nimln(104, "nativesockets.nim");
	osinvalidsocket_162651 = ((int) -1);
	nimln(105, "nativesockets.nim");
	nativeafinet_162652 = AF_INET;
	nimln(106, "nativesockets.nim");
	nativeafinet6_162653 = AF_INET6;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_nativesocketsDatInit000)(void) {
static TNimNode* TMP784[3];
NI TMP786;
static char* NIM_CONST TMP785[3] = {
"AF_UNIX", 
"AF_INET", 
"AF_INET6"};
static TNimNode* TMP787[4];
NI TMP789;
static char* NIM_CONST TMP788[4] = {
"SOCK_STREAM", 
"SOCK_DGRAM", 
"SOCK_RAW", 
"SOCK_SEQPACKET"};
static TNimNode* TMP790[6];
NI TMP792;
static char* NIM_CONST TMP791[6] = {
"IPPROTO_TCP", 
"IPPROTO_UDP", 
"IPPROTO_IP", 
"IPPROTO_IPV6", 
"IPPROTO_RAW", 
"IPPROTO_ICMP"};
static TNimNode TMP606[16];
NTI162604.size = sizeof(NU8);
NTI162604.kind = 14;
NTI162604.base = 0;
NTI162604.flags = 3;
for (TMP786 = 0; TMP786 < 3; TMP786++) {
TMP606[TMP786+0].kind = 1;
TMP606[TMP786+0].offset = TMP786;
TMP606[TMP786+0].name = TMP785[TMP786];
TMP784[TMP786] = &TMP606[TMP786+0];
}
TMP606[0].offset = 0;
TMP606[1].offset = 2;
TMP606[2].offset = 23;
TMP606[3].len = 3; TMP606[3].kind = 2; TMP606[3].sons = &TMP784[0];
NTI162604.node = &TMP606[3];
NTI162604.flags = 1<<2;
NTI162606.size = sizeof(NU8);
NTI162606.kind = 14;
NTI162606.base = 0;
NTI162606.flags = 3;
for (TMP789 = 0; TMP789 < 4; TMP789++) {
TMP606[TMP789+4].kind = 1;
TMP606[TMP789+4].offset = TMP789;
TMP606[TMP789+4].name = TMP788[TMP789];
TMP787[TMP789] = &TMP606[TMP789+4];
}
TMP606[4].offset = 1;
TMP606[5].offset = 2;
TMP606[6].offset = 3;
TMP606[7].offset = 5;
TMP606[8].len = 4; TMP606[8].kind = 2; TMP606[8].sons = &TMP787[0];
NTI162606.node = &TMP606[8];
NTI162606.flags = 1<<2;
NTI162608.size = sizeof(NU8);
NTI162608.kind = 14;
NTI162608.base = 0;
NTI162608.flags = 3;
for (TMP792 = 0; TMP792 < 6; TMP792++) {
TMP606[TMP792+9].kind = 1;
TMP606[TMP792+9].offset = TMP792;
TMP606[TMP792+9].name = TMP791[TMP792];
TMP790[TMP792] = &TMP606[TMP792+9];
}
TMP606[9].offset = 6;
TMP606[10].offset = 17;
TMP606[11].offset = 18;
TMP606[12].offset = 19;
TMP606[13].offset = 20;
TMP606[14].offset = 21;
TMP606[15].len = 6; TMP606[15].kind = 2; TMP606[15].sons = &TMP790[0];
NTI162608.node = &TMP606[15];
NTI162608.flags = 1<<2;
}

